// This file is auto-generated by @hey-api/openapi-ts

export const ParticipantDataFieldDropdownChoicesSchema = {
    type: 'object',
    properties: {
        participantdatafielddropdownchoices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParticipantDataFieldDropdownChoice'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        participantdatafielddropdownchoices: {
            '$ref': '#/components/schemas/ParticipantDataFieldDropdownChoicePageData'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoicePageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of Participant Data Field Dropdown Choices returned by the underlying query.',
            type: 'integer',
            example: 4
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of custom Participant Data Field Dropdown Choices.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of custom Participant Data Field Dropdown Choices.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantdatafielddropdownchoices?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of custom Participant Data Field Dropdown Choices.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantdatafielddropdownchoices?page=3'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoiceSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'Name for the participant data field dropdown choice. This is the display name shown on the UI.',
            type: 'string',
            example: 'Red'
        },
        value: {
            description: 'The value that will be copied when the participant data field dropdown choice is selected.',
            type: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which the participant data field dropdown choice appears in the dropdown list. If a listOrder value shares the same value as another choice, the choices are displayed in name order.',
            type: 'integer',
            example: 5
        },
        isDefault: {
            description: 'Indicates if the choice item is the default selected item displayed in the dropdown list. A list can only contain one default item for a single select dropdown, but can have multiple defaults for a multi-select dropdown.',
            type: 'string',
            enum: ['T', 'F'],
            example: 'T'
        },
        links: {
            '$ref': '#/components/schemas/ParticipantDataFieldDropdownChoiceLinks'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoiceLinksSchema = {
    type: 'object',
    properties: {
        participantType: {
            description: 'Unique identifier for the underlying participant type to which this data field dropdown choice is associated.',
            type: 'integer',
            format: 'string',
            example: 7383,
            readOnly: true
        },
        participantDataField: {
            description: 'Unique identifier for the participant data field associated with this data field dropdown choice.',
            type: 'integer',
            format: 'string',
            example: 2300
        }
    }
} as const;

export const CreateParticipantDataFieldDropdownChoiceSchema = {
    type: 'object',
    required: ['name', 'value', 'listOrder', 'isDefault', 'participantDataField'],
    properties: {
        name: {
            description: 'Name for the participant data field dropdown choice. This is the display name shown on the UI. The name must be unique.',
            type: 'string',
            example: 'Red'
        },
        value: {
            description: 'The value that will be copied when the participant data field dropdown choice is selected.',
            type: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which the participant data field dropdown choice appears in the dropdown list. If a listOrder value shares the same value as another choice, the choices are displayed in name order.',
            type: 'integer',
            example: 5
        },
        isDefault: {
            description: 'Indicates if the choice item is the default selected item displayed in the dropdown list. A list can only contain one default item for single select dropdown, but can have multiple defaults for a multi-select dropdown.',
            type: 'string',
            enum: ['T', 'F'],
            example: 'T'
        },
        links: {
            '$ref': '#/components/schemas/CreateParticipantDataFieldDropdownChoiceLinks'
        }
    }
} as const;

export const CreateParticipantDataFieldDropdownChoiceLinksSchema = {
    type: 'object',
    properties: {
        participantDataField: {
            description: 'Unique identifier for the participant data field associated with this data field dropdown choice.',
            type: 'integer',
            format: 'string',
            example: 2300
        }
    }
} as const;

export const UpdateParticipantDataFieldDropdownChoiceSchema = {
    type: 'object',
    properties: {
        value: {
            description: 'The value that will be copied when the participant data field dropdown choice is selected.',
            type: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which the participant data field dropdown choice appears in the dropdown list. If a listOrder value shares the same value as another choice, the choices are displayed in name order.',
            type: 'integer',
            example: 5
        },
        isDefault: {
            description: 'Indicates if the choice item is the default selected item displayed in the dropdown list. A list can only contain one default item for single select dropdown, but can have multiple defaults for a multi-select dropdown.',
            type: 'string',
            enum: ['T', 'F'],
            example: 'T'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoicesWritableSchema = {
    type: 'object',
    properties: {
        participantdatafielddropdownchoices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParticipantDataFieldDropdownChoiceWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoiceWritableSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'Name for the participant data field dropdown choice. This is the display name shown on the UI.',
            type: 'string',
            example: 'Red'
        },
        value: {
            description: 'The value that will be copied when the participant data field dropdown choice is selected.',
            type: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which the participant data field dropdown choice appears in the dropdown list. If a listOrder value shares the same value as another choice, the choices are displayed in name order.',
            type: 'integer',
            example: 5
        },
        isDefault: {
            description: 'Indicates if the choice item is the default selected item displayed in the dropdown list. A list can only contain one default item for a single select dropdown, but can have multiple defaults for a multi-select dropdown.',
            type: 'string',
            enum: ['T', 'F'],
            example: 'T'
        },
        links: {
            '$ref': '#/components/schemas/ParticipantDataFieldDropdownChoiceLinksWritable'
        }
    }
} as const;

export const ParticipantDataFieldDropdownChoiceLinksWritableSchema = {
    type: 'object',
    properties: {
        participantDataField: {
            description: 'Unique identifier for the participant data field associated with this data field dropdown choice.',
            type: 'integer',
            format: 'string',
            example: 2300
        }
    }
} as const;
