// This file is auto-generated by @hey-api/openapi-ts

export const PagedParticipantDefaultTypesSchema = {
    type: 'object',
    properties: {
        participantdefaulttypes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParticipantDefaultType'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        participantdefaulttypes: {
            '$ref': '#/components/schemas/ParticipantDefaultTypesPageData'
        }
    }
} as const;

export const ParticipantDefaultTypesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of participant default types returned by the underlying query.',
            type: 'integer',
            example: 23
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 47
        },
        page: {
            description: 'The page number for this page of participant default types.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of participant default types.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantdefaulttypes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of participant default types.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantdefaulttypes?page=3'
        }
    }
} as const;

export const ParticipantDefaultTypeSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for a participant default type. The identifier is a composite value composed from the participant identifier and the participant type identifier, separated by "--".',
            example: '1024--31',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/ParticipantDefaultTypeLinks'
        }
    }
} as const;

export const ParticipantDefaultTypeLinksSchema = {
    type: 'object',
    properties: {
        participantType: {
            description: 'Unique identifier of the participant type.',
            example: 31,
            type: 'integer'
        },
        participant: {
            description: 'Unique identifier of the participant.',
            example: 1024,
            type: 'integer'
        }
    }
} as const;

export const CreateParticipantDefaultTypeSchema = {
    type: 'object',
    properties: {
        participantdefaulttypes: {
            '$ref': '#/components/schemas/CreateParticipantDefaultTypeLinks'
        }
    }
} as const;

export const CreateParticipantDefaultTypeLinksSchema = {
    type: 'object',
    properties: {
        links: {
            '$ref': '#/components/schemas/CreateParticipantDefaultTypeLinksLink'
        }
    }
} as const;

export const CreateParticipantDefaultTypeLinksLinkSchema = {
    type: 'object',
    properties: {
        participantType: {
            description: 'Unique identifier of the participant type.',
            example: 31,
            type: 'integer'
        },
        participant: {
            description: 'Unique identifier of the participant.',
            example: 1024,
            type: 'integer'
        }
    }
} as const;
