// This file is auto-generated by @hey-api/openapi-ts

export const PagedDataCollectionsSchema = {
    type: 'object',
    properties: {
        datacollections: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollection'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        datacollections: {
            '$ref': '#/components/schemas/DataCollectionsPageData'
        }
    }
} as const;

export const DataCollectionsPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of data collections returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of data collections.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of data collections.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollections?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of data collections.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollections?page=3'
        }
    }
} as const;

export const DataCollectionSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the data collection.',
            example: 2347,
            type: 'integer',
            readOnly: true
        },
        name: {
            description: 'Name for the data collection.',
            example: 'AMLData',
            type: 'string'
        },
        description: {
            description: 'Description for the data collection.',
            example: 'AML status and progress values.',
            type: 'string'
        },
        multipleRecords: {
            description: 'Indicates if the data collection supports multiple records of values.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        order: {
            description: 'The display order compared to other data collections.',
            example: 5,
            type: 'integer'
        },
        label: {
            description: 'The display label for the data collection.',
            example: 'AML Certification',
            type: 'string'
        },
        alwaysShowDescriptions: {
            description: 'Indicates if the data collection description should always be displayed.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionLinks'
        }
    }
} as const;

export const DataCollectionLinksSchema = {
    type: 'object',
    properties: {
        actionType: {
            description: 'Unique identifier of the matter type to which the data collection is associated.',
            example: 822,
            type: 'integer'
        }
    }
} as const;

export const CreateDataCollectionSchema = {
    type: 'object',
    required: ['name', 'description'],
    properties: {
        name: {
            description: 'Name for the data collection.',
            example: 'AMLData',
            type: 'string'
        },
        description: {
            description: 'Description for the data collection.',
            example: 'AML status and progress values.',
            type: 'string'
        },
        multipleRecords: {
            description: 'Indicates if the data collection supports multiple records of values.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        order: {
            description: 'The display order compared to other data collections.',
            example: 5,
            type: 'integer'
        },
        label: {
            description: 'The display label for the data collection.',
            example: 'AML Certification',
            type: 'string'
        },
        alwaysShowDescriptions: {
            description: 'Indicates if the data collection description should always be displayed.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/CreateDataCollectionLinks'
        }
    }
} as const;

export const CreateDataCollectionLinksSchema = {
    type: 'object',
    required: ['actionType'],
    properties: {
        actionType: {
            description: 'Unique identifier of the matter type to which the data collection is associated.',
            example: 822,
            type: 'integer'
        }
    }
} as const;

export const UpdateDataCollectionSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'Name for the data collection.',
            example: 'AMLData',
            type: 'string'
        },
        description: {
            description: 'Description for the data collection.',
            example: 'AML status and progress values.',
            type: 'string'
        },
        multipleRecords: {
            description: 'Indicates if the data collection supports multiple records of values.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        order: {
            description: 'The display order compared to other data collections.',
            example: 5,
            type: 'integer'
        },
        label: {
            description: 'The display label for the data collection.',
            example: 'AML Certification',
            type: 'string'
        },
        alwaysShowDescriptions: {
            description: 'Indicates if the data collection description should always be displayed.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/UpdateDataCollectionLinks'
        }
    }
} as const;

export const UpdateDataCollectionLinksSchema = {
    type: 'object',
    properties: {
        actionType: {
            description: 'Unique identifier of the matter type to which the data collection is associated.',
            example: 822,
            type: 'integer'
        }
    }
} as const;

export const PagedDataCollectionsWritableSchema = {
    type: 'object',
    properties: {
        datacollections: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const DataCollectionWritableSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'Name for the data collection.',
            example: 'AMLData',
            type: 'string'
        },
        description: {
            description: 'Description for the data collection.',
            example: 'AML status and progress values.',
            type: 'string'
        },
        multipleRecords: {
            description: 'Indicates if the data collection supports multiple records of values.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        order: {
            description: 'The display order compared to other data collections.',
            example: 5,
            type: 'integer'
        },
        label: {
            description: 'The display label for the data collection.',
            example: 'AML Certification',
            type: 'string'
        },
        alwaysShowDescriptions: {
            description: 'Indicates if the data collection description should always be displayed.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionLinks'
        }
    }
} as const;
