// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedRestHooks = {
    resthooks?: Array<RestHook>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    resthooks?: RestHooksPageData;
};

export type RestHooksPageData = {
    /**
     * The total number of REST hooks returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of REST hooks.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of REST hooks.
     */
    prevPage?: string;
    /**
     * A URL to the next page of REST hooks.
     */
    nextPage?: string;
};

export type RestHook = {
    /**
     * Unique identifier for the REST hook.
     */
    id?: number;
    /**
     * Name of the event.
     */
    eventName?: string;
    /**
     * Url to be called.
     */
    targetUrl?: string;
    /**
     * Status of the REST hook.
     */
    status?: 'Active' | 'Disabled' | 'Deleted';
    /**
     * Number of times the REST hook has been triggered.
     */
    triggeredCount?: number;
    /**
     * The last date and time the REST hook was triggered.
     */
    triggeredLastTimestamp?: string;
};

export type CreateRestHook = {
    /**
     * Name of the event.
     */
    eventName: string;
    /**
     * Url to be called.
     */
    targetUrl: string;
};

export type UpdateRestHook = {
    /**
     * Name of the event.
     */
    eventName: string;
    /**
     * Url to be called.
     */
    targetUrl: string;
};

export type CreateRestHook2 = CreateRestHook;

export type UpdateRestHook2 = UpdateRestHook;

export type GetResthooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resthooks';
};

export type GetResthooksResponses = {
    /**
     * OK.
     */
    200: PagedRestHooks;
};

export type GetResthooksResponse = GetResthooksResponses[keyof GetResthooksResponses];

export type PostResthooksData = {
    body?: CreateRestHook2;
    path?: never;
    query?: never;
    url: '/resthooks';
};

export type PostResthooksResponses = {
    /**
     * OK.
     */
    200: RestHook;
};

export type PostResthooksResponse = PostResthooksResponses[keyof PostResthooksResponses];

export type DeleteResthooksByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a REST hook.
         */
        id: number;
    };
    query?: never;
    url: '/resthooks/{id}';
};

export type DeleteResthooksByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteResthooksByIdResponse = DeleteResthooksByIdResponses[keyof DeleteResthooksByIdResponses];

export type GetResthooksByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a REST hook.
         */
        id: number;
    };
    query?: never;
    url: '/resthooks/{id}';
};

export type GetResthooksByIdResponses = {
    /**
     * OK.
     */
    200: RestHook;
};

export type GetResthooksByIdResponse = GetResthooksByIdResponses[keyof GetResthooksByIdResponses];

export type PutResthooksByIdData = {
    body?: UpdateRestHook2;
    path: {
        /**
         * Unique identifier for a REST hook.
         */
        id: number;
    };
    query?: never;
    url: '/resthooks/{id}';
};

export type PutResthooksByIdResponses = {
    /**
     * OK.
     */
    200: RestHook;
};

export type PutResthooksByIdResponse = PutResthooksByIdResponses[keyof PutResthooksByIdResponses];
