// This file is auto-generated by @hey-api/openapi-ts

export const PagedActionTypeParticipantTypesSchema = {
    type: 'object',
    properties: {
        actiontypeparticipanttypes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionTypeParticipantType'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        actiontypeparticipanttypes: {
            '$ref': '#/components/schemas/ActionTypeParticipantTypesPageData'
        }
    }
} as const;

export const ActionTypeParticipantTypesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of matter type participant type records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of matter type participant type records.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of matter type participant type records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actiontypeparticipanttypes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of matter type participant type records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actiontypeparticipanttypes?page=3'
        }
    }
} as const;

export const ActionTypeParticipantTypeSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for a single record. The identifier is composed from the matter type identifier and the participant type identifier separated by "--".',
            type: 'string',
            format: 'string',
            example: '14--54',
            readOnly: true
        },
        required: {
            description: 'A flag to indicate if a participant of the specified participant type is required for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        isPrimaryParticipantType: {
            description: 'A flag to indicate if a participant of the specified participant type is the primary participant type for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        actionType: {
            description: 'The matter type for which participant types are being managed.',
            example: 14,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/ActionTypeParticipantTypeLinks'
        }
    }
} as const;

export const ActionTypeParticipantTypeLinksSchema = {
    type: 'object',
    properties: {
        participantType: {
            description: 'Unique identifier for the participant type for this record.',
            example: 546,
            type: 'integer',
            readOnly: true
        }
    }
} as const;

export const CreateActionTypeParticipantTypeSchema = {
    type: 'object',
    properties: {
        required: {
            description: 'A flag to indicate if a participant of the specified participant type is required for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        isPrimaryParticipantType: {
            description: 'A flag to indicate if a participant of the specified participant type is the primary participant type for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        actionType: {
            description: 'The matter type for which participant types are being managed.',
            example: 14,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/CreateActionTypeParticipantTypeLinks'
        }
    }
} as const;

export const CreateActionTypeParticipantTypeLinksSchema = {
    type: 'object',
    required: ['participantType'],
    properties: {
        participantType: {
            description: 'Unique identifier for the participant type for this record.',
            example: 546,
            type: 'integer'
        }
    }
} as const;

export const UpdateActionTypeParticipantTypeSchema = {
    type: 'object',
    properties: {
        required: {
            description: 'A flag to indicate if a participant of the specified participant type is required for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        isPrimaryParticipantType: {
            description: 'A flag to indicate if a participant of the specified participant type is the primary participant type for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        }
    }
} as const;

export const PagedActionTypeParticipantTypesWritableSchema = {
    type: 'object',
    properties: {
        actiontypeparticipanttypes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionTypeParticipantTypeWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ActionTypeParticipantTypeWritableSchema = {
    type: 'object',
    properties: {
        required: {
            description: 'A flag to indicate if a participant of the specified participant type is required for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        isPrimaryParticipantType: {
            description: 'A flag to indicate if a participant of the specified participant type is the primary participant type for a matter of the specified matter type. Value is either T for true, or F for false.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        actionType: {
            description: 'The matter type for which participant types are being managed.',
            example: 14,
            type: 'integer'
        }
    }
} as const;
