// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteActiontypeparticipanttypesByIdData, DeleteActiontypeparticipanttypesByIdResponses, GetActiontypeparticipanttypesByIdData, GetActiontypeparticipanttypesByIdResponses, GetActiontypeparticipanttypesData, GetActiontypeparticipanttypesResponses, PostActiontypeparticipanttypesData, PostActiontypeparticipanttypesResponses, PutActiontypeparticipanttypesByIdData, PutActiontypeparticipanttypesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all participant types for all matter types.
 */
export const getActiontypeparticipanttypes = <ThrowOnError extends boolean = false>(options?: Options<GetActiontypeparticipanttypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetActiontypeparticipanttypesResponses, unknown, ThrowOnError>({
        url: '/actiontypeparticipanttypes',
        ...options
    });
};

/**
 * Add an existing participant type to an existing matter type.
 */
export const postActiontypeparticipanttypes = <ThrowOnError extends boolean = false>(options?: Options<PostActiontypeparticipanttypesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostActiontypeparticipanttypesResponses, unknown, ThrowOnError>({
        url: '/actiontypeparticipanttypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single matter type participant type record.
 */
export const deleteActiontypeparticipanttypesById = <ThrowOnError extends boolean = false>(options: Options<DeleteActiontypeparticipanttypesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteActiontypeparticipanttypesByIdResponses, unknown, ThrowOnError>({
        url: '/actiontypeparticipanttypes/{id}',
        ...options
    });
};

/**
 * Returns a single matter type participant type record.
 */
export const getActiontypeparticipanttypesById = <ThrowOnError extends boolean = false>(options: Options<GetActiontypeparticipanttypesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetActiontypeparticipanttypesByIdResponses, unknown, ThrowOnError>({
        url: '/actiontypeparticipanttypes/{id}',
        ...options
    });
};

/**
 * Updates a single matter type participant type record.
 */
export const putActiontypeparticipanttypesById = <ThrowOnError extends boolean = false>(options: Options<PutActiontypeparticipanttypesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutActiontypeparticipanttypesByIdResponses, unknown, ThrowOnError>({
        url: '/actiontypeparticipanttypes/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
