// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetActionsByIdData, GetActionsByIdResponses, GetActionsData, GetActionsResponses, PatchActionsByIdData, PatchActionsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of Matters. For information on how to construct requests filtering by various properties on a Matter please refer to the API Developer Portal.
 */
export const getActions = <ThrowOnError extends boolean = false>(options?: Options<GetActionsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetActionsResponses, unknown, ThrowOnError>({
        url: '/actions',
        ...options
    });
};

/**
 * Returns a single Matter.
 */
export const getActionsById = <ThrowOnError extends boolean = false>(options: Options<GetActionsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetActionsByIdResponses, unknown, ThrowOnError>({
        url: '/actions/{id}',
        ...options
    });
};

/**
 * Update the properties of a Matter.
 */
export const patchActionsById = <ThrowOnError extends boolean = false>(options: Options<PatchActionsByIdData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchActionsByIdResponses, unknown, ThrowOnError>({
        url: '/actions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
