// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedActions = {
    actions?: Array<Action>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    actions?: ActionPageData;
};

export type ActionPageData = {
    /**
     * The total number of Matters returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Matters.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Matters.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Matters.
     */
    nextPage?: string;
};

export type Action = {
    /**
     * Unique identifier for the Matter.
     */
    id?: number;
    /**
     * Name of the Matter.
     */
    name?: string;
    /**
     * Matter reference.
     */
    reference?: string;
    /**
     * Matter priority.
     */
    priority?: number;
    /**
     * Matter status.
     */
    status?: 'Active' | 'Inactive' | 'Template' | 'Closed';
    /**
     * Timestamp when the status was last updated.
     */
    statusTimestamp?: string;
    /**
     * Flag to indicate if the Matter billing can be overridden, True (T) or False (F).
     */
    isBillableOverride?: string;
    /**
     * Timestamp when the Matter was created.
     */
    createdTimestamp?: string;
    /**
     * Timestamp when the Matter was last modified.
     */
    modifiedTimestamp?: string;
    /**
     * Flag to indicate if the Matter is deleted, True (T) or False (F).
     */
    isDeleted?: string;
    /**
     * The Actionstep User who deleted the Matter.
     */
    deletedBy?: string;
    /**
     * Timestamp when the Matter was deleted.
     */
    deletedTimestamp?: string;
    /**
     * Flag to indicate if the Matter has been marked as a favourite, True (T) or False (F).
     */
    isFavorite?: string;
    /**
     * Billing status if Matter billing has been overridden.
     */
    overrideBillingStatus?: 'Active' | 'Closed';
    /**
     * Timestamp when the Matter was last accessed.
     */
    lastAccessTimestamp?: string;
    /**
     * Reference data typically used when importing data from an external source.
     */
    importExternalReference?: string;
    /**
     * Anti-Money Laundering (AML) review status.
     */
    amlReviewStatus?: 'Not required' | 'Not started' | 'In progress' | 'Complete' | 'Delayed' | 'None';
    /**
     * An information message displayed as a banner on Matter and Time Keeping screens.
     */
    bannerText?: string;
    links?: ActionsLinks;
};

export type ActionsLinks = {
    /**
     * Unique identifier of the user to whom the Matter is assigned.
     */
    assignedTo?: number;
    /**
     * Unique identifier of the division owning the Matter.
     */
    division?: number;
    /**
     * Unique identifier of the Matter type.
     */
    actionType?: number;
    /**
     * Unique identifiers of the primary participants to the Matter.
     */
    primaryParticipants?: number;
    /**
     * Unique identifier of the current workflow step applicable to the Matter.
     */
    step?: string;
    /**
     * Unique identifier of the bill settings applicable to the Matter.
     */
    billSettings?: number;
    /**
     * Unique identifiers for any related Matters.
     */
    relatedActions?: number;
};

export type UpdateAction = {
    /**
     * Name of the Matter.
     */
    name?: string;
    /**
     * Matter reference.
     */
    reference?: string;
    /**
     * Matter priority.
     */
    priority?: number;
    /**
     * Matter status.
     */
    status?: 'Active' | 'Inactive' | 'Template' | 'Closed';
    /**
     * Is override billable, True (T) or False (F).
     */
    isBillableOverride?: string;
    /**
     * Override the billing status.
     */
    overrideBillingStatus?: 'Active' | 'Closed';
    /**
     * Reference data typically used when importing data from an external source.
     */
    importExternalReference?: string;
    /**
     * Anti-Money Laundering (AML) review status.
     */
    amlReviewStatus?: 'Not required' | 'Not started' | 'In progress' | 'Complete' | 'Delayed' | 'None';
    /**
     * An information message displayed as a banner on Matter and Time Keeping screens.
     */
    bannerText?: string;
    links?: UpdateActionLinks;
};

export type UpdateActionLinks = {
    /**
     * Unique identifier of the user to whom the Matter is assigned.
     */
    assignedTo?: number;
    /**
     * Unique identifier of the division owning the Matter.
     */
    division?: number;
};

export type UpdateAction2 = UpdateAction;

export type GetActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actions';
};

export type GetActionsResponses = {
    /**
     * OK.
     */
    200: PagedActions;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type GetActionsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a Matter.
         */
        id: number;
    };
    query?: never;
    url: '/actions/{id}';
};

export type GetActionsByIdResponses = {
    /**
     * OK.
     */
    200: Action;
};

export type GetActionsByIdResponse = GetActionsByIdResponses[keyof GetActionsByIdResponses];

export type PatchActionsByIdData = {
    body?: UpdateAction2;
    path: {
        /**
         * Unique identifier for a Matter.
         */
        id: number;
    };
    query?: never;
    url: '/actions/{id}';
};

export type PatchActionsByIdResponses = {
    /**
     * OK.
     */
    200: Action;
};

export type PatchActionsByIdResponse = PatchActionsByIdResponses[keyof PatchActionsByIdResponses];
