// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedPrimaryLanguage = {
    primarylanguage?: Array<PrimaryLanguage>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    primarylanguage?: PrimaryLanguagePageData;
};

export type PrimaryLanguagePageData = {
    /**
     * The total number of primary languages returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of primary languages.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of primary languages.
     */
    prevPage?: string;
    /**
     * A URL to the next page of primary languages.
     */
    nextPage?: string;
};

export type PrimaryLanguage = {
    /**
     * Language name.
     */
    language?: string;
};

export type GetPrimarylanguageData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/primarylanguage';
};

export type GetPrimarylanguageResponses = {
    /**
     * OK.
     */
    200: PagedPrimaryLanguage;
};

export type GetPrimarylanguageResponse = GetPrimarylanguageResponses[keyof GetPrimarylanguageResponses];
