// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedActionTypes = {
    actions?: Array<ActionType>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    actions?: ActionTypePageData;
};

export type ActionTypePageData = {
    /**
     * The total number of Matter types returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Matter types.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Matter types.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Matter types.
     */
    nextPage?: string;
};

export type ActionType = {
    /**
     * Unique identifier for the Matter type.
     */
    id?: number;
    /**
     * Name of the Matter type.
     */
    name?: string;
    /**
     * Description for the Matter type.
     */
    description?: string;
    /**
     * For third-party Matter type templates this shows the copyright owner.
     */
    copyrightHolder?: string;
    /**
     * For third-party Matter type templates this shows the creator's contact name.
     */
    copyrightContact?: string;
    /**
     * For third-party Matter type templates this shows the creator's email address.
     */
    copyrightEmail?: string;
    /**
     * Flag to indicate if the Matter type will track actual time, True (T) or False (F).
     */
    trackActualTime?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type will track billable time, True (T) or False (F).
     */
    trackBillableTime?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can be used for marketing campaigns, True (T) or False (F).
     */
    isForMarketingCampaigns?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can be used for marketing events, True (T) or False (F).
     */
    isForMarketingEvents?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can be used by employees, True (T) or False (F).
     */
    isForEmployees?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can be used for CRM, True (T) or False (F).
     */
    isForCrm?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can be used for debt collection, True (T) or False (F).
     */
    isForDebtCollection?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type is disabled, True (T) or False (F).
     */
    isDisabled?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type is billable, True (T) or False (F).
     */
    isBillable?: 'T' | 'F';
    /**
     * Flag to indicate if the Matter type can display the default logo/image, True (T) or False (F).
     */
    enableActionImage?: string;
    /**
     * Default email subject when composing emails.
     */
    defaultEmailSubject?: string;
    /**
     * File name of the default logo/image for the Matter type.
     */
    logoFilename?: string;
    /**
     * Override file name containing a custom logo/image.
     */
    customLogoFilename?: string;
    /**
     * Folder name containing the custom logo/image.
     */
    customLogoDirectory?: string;
    /**
     * Size in bytes of the custom logo/image.
     */
    customLogoFilesize?: number;
    /**
     * Timestamp of when the custom logo/image was last modified.
     */
    customLogoModifiedTimestamp?: string;
    /**
     * Unique identifier for the Matter type template.
     */
    templateIdentifier?: string;
    /**
     * Flag to indicate if Matters created from the Matter type can closed with any open invoices, True (T) or False (F).
     */
    allowCloseWithOpenInvoice?: string;
    /**
     * Flag to indicate if inline customization of the Matter type is permitted, True (T) or False (F).
     */
    allowInlineCustomizing?: 'T' | 'F';
    /**
     * Flag to indicate if Matters can be created from the Matter type, True (T) or False (F).
     */
    canCreate?: 'T' | 'F';
    /**
     * Flag to indicate if the AML review status should be shown on Matters created from the Matter type, True (T) or False (F).
     */
    showAmlReviewStatus?: 'T' | 'F';
    links?: ActionTypeLinks;
};

export type ActionTypeLinks = {
    /**
     * Unique identifier of the primary participant type for the Matter type.
     */
    primaryParticipantType?: number;
};

export type GetActiontypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actiontypes';
};

export type GetActiontypesResponses = {
    /**
     * OK.
     */
    200: PagedActionTypes;
};

export type GetActiontypesResponse = GetActiontypesResponses[keyof GetActiontypesResponses];
