// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ActionDocumentAttributes = {
    name?: string;
    keywords?: string;
    summary?: string;
    file?: string;
    folder?: string;
    action?: string;
    [key: string]: unknown | string | undefined;
};

export type ActionDocumentCreatePayload = {
    data?: {
        type?: string;
        attributes?: ActionDocumentAttributes;
        [key: string]: unknown | string | ActionDocumentAttributes | undefined;
    };
    [key: string]: unknown | {
        type?: string;
        attributes?: ActionDocumentAttributes;
        [key: string]: unknown | string | ActionDocumentAttributes | undefined;
    } | undefined;
};

export type ActionDocumentUpdatePayload = {
    data?: {
        id?: string;
        type?: string;
        attributes?: ActionDocumentAttributes;
        [key: string]: unknown | string | ActionDocumentAttributes | undefined;
    };
    [key: string]: unknown | {
        id?: string;
        type?: string;
        attributes?: ActionDocumentAttributes;
        [key: string]: unknown | string | ActionDocumentAttributes | undefined;
    } | undefined;
};

export type ActionstepDocumentResponse = {
    data?: {
        [key: string]: unknown;
    };
    [key: string]: unknown | {
        [key: string]: unknown;
    } | undefined;
};

export type ActionstepListResponse = {
    data?: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | Array<{
        [key: string]: unknown;
    }> | undefined;
};

export type GetActiondocumentsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/actiondocuments';
};

export type GetActiondocumentsResponses = {
    /**
     * OK
     */
    200: ActionstepListResponse;
};

export type GetActiondocumentsResponse = GetActiondocumentsResponses[keyof GetActiondocumentsResponses];

export type PostActiondocumentsData = {
    body: ActionDocumentCreatePayload;
    path?: never;
    query?: never;
    url: '/actiondocuments';
};

export type PostActiondocumentsResponses = {
    /**
     * Created
     */
    201: ActionstepDocumentResponse;
};

export type PostActiondocumentsResponse = PostActiondocumentsResponses[keyof PostActiondocumentsResponses];

export type DeleteActiondocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actiondocuments/{id}';
};

export type DeleteActiondocumentsByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteActiondocumentsByIdResponse = DeleteActiondocumentsByIdResponses[keyof DeleteActiondocumentsByIdResponses];

export type GetActiondocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/actiondocuments/{id}';
};

export type GetActiondocumentsByIdResponses = {
    /**
     * OK
     */
    200: ActionstepDocumentResponse;
};

export type GetActiondocumentsByIdResponse = GetActiondocumentsByIdResponses[keyof GetActiondocumentsByIdResponses];

export type PutActiondocumentsByIdData = {
    body: ActionDocumentUpdatePayload;
    path: {
        id: string;
    };
    query?: never;
    url: '/actiondocuments/{id}';
};

export type PutActiondocumentsByIdResponses = {
    /**
     * Updated
     */
    200: ActionstepDocumentResponse;
};

export type PutActiondocumentsByIdResponse = PutActiondocumentsByIdResponses[keyof PutActiondocumentsByIdResponses];
