// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDisbursementsByIdData, DeleteDisbursementsByIdResponses, GetDisbursementsByIdData, GetDisbursementsByIdResponses, GetDisbursementsData, GetDisbursementsResponses, PostDisbursementsData, PostDisbursementsResponses, PutDisbursementsByIdData, PutDisbursementsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of disbursements. For information on how to construct requests filtering by various properties, please refer to the API Developer Portal.
 */
export const getDisbursements = <ThrowOnError extends boolean = false>(options?: Options<GetDisbursementsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDisbursementsResponses, unknown, ThrowOnError>({
        url: '/disbursements',
        ...options
    });
};

/**
 * Create a new disbursement.
 */
export const postDisbursements = <ThrowOnError extends boolean = false>(options?: Options<PostDisbursementsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDisbursementsResponses, unknown, ThrowOnError>({
        url: '/disbursements',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a disbursement.
 */
export const deleteDisbursementsById = <ThrowOnError extends boolean = false>(options: Options<DeleteDisbursementsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteDisbursementsByIdResponses, unknown, ThrowOnError>({
        url: '/disbursements/{id}',
        ...options
    });
};

/**
 * Returns a single disbursement.
 */
export const getDisbursementsById = <ThrowOnError extends boolean = false>(options: Options<GetDisbursementsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetDisbursementsByIdResponses, unknown, ThrowOnError>({
        url: '/disbursements/{id}',
        ...options
    });
};

/**
 * Updates a disbursement
 */
export const putDisbursementsById = <ThrowOnError extends boolean = false>(options: Options<PutDisbursementsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutDisbursementsByIdResponses, unknown, ThrowOnError>({
        url: '/disbursements/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
