// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteTimeentriesByIdData, DeleteTimeentriesByIdResponses, GetTimeentriesByIdData, GetTimeentriesByIdResponses, GetTimeentriesData, GetTimeentriesResponses, PostTimeentriesData, PostTimeentriesResponses, PutTimeentriesByIdData, PutTimeentriesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of time entries.
 */
export const getTimeentries = <ThrowOnError extends boolean = false>(options?: Options<GetTimeentriesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTimeentriesResponses, unknown, ThrowOnError>({
        url: '/timeentries',
        ...options
    });
};

/**
 * Create a new time entry.
 */
export const postTimeentries = <ThrowOnError extends boolean = false>(options?: Options<PostTimeentriesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostTimeentriesResponses, unknown, ThrowOnError>({
        url: '/timeentries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a time entry.
 */
export const deleteTimeentriesById = <ThrowOnError extends boolean = false>(options: Options<DeleteTimeentriesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTimeentriesByIdResponses, unknown, ThrowOnError>({
        url: '/timeentries/{id}',
        ...options
    });
};

/**
 * Returns a single time entry.
 */
export const getTimeentriesById = <ThrowOnError extends boolean = false>(options: Options<GetTimeentriesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTimeentriesByIdResponses, unknown, ThrowOnError>({
        url: '/timeentries/{id}',
        ...options
    });
};

/**
 * Update a time entry.
 */
export const putTimeentriesById = <ThrowOnError extends boolean = false>(options: Options<PutTimeentriesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutTimeentriesByIdResponses, unknown, ThrowOnError>({
        url: '/timeentries/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
