// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedTimeEntries = {
    timeentries?: Array<TimeEntry>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    timeentries?: TimeEntriesPageData;
};

export type TimeEntriesPageData = {
    /**
     * The total number of time entries returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of time entries.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of time entries.
     */
    prevPage?: string;
    /**
     * A URL to the next page of time entries.
     */
    nextPage?: string;
};

export type TimeEntry = {
    /**
     * Unique identifier for the time entry.
     */
    id?: number;
    /**
     * The date for the time entry.
     */
    timestampDate?: string;
    /**
     * Description for the time entry.
     */
    description?: string;
    /**
     * Number of hours spent on the time entry.
     */
    actualHours?: number;
    /**
     * Number of billable hours for the time entry.
     */
    billableHours?: number;
    /**
     * Date and time the time entry was created.
     */
    createdTimestamp?: string;
    /**
     * Time when work on the time entry started.
     */
    startTime?: string;
    /**
     * Status of the recording timer.
     */
    timerStatus?: 'Running' | 'Paused' | 'Stopped' | 'Locked';
    /**
     * Time stamp when the client timer was started.
     */
    timerStartedClientTimestamp?: string;
    /**
     * Duration of the timer measured in seconds.
     */
    timerDurationSeconds?: number;
    /**
     * Billing behavior for the time entry.
     */
    billingBehavior?: 'Bill' | 'Hide' | 'No charge';
    /**
     * Unit price for each billable time unit (typically per hour).
     */
    rateUnitPrice?: number;
    /**
     * Source of the rate unit price.
     */
    rateSource?: 'Default' | 'Timekeeper' | 'Action' | 'Participant' | 'Custom' | 'Bulk custom rate';
    /**
     * Deprecated property.
     */
    rateTimestamp?: string;
    /**
     * How the billable amount is derived.
     */
    billableAmountType?: 'Fixed' | 'Calculated';
    /**
     * Billable amount for the time entry.
     */
    billableAmount?: number;
    /**
     * Indicates if the time entry is billable.
     */
    isBillable?: 'T' | 'F';
    /**
     * Used when importing data into Actionstep from a third-party data source.
     */
    importExternalReference?: string;
    links?: TimeEntryLinks;
};

export type TimeEntryLinks = {
    /**
     * Unique identifier for the task to which the time entry is associated.
     */
    task?: number;
    /**
     * Unique identifier to the quick code for the time entry.
     */
    quickCode?: number;
    /**
     * Actionstep user who created the time entry.
     */
    createdBy?: number;
    /**
     * Actionstep user who owns and is responsible for this time entry.
     */
    owner?: number;
    /**
     * Unique identifier of the matter to which the time entry is associated.
     */
    action?: number;
    /**
     * Unique identifier of the rate table entry applicable to the time entry.
     */
    rate?: number;
    /**
     * UTBMS activity code for the time entry.
     */
    utbmsActivityCode?: string;
    /**
     * UTBMS task code for the time entry.
     */
    utbmsTaskCode?: string;
    /**
     * UTBMS code for the timekeeper associated with the time entry.
     */
    utbmsTimekeeperCode?: string;
    /**
     * Phone record associated with the time entry.
     */
    phoneRecord?: number;
};

export type CreateTimeEntry = {
    /**
     * The date for the time entry.
     */
    timestampDate: string;
    /**
     * Description for the time entry.
     */
    description?: string;
    /**
     * Number of hours spent on the time entry.
     */
    actualHours: number;
    /**
     * Number of billable hours for the time entry.
     */
    billableHours?: number;
    /**
     * Date and time the time entry was created.
     */
    createdTimestamp?: string;
    /**
     * Time when work on the time entry started.
     */
    startTime?: string;
    /**
     * Status of the recording timer.
     */
    timerStatus?: 'Running' | 'Paused' | 'Stopped' | 'Locked';
    /**
     * Time stamp when the client timer was started.
     */
    timerStartedClientTimestamp?: string;
    /**
     * Duration of the timer measured in seconds.
     */
    timerDurationSeconds?: number;
    /**
     * Billing behavior for the time entry.
     */
    billingBehavior?: 'Bill' | 'Hide' | 'No charge';
    /**
     * Unit price for each billable time unit (typically per hour).
     */
    rateUnitPrice?: number;
    /**
     * Source of the rate unit price.
     */
    rateSource?: 'Default' | 'Timekeeper' | 'Action' | 'Participant' | 'Custom' | 'Bulk custom rate';
    /**
     * Deprecated property.
     */
    rateTimestamp?: string;
    /**
     * How the billable amount is derived.
     */
    billableAmountType?: 'Fixed' | 'Calculated';
    /**
     * Billable amount for the time entry.
     */
    billableAmount?: number;
    /**
     * Indicates if the time entry is billable.
     */
    isBillable?: 'T' | 'F';
    /**
     * Used when importing data into Actionstep from a third-party data source.
     */
    importExternalReference?: string;
    links?: CreateTimeEntryLinks;
};

export type CreateTimeEntryLinks = {
    /**
     * Unique identifier for the task to which the time entry is associated.
     */
    task?: number;
    /**
     * Unique identifier to the quick code for the time entry.
     */
    quickCode?: number;
    /**
     * Actionstep user who created the time entry.
     */
    createdBy?: number;
    /**
     * Actionstep user who owns and is responsible for this time entry.
     */
    owner?: number;
    /**
     * Unique identifier of the matter to which the time entry is associated.
     */
    action?: number;
    /**
     * Unique identifier of the rate table entry applicable to the time entry.
     */
    rate?: number;
    /**
     * UTBMS activity code for the time entry.
     */
    utbmsActivityCode?: string;
    /**
     * UTBMS task code for the time entry.
     */
    utbmsTaskCode?: string;
    /**
     * UTBMS code for the timekeeper associated with the time entry.
     */
    utbmsTimekeeperCode?: string;
    /**
     * Phone record associated with the time entry.
     */
    phoneRecord?: number;
};

export type UpdateTimeEntry = {
    /**
     * The date for the time entry.
     */
    timestampDate: string;
    /**
     * Description for the time entry.
     */
    description?: string;
    /**
     * Number of hours spent on the time entry.
     */
    actualHours: number;
    /**
     * Number of billable hours for the time entry.
     */
    billableHours?: number;
    /**
     * Date and time the time entry was created.
     */
    createdTimestamp?: string;
    /**
     * Time when work on the time entry started.
     */
    startTime?: string;
    /**
     * Status of the recording timer.
     */
    timerStatus?: 'Running' | 'Paused' | 'Stopped' | 'Locked';
    /**
     * Time stamp when the client timer was started.
     */
    timerStartedClientTimestamp?: string;
    /**
     * Duration of the timer measured in seconds.
     */
    timerDurationSeconds?: number;
    /**
     * Billing behavior for the time entry.
     */
    billingBehavior?: 'Bill' | 'Hide' | 'No charge';
    /**
     * Unit price for each billable time unit (typically per hour).
     */
    rateUnitPrice?: number;
    /**
     * Source of the rate unit price.
     */
    rateSource?: 'Default' | 'Timekeeper' | 'Action' | 'Participant' | 'Custom' | 'Bulk custom rate';
    /**
     * Deprecated property.
     */
    rateTimestamp?: string;
    /**
     * How the billable amount is derived.
     */
    billableAmountType?: 'Fixed' | 'Calculated';
    /**
     * Billable amount for the time entry.
     */
    billableAmount?: number;
    /**
     * Indicates if the time entry is billable.
     */
    isBillable?: 'T' | 'F';
    /**
     * Used when importing data into Actionstep from a third-party data source.
     */
    importExternalReference?: string;
    links?: UpdateTimeEntryLinks;
};

export type UpdateTimeEntryLinks = {
    /**
     * Unique identifier for the task to which the time entry is associated.
     */
    task?: number;
    /**
     * Unique identifier to the quick code for the time entry.
     */
    quickCode?: number;
    /**
     * Actionstep user who created the time entry.
     */
    createdBy?: number;
    /**
     * Actionstep user who owns and is responsible for this time entry.
     */
    owner?: number;
    /**
     * Unique identifier of the matter to which the time entry is associated.
     */
    action?: number;
    /**
     * Unique identifier of the rate table entry applicable to the time entry.
     */
    rate?: number;
    /**
     * UTBMS activity code for the time entry.
     */
    utbmsActivityCode?: string;
    /**
     * UTBMS task code for the time entry.
     */
    utbmsTaskCode?: string;
    /**
     * UTBMS code for the timekeeper associated with the time entry.
     */
    utbmsTimekeeperCode?: string;
    /**
     * Phone record associated with the time entry.
     */
    phoneRecord?: number;
};

export type CreateTimeEntry2 = CreateTimeEntry;

export type UpdateTimeEntry2 = UpdateTimeEntry;

export type GetTimeentriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/timeentries';
};

export type GetTimeentriesResponses = {
    /**
     * OK.
     */
    200: PagedTimeEntries;
};

export type GetTimeentriesResponse = GetTimeentriesResponses[keyof GetTimeentriesResponses];

export type PostTimeentriesData = {
    body?: CreateTimeEntry2;
    path?: never;
    query?: never;
    url: '/timeentries';
};

export type PostTimeentriesResponses = {
    /**
     * OK.
     */
    200: TimeEntry;
};

export type PostTimeentriesResponse = PostTimeentriesResponses[keyof PostTimeentriesResponses];

export type DeleteTimeentriesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a time entry.
         */
        id: number;
    };
    query?: never;
    url: '/timeentries/{id}';
};

export type DeleteTimeentriesByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteTimeentriesByIdResponse = DeleteTimeentriesByIdResponses[keyof DeleteTimeentriesByIdResponses];

export type GetTimeentriesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a time entry.
         */
        id: number;
    };
    query?: never;
    url: '/timeentries/{id}';
};

export type GetTimeentriesByIdResponses = {
    /**
     * OK.
     */
    200: TimeEntry;
};

export type GetTimeentriesByIdResponse = GetTimeentriesByIdResponses[keyof GetTimeentriesByIdResponses];

export type PutTimeentriesByIdData = {
    body?: UpdateTimeEntry2;
    path: {
        /**
         * Unique identifier for a time entry.
         */
        id: number;
    };
    query?: never;
    url: '/timeentries/{id}';
};

export type PutTimeentriesByIdResponses = {
    /**
     * OK.
     */
    200: TimeEntry;
};

export type PutTimeentriesByIdResponse = PutTimeentriesByIdResponses[keyof PutTimeentriesByIdResponses];
