// This file is auto-generated by @hey-api/openapi-ts

export const PagedActionNetdocumentsSettingsSchema = {
    type: 'object',
    properties: {
        actionnetdocssettings: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionNetDocumentsSettings'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        actionnetdocssettings: {
            '$ref': '#/components/schemas/ActionNetDocumentsSettingsPageData'
        }
    }
} as const;

export const ActionNetDocumentsSettingsPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of NetDocuments settings records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of NetDocuments settings records.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of NetDocuments settings records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actionnetdocssettings?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of NetDocuments settings records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actionnetdocssettings?page=3'
        }
    }
} as const;

export const ActionNetDocumentsSettingsSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for a single NetDocuments settings record.',
            type: 'integer',
            format: 'integer',
            example: 586,
            readOnly: true
        },
        workspaceIdentifier: {
            description: 'Workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 1005499
        },
        parentWorkspaceIdentifier: {
            description: 'Parent workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 799294
        },
        workspaceEnvId: {
            description: 'The workspace environment identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 'Q14:b:i:d:v:^W250512223611824.nev'
        },
        workspaceFolderJson: {
            description: 'A JSON formatted string containing folder configuration details for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: [
                {
                    '\"id\":1': null,
                    '\"name\":\"Client Invoices\"': null,
                    '\"envId\":\"Q23:a:2:7:2:^F250512223615873.nev\"': null,
                    '\"folderId\":\"4898-5237-5619\"': null,
                    '\"pid\":null': null
                }
            ]
        },
        workspaceFolderLastUpdatedTimestamp: {
            description: 'Timestamp for the last update of this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            readOnly: true,
            example: '2025-05-13T14:36:33+12:00'
        },
        links: {
            '$ref': '#/components/schemas/ActionNetDocumentsSettingsLinks'
        }
    }
} as const;

export const ActionNetDocumentsSettingsLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier for the matter to which these NetDocuments settings are applied.',
            example: 8263,
            type: 'string',
            readOnly: true
        },
        participant: {
            description: 'Unique identifier for a participant to which these NetDocuments settings are applied.',
            example: 321845,
            type: 'integer',
            readOnly: true
        }
    }
} as const;

export const CreateActionNetDocumentsSettingsSchema = {
    type: 'object',
    properties: {
        workspaceIdentifier: {
            description: 'Workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 1005499
        },
        parentWorkspaceIdentifier: {
            description: 'Parent workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 799294
        },
        workspaceEnvId: {
            description: 'The workspace environment identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 'Q14:b:i:d:v:^W250512223611824.nev'
        },
        workspaceFolderJson: {
            description: 'A JSON formatted string containing folder configuration details for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: [
                {
                    '\"id\":1': null,
                    '\"name\":\"Client Invoices\"': null,
                    '\"envId\":\"Q23:a:2:7:2:^F250512223615873.nev\"': null,
                    '\"folderId\":\"4898-5237-5619\"': null,
                    '\"pid\":null': null
                }
            ]
        },
        links: {
            '$ref': '#/components/schemas/CreateActionNetDocumentsSettingsLinks'
        }
    }
} as const;

export const CreateActionNetDocumentsSettingsLinksSchema = {
    type: 'object',
    required: ['action'],
    properties: {
        action: {
            description: 'Unique identifier for the matter to which these NetDocuments settings are applied.',
            example: 8263,
            type: 'string',
            readOnly: true
        },
        participant: {
            description: 'Unique identifier for a participant to which these NetDocuments settings are applied.',
            example: 321845,
            type: 'integer',
            readOnly: true
        }
    }
} as const;

export const UpdateActionNetDocumentsSettingsSchema = {
    type: 'object',
    properties: {
        workspaceIdentifier: {
            description: 'Workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 1005499
        },
        parentWorkspaceIdentifier: {
            description: 'Parent workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 799294
        },
        workspaceEnvId: {
            description: 'The workspace environment identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 'Q14:b:i:d:v:^W250512223611824.nev'
        },
        workspaceFolderJson: {
            description: 'A JSON formatted string containing folder configuration details for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: [
                {
                    '\"id\":1': null,
                    '\"name\":\"Client Invoices\"': null,
                    '\"envId\":\"Q23:a:2:7:2:^F250512223615873.nev\"': null,
                    '\"folderId\":\"4898-5237-5619\"': null,
                    '\"pid\":null': null
                }
            ]
        },
        links: {
            '$ref': '#/components/schemas/UpdateActionNetDocumentsSettingsLinks'
        }
    }
} as const;

export const UpdateActionNetDocumentsSettingsLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier for the matter to which these NetDocuments settings are applied.',
            example: 8263,
            type: 'string'
        },
        participant: {
            description: 'Unique identifier for a participant to which these NetDocuments settings are applied.',
            example: 321845,
            type: 'integer'
        }
    }
} as const;

export const PagedActionNetdocumentsSettingsWritableSchema = {
    type: 'object',
    properties: {
        actionnetdocssettings: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionNetDocumentsSettingsWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ActionNetDocumentsSettingsWritableSchema = {
    type: 'object',
    properties: {
        workspaceIdentifier: {
            description: 'Workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 1005499
        },
        parentWorkspaceIdentifier: {
            description: 'Parent workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 799294
        },
        workspaceEnvId: {
            description: 'The workspace environment identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 'Q14:b:i:d:v:^W250512223611824.nev'
        },
        workspaceFolderJson: {
            description: 'A JSON formatted string containing folder configuration details for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: [
                {
                    '\"id\":1': null,
                    '\"name\":\"Client Invoices\"': null,
                    '\"envId\":\"Q23:a:2:7:2:^F250512223615873.nev\"': null,
                    '\"folderId\":\"4898-5237-5619\"': null,
                    '\"pid\":null': null
                }
            ]
        }
    }
} as const;

export const CreateActionNetDocumentsSettingsWritableSchema = {
    type: 'object',
    properties: {
        workspaceIdentifier: {
            description: 'Workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 1005499
        },
        parentWorkspaceIdentifier: {
            description: 'Parent workspace identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 799294
        },
        workspaceEnvId: {
            description: 'The workspace environment identifier for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: 'Q14:b:i:d:v:^W250512223611824.nev'
        },
        workspaceFolderJson: {
            description: 'A JSON formatted string containing folder configuration details for this NetDocuments settings record.',
            type: 'string',
            format: 'string',
            example: [
                {
                    '\"id\":1': null,
                    '\"name\":\"Client Invoices\"': null,
                    '\"envId\":\"Q23:a:2:7:2:^F250512223615873.nev\"': null,
                    '\"folderId\":\"4898-5237-5619\"': null,
                    '\"pid\":null': null
                }
            ]
        }
    }
} as const;
