// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteActionnetdocssettingsByIdData, DeleteActionnetdocssettingsByIdResponses, GetActionnetdocssettingsByIdData, GetActionnetdocssettingsByIdResponses, GetActionnetdocssettingsData, GetActionnetdocssettingsResponses, PostActionnetdocssettingsData, PostActionnetdocssettingsResponses, PutActionnetdocssettingsByIdData, PutActionnetdocssettingsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of NetDocuments Settings for all matters.
 */
export const getActionnetdocssettings = <ThrowOnError extends boolean = false>(options?: Options<GetActionnetdocssettingsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetActionnetdocssettingsResponses, unknown, ThrowOnError>({
        url: '/actionnetdocssettings',
        ...options
    });
};

/**
 * Create a new NetDocuments settings record.
 */
export const postActionnetdocssettings = <ThrowOnError extends boolean = false>(options?: Options<PostActionnetdocssettingsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostActionnetdocssettingsResponses, unknown, ThrowOnError>({
        url: '/actionnetdocssettings',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single NetDocuments settings record.
 */
export const deleteActionnetdocssettingsById = <ThrowOnError extends boolean = false>(options: Options<DeleteActionnetdocssettingsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteActionnetdocssettingsByIdResponses, unknown, ThrowOnError>({
        url: '/actionnetdocssettings/{id}',
        ...options
    });
};

/**
 * Returns a single NetDocuments settings record.
 */
export const getActionnetdocssettingsById = <ThrowOnError extends boolean = false>(options: Options<GetActionnetdocssettingsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetActionnetdocssettingsByIdResponses, unknown, ThrowOnError>({
        url: '/actionnetdocssettings/{id}',
        ...options
    });
};

/**
 * Updates a single NetDocuments settings record.
 */
export const putActionnetdocssettingsById = <ThrowOnError extends boolean = false>(options: Options<PutActionnetdocssettingsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutActionnetdocssettingsByIdResponses, unknown, ThrowOnError>({
        url: '/actionnetdocssettings/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
