// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedActionNetdocumentsSettings = {
    actionnetdocssettings?: Array<ActionNetDocumentsSettings>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    actionnetdocssettings?: ActionNetDocumentsSettingsPageData;
};

export type ActionNetDocumentsSettingsPageData = {
    /**
     * The total number of NetDocuments settings records returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of NetDocuments settings records.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of NetDocuments settings records.
     */
    prevPage?: string;
    /**
     * A URL to the next page of NetDocuments settings records.
     */
    nextPage?: string;
};

export type ActionNetDocumentsSettings = {
    /**
     * Unique identifier for a single NetDocuments settings record.
     */
    readonly id?: number;
    /**
     * Workspace identifier for this NetDocuments settings record.
     */
    workspaceIdentifier?: string;
    /**
     * Parent workspace identifier for this NetDocuments settings record.
     */
    parentWorkspaceIdentifier?: string;
    /**
     * The workspace environment identifier for this NetDocuments settings record.
     */
    workspaceEnvId?: string;
    /**
     * A JSON formatted string containing folder configuration details for this NetDocuments settings record.
     */
    workspaceFolderJson?: string;
    /**
     * Timestamp for the last update of this NetDocuments settings record.
     */
    readonly workspaceFolderLastUpdatedTimestamp?: string;
    links?: ActionNetDocumentsSettingsLinks;
};

export type ActionNetDocumentsSettingsLinks = {
    /**
     * Unique identifier for the matter to which these NetDocuments settings are applied.
     */
    readonly action?: string;
    /**
     * Unique identifier for a participant to which these NetDocuments settings are applied.
     */
    readonly participant?: number;
};

export type CreateActionNetDocumentsSettings = {
    /**
     * Workspace identifier for this NetDocuments settings record.
     */
    workspaceIdentifier?: string;
    /**
     * Parent workspace identifier for this NetDocuments settings record.
     */
    parentWorkspaceIdentifier?: string;
    /**
     * The workspace environment identifier for this NetDocuments settings record.
     */
    workspaceEnvId?: string;
    /**
     * A JSON formatted string containing folder configuration details for this NetDocuments settings record.
     */
    workspaceFolderJson?: string;
    links?: CreateActionNetDocumentsSettingsLinks;
};

export type CreateActionNetDocumentsSettingsLinks = {
    /**
     * Unique identifier for the matter to which these NetDocuments settings are applied.
     */
    readonly action: string;
    /**
     * Unique identifier for a participant to which these NetDocuments settings are applied.
     */
    readonly participant?: number;
};

export type UpdateActionNetDocumentsSettings = {
    /**
     * Workspace identifier for this NetDocuments settings record.
     */
    workspaceIdentifier?: string;
    /**
     * Parent workspace identifier for this NetDocuments settings record.
     */
    parentWorkspaceIdentifier?: string;
    /**
     * The workspace environment identifier for this NetDocuments settings record.
     */
    workspaceEnvId?: string;
    /**
     * A JSON formatted string containing folder configuration details for this NetDocuments settings record.
     */
    workspaceFolderJson?: string;
    links?: UpdateActionNetDocumentsSettingsLinks;
};

export type UpdateActionNetDocumentsSettingsLinks = {
    /**
     * Unique identifier for the matter to which these NetDocuments settings are applied.
     */
    action?: string;
    /**
     * Unique identifier for a participant to which these NetDocuments settings are applied.
     */
    participant?: number;
};

export type PagedActionNetdocumentsSettingsWritable = {
    actionnetdocssettings?: Array<ActionNetDocumentsSettingsWritable>;
    meta?: PageMetaData;
};

export type ActionNetDocumentsSettingsWritable = {
    /**
     * Workspace identifier for this NetDocuments settings record.
     */
    workspaceIdentifier?: string;
    /**
     * Parent workspace identifier for this NetDocuments settings record.
     */
    parentWorkspaceIdentifier?: string;
    /**
     * The workspace environment identifier for this NetDocuments settings record.
     */
    workspaceEnvId?: string;
    /**
     * A JSON formatted string containing folder configuration details for this NetDocuments settings record.
     */
    workspaceFolderJson?: string;
};

export type CreateActionNetDocumentsSettingsWritable = {
    /**
     * Workspace identifier for this NetDocuments settings record.
     */
    workspaceIdentifier?: string;
    /**
     * Parent workspace identifier for this NetDocuments settings record.
     */
    parentWorkspaceIdentifier?: string;
    /**
     * The workspace environment identifier for this NetDocuments settings record.
     */
    workspaceEnvId?: string;
    /**
     * A JSON formatted string containing folder configuration details for this NetDocuments settings record.
     */
    workspaceFolderJson?: string;
};

export type CreateActionNetDocumentsSettings2 = CreateActionNetDocumentsSettingsWritable;

export type UpdateActionNetDocumentsSettings2 = UpdateActionNetDocumentsSettings;

export type GetActionnetdocssettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actionnetdocssettings';
};

export type GetActionnetdocssettingsResponses = {
    /**
     * OK.
     */
    200: PagedActionNetdocumentsSettings;
};

export type GetActionnetdocssettingsResponse = GetActionnetdocssettingsResponses[keyof GetActionnetdocssettingsResponses];

export type PostActionnetdocssettingsData = {
    body?: CreateActionNetDocumentsSettings2;
    path?: never;
    query?: never;
    url: '/actionnetdocssettings';
};

export type PostActionnetdocssettingsResponses = {
    /**
     * OK.
     */
    200: ActionNetDocumentsSettings;
};

export type PostActionnetdocssettingsResponse = PostActionnetdocssettingsResponses[keyof PostActionnetdocssettingsResponses];

export type DeleteActionnetdocssettingsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single NetDocuments settings record.
         */
        id: number;
    };
    query?: never;
    url: '/actionnetdocssettings/{id}';
};

export type DeleteActionnetdocssettingsByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteActionnetdocssettingsByIdResponse = DeleteActionnetdocssettingsByIdResponses[keyof DeleteActionnetdocssettingsByIdResponses];

export type GetActionnetdocssettingsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single NetDocuments settings record.
         */
        id: number;
    };
    query?: never;
    url: '/actionnetdocssettings/{id}';
};

export type GetActionnetdocssettingsByIdResponses = {
    /**
     * OK.
     */
    200: ActionNetDocumentsSettings;
};

export type GetActionnetdocssettingsByIdResponse = GetActionnetdocssettingsByIdResponses[keyof GetActionnetdocssettingsByIdResponses];

export type PutActionnetdocssettingsByIdData = {
    body?: UpdateActionNetDocumentsSettings2;
    path: {
        /**
         * Unique identifier for a single NetDocuments settings record.
         */
        id: number;
    };
    query?: never;
    url: '/actionnetdocssettings/{id}';
};

export type PutActionnetdocssettingsByIdResponses = {
    /**
     * OK.
     */
    200: ActionNetDocumentsSettings;
};

export type PutActionnetdocssettingsByIdResponse = PutActionnetdocssettingsByIdResponses[keyof PutActionnetdocssettingsByIdResponses];
