// This file is auto-generated by @hey-api/openapi-ts

export const PagedDataCollectionRecordsSchema = {
    type: 'object',
    properties: {
        datacollectionrecords: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionRecord'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        datacollectionrecords: {
            '$ref': '#/components/schemas/DataCollectionRecordsPageData'
        }
    }
} as const;

export const DataCollectionRecordsPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of data collection records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of data collection records.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of data collection records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionrecords?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of data collection records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionrecords?page=3'
        }
    }
} as const;

export const DataCollectionRecordSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the data collection record.',
            example: 4910,
            type: 'integer',
            readOnly: true
        },
        canWrite: {
            description: 'Indicates if the data collection record can be written to.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string',
            readOnly: true
        },
        canDelete: {
            description: 'Indicates if the data collection record can be deleted.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string',
            readOnly: true
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionRecordLinks'
        }
    }
} as const;

export const DataCollectionRecordLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the data collection is associated.',
            example: 822,
            type: 'integer'
        },
        dataCollection: {
            description: 'Unique identifier of the data collection to which the data collection record is associated.',
            example: 50,
            type: 'integer'
        }
    }
} as const;

export const CreateDataCollectionRecordSchema = {
    type: 'object',
    properties: {
        canWrite: {
            description: 'Indicates if the data collection record can be written to.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        canDelete: {
            description: 'Indicates if the data collection record can be deleted.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/CreateDataCollectionRecordLinks'
        }
    }
} as const;

export const CreateDataCollectionRecordLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the data collection is associated.',
            example: 822,
            type: 'integer'
        },
        dataCollection: {
            description: 'Unique identifier of the data collection to which the data collection record is associated.',
            example: 50,
            type: 'integer'
        }
    }
} as const;

export const PagedDataCollectionRecordsWritableSchema = {
    type: 'object',
    properties: {
        datacollectionrecords: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionRecordWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const DataCollectionRecordWritableSchema = {
    type: 'object',
    properties: {
        links: {
            '$ref': '#/components/schemas/DataCollectionRecordLinks'
        }
    }
} as const;
