// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDatacollectionrecordsByIdData, DeleteDatacollectionrecordsByIdResponses, GetDatacollectionrecordsByIdData, GetDatacollectionrecordsByIdResponses, GetDatacollectionrecordsData, GetDatacollectionrecordsResponses, PostDatacollectionrecordsData, PostDatacollectionrecordsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of data collection records.
 */
export const getDatacollectionrecords = <ThrowOnError extends boolean = false>(options?: Options<GetDatacollectionrecordsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDatacollectionrecordsResponses, unknown, ThrowOnError>({
        url: '/datacollectionrecords',
        ...options
    });
};

/**
 * Create a new data collection record.
 */
export const postDatacollectionrecords = <ThrowOnError extends boolean = false>(options?: Options<PostDatacollectionrecordsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDatacollectionrecordsResponses, unknown, ThrowOnError>({
        url: '/datacollectionrecords',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a data collection record.
 */
export const deleteDatacollectionrecordsById = <ThrowOnError extends boolean = false>(options: Options<DeleteDatacollectionrecordsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteDatacollectionrecordsByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionrecords/{id}',
        ...options
    });
};

/**
 * Returns a single data collection record.
 */
export const getDatacollectionrecordsById = <ThrowOnError extends boolean = false>(options: Options<GetDatacollectionrecordsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetDatacollectionrecordsByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionrecords/{id}',
        ...options
    });
};
