// This file is auto-generated by @hey-api/openapi-ts

export const PagedCulturalIdentitySchema = {
    type: 'object',
    properties: {
        culturalidentity: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CulturalIdentity'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        culturalidentity: {
            '$ref': '#/components/schemas/CulturalIdentityPageData'
        }
    }
} as const;

export const CulturalIdentityPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of cultural identity values returned by the underlying query.',
            type: 'integer',
            example: 4
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of cultural identity values.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of cultural identity values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of cultural identity values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/culturalidentity?page=3'
        }
    }
} as const;

export const CulturalIdentitySchema = {
    type: 'object',
    properties: {
        identity: {
            description: 'Identity value.',
            example: 'Yes, Aboriginal',
            type: 'string',
            format: 'string'
        }
    }
} as const;
