// This file is auto-generated by @hey-api/openapi-ts

export const PagedActionBillSettingsSchema = {
    type: 'object',
    properties: {
        actionbillsettings: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionBillSettings'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        actionbillsettings: {
            '$ref': '#/components/schemas/ActionBillSettingsPageData'
        }
    }
} as const;

export const ActionBillSettingsPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of matter bill settings returned by the underlying query.',
            type: 'integer',
            example: 360
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of matter bill settings.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of matter bill settings.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actionbillsettings?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of matter bill settings.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/actionbillsettings?page=3'
        }
    }
} as const;

export const ActionBillSettingsSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the matter to which the bill settings are associated.',
            example: 5850,
            type: 'integer'
        },
        billType: {
            description: 'Indicates the billing arrangement being applied to the matter.',
            enum: ['Hourly', 'Fixed fee'],
            example: 'Hourly',
            type: 'string'
        },
        sendToEmailAddress: {
            description: 'The default email address to which finalized bills are sent for this matter.',
            example: 'john.smith@mybigcompany.com',
            type: 'string'
        },
        quotedAmountIncludes: {
            description: 'Indicates whether any quoted amount includes fees and/or costs (disbursements).',
            enum: ['Fees', 'Costs', 'Fees and costs'],
            example: 'Fees and costs',
            type: 'string'
        },
        quotedAmount: {
            description: 'A quoted amount for this matter.',
            example: 5750.75,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isBillable: {
            description: 'Flag to indicate if the matter is billable.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string',
            readOnly: true
        },
        isUtbmsEnabled: {
            description: 'Flag to indicate if UTBMS is enabled for this matter.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        utbmsTaskCategoryCode: {
            description: 'UTBMS task category code.',
            example: 'Activity Codes',
            type: 'string'
        },
        defaultTimeEntryBehavior: {
            description: 'Default behavior for time entries.',
            enum: ['Bill', 'Hide', 'No Charge'],
            example: 'Bill',
            type: 'string'
        },
        salesTaxAppliesTo: {
            description: 'Indicates what sales tax is applied to.',
            enum: ['Fees', 'Expenses', 'All'],
            example: 'Fees',
            type: 'string'
        },
        discountType: {
            description: 'The discount type applicable for the matter.',
            enum: ['Amount', 'Percentage', 'None'],
            example: 'Amount',
            type: 'string'
        },
        discountAmount: {
            description: 'The amount of any discount.',
            example: 550.5,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isSalesTaxEnabled: {
            description: 'Flag to indicate if sales tax is enabled for the matter.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/Links'
        }
    }
} as const;

export const LinksSchema = {
    type: 'object',
    properties: {
        defaultRate: {
            description: 'Unique identifier for the default rate applicable to this matter.',
            example: 3,
            type: 'integer'
        },
        currency: {
            description: 'ISO 3 character code for the default billing currency.',
            example: 'USD',
            type: 'string',
            readOnly: true
        },
        salesTaxRate: {
            description: 'Unique identifier for the sales tax rate applicable to the bill settings.',
            example: 3945,
            type: 'integer'
        }
    }
} as const;

export const UpdateLinksSchema = {
    type: 'object',
    properties: {
        defaultRate: {
            description: 'Unique identifier for the default rate applicable to this matter.',
            example: 3,
            type: 'integer'
        },
        salesTaxRate: {
            description: 'Unique identifier for the sales tax rate applicable to the bill settings.',
            example: 3945,
            type: 'integer'
        }
    }
} as const;

export const UpdateBillSettingsSchema = {
    type: 'object',
    properties: {
        billType: {
            description: 'Indicates the billing arrangement being applied to the matter.',
            enum: ['Hourly', 'Fixed fee'],
            example: 'Hourly',
            type: 'string'
        },
        sendToEmailAddress: {
            description: 'The default email address to which finalized bills are sent for this matter.',
            example: 'john.smith@mybigcompany.com',
            type: 'string'
        },
        quotedAmountIncludes: {
            description: 'Indicates whether any quoted amount includes fees and/or costs (disbursements).',
            enum: ['Fees', 'Costs', 'Fees and costs'],
            example: 'Fees and costs',
            type: 'string'
        },
        quotedAmount: {
            description: 'A quoted amount for this matter.',
            example: 5750.75,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isUtbmsEnabled: {
            description: 'Flag to indicate if UTBMS is enabled for this matter.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        utbmsTaskCategoryCode: {
            description: 'UTBMS task category code.',
            example: 'Activity Codes',
            type: 'string'
        },
        defaultTimeEntryBehavior: {
            description: 'Default behavior for time entries.',
            enum: ['Bill', 'Hide', 'No Charge'],
            example: 'Bill',
            type: 'string'
        },
        salesTaxAppliesTo: {
            description: 'Indicates what sales tax is applied to.',
            enum: ['Fees', 'Expenses', 'All'],
            example: 'Fees',
            type: 'string'
        },
        discountType: {
            description: 'The discount type applicable for the matter.',
            enum: ['Amount', 'Percentage', 'None'],
            example: 'Amount',
            type: 'string'
        },
        discountAmount: {
            description: 'The amount of any discount.',
            example: 550.5,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isSalesTaxEnabled: {
            description: 'Flag to indicate if sales tax is enabled for the matter.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/UpdateLinks'
        }
    }
} as const;

export const PagedActionBillSettingsWritableSchema = {
    type: 'object',
    properties: {
        actionbillsettings: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ActionBillSettingsWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ActionBillSettingsWritableSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the matter to which the bill settings are associated.',
            example: 5850,
            type: 'integer'
        },
        billType: {
            description: 'Indicates the billing arrangement being applied to the matter.',
            enum: ['Hourly', 'Fixed fee'],
            example: 'Hourly',
            type: 'string'
        },
        sendToEmailAddress: {
            description: 'The default email address to which finalized bills are sent for this matter.',
            example: 'john.smith@mybigcompany.com',
            type: 'string'
        },
        quotedAmountIncludes: {
            description: 'Indicates whether any quoted amount includes fees and/or costs (disbursements).',
            enum: ['Fees', 'Costs', 'Fees and costs'],
            example: 'Fees and costs',
            type: 'string'
        },
        quotedAmount: {
            description: 'A quoted amount for this matter.',
            example: 5750.75,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isUtbmsEnabled: {
            description: 'Flag to indicate if UTBMS is enabled for this matter.',
            enum: ['T', 'F'],
            example: 'F',
            type: 'string'
        },
        utbmsTaskCategoryCode: {
            description: 'UTBMS task category code.',
            example: 'Activity Codes',
            type: 'string'
        },
        defaultTimeEntryBehavior: {
            description: 'Default behavior for time entries.',
            enum: ['Bill', 'Hide', 'No Charge'],
            example: 'Bill',
            type: 'string'
        },
        salesTaxAppliesTo: {
            description: 'Indicates what sales tax is applied to.',
            enum: ['Fees', 'Expenses', 'All'],
            example: 'Fees',
            type: 'string'
        },
        discountType: {
            description: 'The discount type applicable for the matter.',
            enum: ['Amount', 'Percentage', 'None'],
            example: 'Amount',
            type: 'string'
        },
        discountAmount: {
            description: 'The amount of any discount.',
            example: 550.5,
            type: 'number',
            multipleOf: 0.01,
            format: 'money'
        },
        isSalesTaxEnabled: {
            description: 'Flag to indicate if sales tax is enabled for the matter.',
            enum: ['T', 'F'],
            example: 'T',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/LinksWritable'
        }
    }
} as const;

export const LinksWritableSchema = {
    type: 'object',
    properties: {
        defaultRate: {
            description: 'Unique identifier for the default rate applicable to this matter.',
            example: 3,
            type: 'integer'
        },
        salesTaxRate: {
            description: 'Unique identifier for the sales tax rate applicable to the bill settings.',
            example: 3945,
            type: 'integer'
        }
    }
} as const;
