// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedActionBillSettings = {
    actionbillsettings?: Array<ActionBillSettings>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    actionbillsettings?: ActionBillSettingsPageData;
};

export type ActionBillSettingsPageData = {
    /**
     * The total number of matter bill settings returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of matter bill settings.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of matter bill settings.
     */
    prevPage?: string;
    /**
     * A URL to the next page of matter bill settings.
     */
    nextPage?: string;
};

export type ActionBillSettings = {
    /**
     * Unique identifier for the matter to which the bill settings are associated.
     */
    id?: number;
    /**
     * Indicates the billing arrangement being applied to the matter.
     */
    billType?: 'Hourly' | 'Fixed fee';
    /**
     * The default email address to which finalized bills are sent for this matter.
     */
    sendToEmailAddress?: string;
    /**
     * Indicates whether any quoted amount includes fees and/or costs (disbursements).
     */
    quotedAmountIncludes?: 'Fees' | 'Costs' | 'Fees and costs';
    /**
     * A quoted amount for this matter.
     */
    quotedAmount?: number;
    /**
     * Flag to indicate if the matter is billable.
     */
    isBillable?: 'T' | 'F';
    /**
     * Flag to indicate if UTBMS is enabled for this matter.
     */
    isUtbmsEnabled?: 'T' | 'F';
    /**
     * UTBMS task category code.
     */
    utbmsTaskCategoryCode?: string;
    /**
     * Default behavior for time entries.
     */
    defaultTimeEntryBehavior?: 'Bill' | 'Hide' | 'No Charge';
    /**
     * Indicates what sales tax is applied to.
     */
    salesTaxAppliesTo?: 'Fees' | 'Expenses' | 'All';
    /**
     * The discount type applicable for the matter.
     */
    discountType?: 'Amount' | 'Percentage' | 'None';
    /**
     * The amount of any discount.
     */
    discountAmount?: number;
    /**
     * Flag to indicate if sales tax is enabled for the matter.
     */
    isSalesTaxEnabled?: 'T' | 'F';
    links?: Links;
};

export type Links = {
    /**
     * Unique identifier for the default rate applicable to this matter.
     */
    defaultRate?: number;
    /**
     * ISO 3 character code for the default billing currency.
     */
    readonly currency?: string;
    /**
     * Unique identifier for the sales tax rate applicable to the bill settings.
     */
    salesTaxRate?: number;
};

export type UpdateLinks = {
    /**
     * Unique identifier for the default rate applicable to this matter.
     */
    defaultRate?: number;
    /**
     * Unique identifier for the sales tax rate applicable to the bill settings.
     */
    salesTaxRate?: number;
};

export type UpdateBillSettings = {
    /**
     * Indicates the billing arrangement being applied to the matter.
     */
    billType?: 'Hourly' | 'Fixed fee';
    /**
     * The default email address to which finalized bills are sent for this matter.
     */
    sendToEmailAddress?: string;
    /**
     * Indicates whether any quoted amount includes fees and/or costs (disbursements).
     */
    quotedAmountIncludes?: 'Fees' | 'Costs' | 'Fees and costs';
    /**
     * A quoted amount for this matter.
     */
    quotedAmount?: number;
    /**
     * Flag to indicate if UTBMS is enabled for this matter.
     */
    isUtbmsEnabled?: 'T' | 'F';
    /**
     * UTBMS task category code.
     */
    utbmsTaskCategoryCode?: string;
    /**
     * Default behavior for time entries.
     */
    defaultTimeEntryBehavior?: 'Bill' | 'Hide' | 'No Charge';
    /**
     * Indicates what sales tax is applied to.
     */
    salesTaxAppliesTo?: 'Fees' | 'Expenses' | 'All';
    /**
     * The discount type applicable for the matter.
     */
    discountType?: 'Amount' | 'Percentage' | 'None';
    /**
     * The amount of any discount.
     */
    discountAmount?: number;
    /**
     * Flag to indicate if sales tax is enabled for the matter.
     */
    isSalesTaxEnabled?: 'T' | 'F';
    links?: UpdateLinks;
};

export type PagedActionBillSettingsWritable = {
    actionbillsettings?: Array<ActionBillSettingsWritable>;
    meta?: PageMetaData;
};

export type ActionBillSettingsWritable = {
    /**
     * Unique identifier for the matter to which the bill settings are associated.
     */
    id?: number;
    /**
     * Indicates the billing arrangement being applied to the matter.
     */
    billType?: 'Hourly' | 'Fixed fee';
    /**
     * The default email address to which finalized bills are sent for this matter.
     */
    sendToEmailAddress?: string;
    /**
     * Indicates whether any quoted amount includes fees and/or costs (disbursements).
     */
    quotedAmountIncludes?: 'Fees' | 'Costs' | 'Fees and costs';
    /**
     * A quoted amount for this matter.
     */
    quotedAmount?: number;
    /**
     * Flag to indicate if UTBMS is enabled for this matter.
     */
    isUtbmsEnabled?: 'T' | 'F';
    /**
     * UTBMS task category code.
     */
    utbmsTaskCategoryCode?: string;
    /**
     * Default behavior for time entries.
     */
    defaultTimeEntryBehavior?: 'Bill' | 'Hide' | 'No Charge';
    /**
     * Indicates what sales tax is applied to.
     */
    salesTaxAppliesTo?: 'Fees' | 'Expenses' | 'All';
    /**
     * The discount type applicable for the matter.
     */
    discountType?: 'Amount' | 'Percentage' | 'None';
    /**
     * The amount of any discount.
     */
    discountAmount?: number;
    /**
     * Flag to indicate if sales tax is enabled for the matter.
     */
    isSalesTaxEnabled?: 'T' | 'F';
    links?: LinksWritable;
};

export type LinksWritable = {
    /**
     * Unique identifier for the default rate applicable to this matter.
     */
    defaultRate?: number;
    /**
     * Unique identifier for the sales tax rate applicable to the bill settings.
     */
    salesTaxRate?: number;
};

export type UpdateActionBillSettings = UpdateBillSettings;

export type GetActionbillsettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actionbillsettings';
};

export type GetActionbillsettingsResponses = {
    /**
     * OK.
     */
    200: PagedActionBillSettings;
};

export type GetActionbillsettingsResponse = GetActionbillsettingsResponses[keyof GetActionbillsettingsResponses];

export type GetActionbillsettingsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a matter.
         */
        id: number;
    };
    query?: never;
    url: '/actionbillsettings/{id}';
};

export type GetActionbillsettingsByIdResponses = {
    /**
     * OK.
     */
    200: ActionBillSettings;
};

export type GetActionbillsettingsByIdResponse = GetActionbillsettingsByIdResponses[keyof GetActionbillsettingsByIdResponses];

export type PutActionbillsettingsByIdData = {
    body?: UpdateActionBillSettings;
    path: {
        /**
         * Unique identifier for a matter.
         */
        id: number;
    };
    query?: never;
    url: '/actionbillsettings/{id}';
};

export type PutActionbillsettingsByIdResponses = {
    /**
     * OK.
     */
    200: ActionBillSettings;
};

export type PutActionbillsettingsByIdResponse = PutActionbillsettingsByIdResponses[keyof PutActionbillsettingsByIdResponses];
