// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteContactfoldersByIdData, DeleteContactfoldersByIdResponses, GetContactfoldersByIdData, GetContactfoldersByIdResponses, GetContactfoldersData, GetContactfoldersResponses, PostContactfoldersData, PostContactfoldersResponses, PutContactfoldersByIdData, PutContactfoldersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all contact folders.
 */
export const getContactfolders = <ThrowOnError extends boolean = false>(options?: Options<GetContactfoldersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetContactfoldersResponses, unknown, ThrowOnError>({
        url: '/contactfolders',
        ...options
    });
};

/**
 * Create a new contact folder.
 */
export const postContactfolders = <ThrowOnError extends boolean = false>(options?: Options<PostContactfoldersData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostContactfoldersResponses, unknown, ThrowOnError>({
        url: '/contactfolders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single contact folder record.
 */
export const deleteContactfoldersById = <ThrowOnError extends boolean = false>(options: Options<DeleteContactfoldersByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteContactfoldersByIdResponses, unknown, ThrowOnError>({
        url: '/contactfolders/{id}',
        ...options
    });
};

/**
 * Returns a single contact folder record.
 */
export const getContactfoldersById = <ThrowOnError extends boolean = false>(options: Options<GetContactfoldersByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetContactfoldersByIdResponses, unknown, ThrowOnError>({
        url: '/contactfolders/{id}',
        ...options
    });
};

/**
 * Updates a single folder.
 */
export const putContactfoldersById = <ThrowOnError extends boolean = false>(options: Options<PutContactfoldersByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutContactfoldersByIdResponses, unknown, ThrowOnError>({
        url: '/contactfolders/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
