// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedContactFolders = {
    contactfolders?: Array<ContactFolder>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    contactfolders?: ContactFoldersPageData;
};

export type ContactFoldersPageData = {
    /**
     * The total number of contact folder records returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of contact folder records.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of contact folder records.
     */
    prevPage?: string;
    /**
     * A URL to the next page of contact folder records.
     */
    nextPage?: string;
};

export type ContactFolder = {
    /**
     * Unique identifier for a single contact folder record.
     */
    readonly id?: number;
    /**
     * Name of the folder.
     */
    name?: string;
    links?: ContactFolderLinks;
};

export type ContactFolderLinks = {
    /**
     * Unique identifier for a parent folder. Null means root folder.
     */
    readonly parentFolder?: string;
    /**
     * Unique identifier for the contact associated with the folder.
     */
    readonly participant?: number;
};

export type CreateContactFolder = {
    /**
     * Name of the folder.
     */
    name: string;
    links?: CreateContactFolderLinks;
};

export type CreateContactFolderLinks = {
    /**
     * Unique identifier for a parent folder. Null means root folder.
     */
    parentFolder?: string;
    /**
     * Unique identifier for the contact associated with the folder.
     */
    participant: number;
};

export type UpdateContactFolder = {
    /**
     * Name of the folder.
     */
    name?: string;
    links?: UpdateContactFolderLinks;
};

export type UpdateContactFolderLinks = {
    /**
     * Unique identifier for a parent folder. Null means root folder.
     */
    parentFolder?: string;
    /**
     * Unique identifier for the contact associated with the folder.
     */
    participant: number;
};

export type PagedContactFoldersWritable = {
    contactfolders?: Array<ContactFolderWritable>;
    meta?: PageMetaData;
};

export type ContactFolderWritable = {
    /**
     * Name of the folder.
     */
    name?: string;
};

export type CreateContactFolder2 = CreateContactFolder;

export type UpdateContactFolder2 = UpdateContactFolder;

export type GetContactfoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contactfolders';
};

export type GetContactfoldersResponses = {
    /**
     * OK.
     */
    200: PagedContactFolders;
};

export type GetContactfoldersResponse = GetContactfoldersResponses[keyof GetContactfoldersResponses];

export type PostContactfoldersData = {
    body?: CreateContactFolder2;
    path?: never;
    query?: never;
    url: '/contactfolders';
};

export type PostContactfoldersResponses = {
    /**
     * OK.
     */
    200: ContactFolder;
};

export type PostContactfoldersResponse = PostContactfoldersResponses[keyof PostContactfoldersResponses];

export type DeleteContactfoldersByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single contact folder record.
         */
        id: number;
    };
    query?: never;
    url: '/contactfolders/{id}';
};

export type DeleteContactfoldersByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteContactfoldersByIdResponse = DeleteContactfoldersByIdResponses[keyof DeleteContactfoldersByIdResponses];

export type GetContactfoldersByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single contact folder record.
         */
        id: number;
    };
    query?: never;
    url: '/contactfolders/{id}';
};

export type GetContactfoldersByIdResponses = {
    /**
     * OK.
     */
    200: ContactFolder;
};

export type GetContactfoldersByIdResponse = GetContactfoldersByIdResponses[keyof GetContactfoldersByIdResponses];

export type PutContactfoldersByIdData = {
    body?: UpdateContactFolder2;
    path: {
        /**
         * Unique identifier for a single contact folder record.
         */
        id: number;
    };
    query?: never;
    url: '/contactfolders/{id}';
};

export type PutContactfoldersByIdResponses = {
    /**
     * OK.
     */
    200: ContactFolder;
};

export type PutContactfoldersByIdResponse = PutContactfoldersByIdResponses[keyof PutContactfoldersByIdResponses];
