// This file is auto-generated by @hey-api/openapi-ts

export const PagedDisabilityStatusSchema = {
    type: 'object',
    properties: {
        disabilitystatus: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DisabilityStatus'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        disabilitystatus: {
            '$ref': '#/components/schemas/DisabilityStatusPageData'
        }
    }
} as const;

export const DisabilityStatusPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of disability status values returned by the underlying query.',
            type: 'integer',
            example: 4
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of disability status values.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of disability status values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/disabilitystatus?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of disability status values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/disabilitystatus?page=3'
        }
    }
} as const;

export const DisabilityStatusSchema = {
    type: 'object',
    properties: {
        status: {
            description: 'Status value.',
            example: 'Physical',
            type: 'string',
            format: 'string'
        }
    }
} as const;
