// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedDisabilityStatus = {
    disabilitystatus?: Array<DisabilityStatus>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    disabilitystatus?: DisabilityStatusPageData;
};

export type DisabilityStatusPageData = {
    /**
     * The total number of disability status values returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of disability status values.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of disability status values.
     */
    prevPage?: string;
    /**
     * A URL to the next page of disability status values.
     */
    nextPage?: string;
};

export type DisabilityStatus = {
    /**
     * Status value.
     */
    status?: string;
};

export type GetDisabilitystatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/disabilitystatus';
};

export type GetDisabilitystatusResponses = {
    /**
     * OK.
     */
    200: PagedDisabilityStatus;
};

export type GetDisabilitystatusResponse = GetDisabilitystatusResponses[keyof GetDisabilitystatusResponses];
