// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDatacollectionfieldByIdData, DeleteDatacollectionfieldByIdResponses, GetDatacollectionfieldByIdData, GetDatacollectionfieldByIdResponses, GetDatacollectionfieldsData, GetDatacollectionfieldsResponses, PostDatacollectionfieldsData, PostDatacollectionfieldsResponses, PutDatacollectionfieldByIdData, PutDatacollectionfieldByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of data collection fields.
 */
export const getDatacollectionfields = <ThrowOnError extends boolean = false>(options?: Options<GetDatacollectionfieldsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDatacollectionfieldsResponses, unknown, ThrowOnError>({
        url: '/datacollectionfields',
        ...options
    });
};

/**
 * Create a new data collection field.
 */
export const postDatacollectionfields = <ThrowOnError extends boolean = false>(options?: Options<PostDatacollectionfieldsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDatacollectionfieldsResponses, unknown, ThrowOnError>({
        url: '/datacollectionfields',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a data collection field.
 */
export const deleteDatacollectionfieldById = <ThrowOnError extends boolean = false>(options: Options<DeleteDatacollectionfieldByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteDatacollectionfieldByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfield/{id}',
        ...options
    });
};

/**
 * Returns a single data collection field.
 */
export const getDatacollectionfieldById = <ThrowOnError extends boolean = false>(options: Options<GetDatacollectionfieldByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetDatacollectionfieldByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfield/{id}',
        ...options
    });
};

/**
 * Update a data collection field.
 */
export const putDatacollectionfieldById = <ThrowOnError extends boolean = false>(options: Options<PutDatacollectionfieldByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutDatacollectionfieldByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfield/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
