// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedDataCollectionFields = {
    datacollectionfields?: Array<DataCollectionField>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    datacollectionfields?: DataCollectionFieldsPageData;
};

export type DataCollectionFieldsPageData = {
    /**
     * The total number of data collection fields returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of data collection fields.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of data collection fields.
     */
    prevPage?: string;
    /**
     * A URL to the next page of data collection fields.
     */
    nextPage?: string;
};

export type DataCollectionField = {
    /**
     * Unique identifier for the data collection field. The identifier is a composite value composed from the data collection unique identifier and the data field name.
     */
    readonly id?: string;
    /**
     * Name for the data collection field.
     */
    name?: string;
    /**
     * Data type for the data collection field.
     */
    dataType?: 'Appointment' | 'AutoNumber' | 'AutoNumberDC' | 'Boolean' | 'Date' | 'DateNM' | 'DateTime' | 'DateTimeNM' | 'DropDown' | 'DropDownMulti' | 'HtmlReadOnly' | 'Money' | 'Number' | 'Participant' | 'Str255' | 'Str255Protected' | 'TextArea';
    /**
     * Display label for the data collection field.
     */
    label?: string;
    /**
     * The data field's display position on the form relative to other data fields.
     */
    formOrder?: number;
    /**
     * Unknown.
     */
    listOrder?: number;
    /**
     * Indicates if a value is required for the data field.
     */
    required?: 'T' | 'F';
    /**
     * Description for the data collection field.
     */
    description?: string;
    /**
     * Fragment of HTML that is displayed after the data field.
     */
    customHtmlBelow?: string;
    /**
     * Fragment of HTML that is displayed before the data field.
     */
    customHtmlAbove?: string;
    links?: DataCollectionFieldLinks;
};

export type DataCollectionFieldLinks = {
    /**
     * Unique identifier of the data collection to which the data collection field is associated.
     */
    dataCollection?: number;
    /**
     * Unique identifier for a tag associated with this data collection field.
     */
    tag?: number;
};

export type CreateDataCollectionField = {
    /**
     * Name for the data collection field. Please note the name cannot be changed after the data collection field has been created.
     */
    name: string;
    /**
     * Data type for the data collection field.
     */
    dataType: 'Appointment' | 'AutoNumber' | 'AutoNumberDC' | 'Boolean' | 'Date' | 'DateNM' | 'DateTime' | 'DateTimeNM' | 'DropDown' | 'DropDownMulti' | 'HtmlReadOnly' | 'Money' | 'Number' | 'Participant' | 'Str255' | 'Str255Protected' | 'TextArea';
    /**
     * Label for the data collection field.
     */
    label?: string;
    /**
     * The data field's display position on the form.
     */
    formOrder?: number;
    /**
     * Unknown.
     */
    listOrder?: number;
    /**
     * Indicates if a value is required for the data field.
     */
    required?: 'T' | 'F';
    /**
     * Description for the data collection field.
     */
    description?: string;
    /**
     * Fragment of HTML that is displayed after the data field.
     */
    customHtmlBelow?: string;
    /**
     * Fragment of HTML that is displayed before the data field.
     */
    customHtmlAbove?: string;
    links?: CreateDataCollectionFieldLinks;
};

export type CreateDataCollectionFieldLinks = {
    /**
     * Unique identifier of the data collection to which the data collection field is associated.
     */
    dataCollection: number;
    /**
     * Unique identifier for a tag associated with this data collection field.
     */
    tag?: number;
};

export type UpdateDataCollectionField = {
    /**
     * Data type for the data collection field.
     */
    dataType?: 'Appointment' | 'AutoNumber' | 'AutoNumberDC' | 'Boolean' | 'Date' | 'DateNM' | 'DateTime' | 'DateTimeNM' | 'DropDown' | 'DropDownMulti' | 'HtmlReadOnly' | 'Money' | 'Number' | 'Participant' | 'Str255' | 'Str255Protected' | 'TextArea';
    /**
     * Label for the data collection field.
     */
    label?: string;
    /**
     * The data field's display position on the form.
     */
    formOrder?: number;
    /**
     * Unknown.
     */
    listOrder?: number;
    /**
     * Indicates if a value is required for the data field.
     */
    required?: 'T' | 'F';
    /**
     * Description for the data collection field.
     */
    description?: string;
    /**
     * Fragment of HTML that is displayed after the data field.
     */
    customHtmlBelow?: string;
    /**
     * Fragment of HTML that is displayed before the data field.
     */
    customHtmlAbove?: string;
    links?: UpdateDataCollectionFieldLinks;
};

export type UpdateDataCollectionFieldLinks = {
    /**
     * Unique identifier of the data collection to which the data collection field is associated.
     */
    dataCollection: number;
    /**
     * Unique identifier for a tag associated with this data collection field.
     */
    tag?: number;
};

export type PagedDataCollectionFieldsWritable = {
    datacollectionfields?: Array<DataCollectionFieldWritable>;
    meta?: PageMetaData;
};

export type DataCollectionFieldWritable = {
    /**
     * Name for the data collection field.
     */
    name?: string;
    /**
     * Data type for the data collection field.
     */
    dataType?: 'Appointment' | 'AutoNumber' | 'AutoNumberDC' | 'Boolean' | 'Date' | 'DateNM' | 'DateTime' | 'DateTimeNM' | 'DropDown' | 'DropDownMulti' | 'HtmlReadOnly' | 'Money' | 'Number' | 'Participant' | 'Str255' | 'Str255Protected' | 'TextArea';
    /**
     * Display label for the data collection field.
     */
    label?: string;
    /**
     * The data field's display position on the form relative to other data fields.
     */
    formOrder?: number;
    /**
     * Unknown.
     */
    listOrder?: number;
    /**
     * Indicates if a value is required for the data field.
     */
    required?: 'T' | 'F';
    /**
     * Description for the data collection field.
     */
    description?: string;
    /**
     * Fragment of HTML that is displayed after the data field.
     */
    customHtmlBelow?: string;
    /**
     * Fragment of HTML that is displayed before the data field.
     */
    customHtmlAbove?: string;
    links?: DataCollectionFieldLinks;
};

export type CreateDataCollectionField2 = CreateDataCollectionField;

export type UpdateDataCollectionField2 = UpdateDataCollectionField;

export type GetDatacollectionfieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datacollectionfields';
};

export type GetDatacollectionfieldsResponses = {
    /**
     * OK.
     */
    200: PagedDataCollectionFields;
};

export type GetDatacollectionfieldsResponse = GetDatacollectionfieldsResponses[keyof GetDatacollectionfieldsResponses];

export type PostDatacollectionfieldsData = {
    body?: CreateDataCollectionField2;
    path?: never;
    query?: never;
    url: '/datacollectionfields';
};

export type PostDatacollectionfieldsResponses = {
    /**
     * OK.
     */
    200: DataCollectionField;
};

export type PostDatacollectionfieldsResponse = PostDatacollectionfieldsResponses[keyof PostDatacollectionfieldsResponses];

export type DeleteDatacollectionfieldByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a data collection field. Please note this is a composite identifier composed from the data collection unique identifier and the data field name separated by "--".
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfield/{id}';
};

export type DeleteDatacollectionfieldByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteDatacollectionfieldByIdResponse = DeleteDatacollectionfieldByIdResponses[keyof DeleteDatacollectionfieldByIdResponses];

export type GetDatacollectionfieldByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a data collection field. Please note this is a composite identifier composed from the data collection unique identifier and the data field name separated by "--".
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfield/{id}';
};

export type GetDatacollectionfieldByIdResponses = {
    /**
     * OK.
     */
    200: DataCollectionField;
};

export type GetDatacollectionfieldByIdResponse = GetDatacollectionfieldByIdResponses[keyof GetDatacollectionfieldByIdResponses];

export type PutDatacollectionfieldByIdData = {
    body?: UpdateDataCollectionField2;
    path: {
        /**
         * Unique identifier for a data collection field. Please note this is a composite identifier composed from the data collection unique identifier and the data field name separated by "--".
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfield/{id}';
};

export type PutDatacollectionfieldByIdResponses = {
    /**
     * OK.
     */
    200: DataCollectionField;
};

export type PutDatacollectionfieldByIdResponse = PutDatacollectionfieldByIdResponses[keyof PutDatacollectionfieldByIdResponses];
