// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetParticipantsByIdData, GetParticipantsByIdResponses, GetParticipantsData, GetParticipantsResponses, PostParticipantsData, PostParticipantsResponses, PutParticipantsByIdData, PutParticipantsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of participants. For information on how to construct requests filtering by various properties, please refer to the API Developer Portal.
 */
export const getParticipants = <ThrowOnError extends boolean = false>(options?: Options<GetParticipantsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetParticipantsResponses, unknown, ThrowOnError>({
        url: '/participants',
        ...options
    });
};

/**
 * Create a new participant.
 */
export const postParticipants = <ThrowOnError extends boolean = false>(options?: Options<PostParticipantsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostParticipantsResponses, unknown, ThrowOnError>({
        url: '/participants',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Returns a single participant.
 */
export const getParticipantsById = <ThrowOnError extends boolean = false>(options: Options<GetParticipantsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetParticipantsByIdResponses, unknown, ThrowOnError>({
        url: '/participants/{id}',
        ...options
    });
};

/**
 * Updates a participant
 */
export const putParticipantsById = <ThrowOnError extends boolean = false>(options: Options<PutParticipantsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutParticipantsByIdResponses, unknown, ThrowOnError>({
        url: '/participants/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
