// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedQuickCodes = {
    QuickCodes?: Array<QuickCode>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    QuickCodes?: QuickCodesPageData;
};

export type QuickCodesPageData = {
    /**
     * The total number of Quick Code records returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Quick Codes.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Quick Codes.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Quick Codes.
     */
    nextPage?: string;
};

export type QuickCode = {
    /**
     * Unique identifier (code) for the Quick Code.
     */
    readonly id?: number;
    /**
     * The value for the quick code.
     */
    quickCode?: string;
    /**
     * A description for the quick code.
     */
    description?: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
    links?: QuickCodeLinks;
};

export type QuickCodeLinks = {
    /**
     * Unique identifier for a rate associated with the quick code.
     */
    readonly rate?: number;
};

export type CreateQuickCode = {
    /**
     * The value for the quick code.
     */
    quickCode: string;
    /**
     * A description for the quick code.
     */
    description: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
    links?: CreateQuickCodeLinks;
};

export type CreateQuickCodeLinks = {
    /**
     * Unique identifier for a rate associated with the quick code.
     */
    readonly rate?: number;
};

export type UpdateQuickCode = {
    /**
     * The value for the quick code.
     */
    quickCode?: string;
    /**
     * A description for the quick code.
     */
    description?: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
    links?: UpdateQuickCodeLinks;
};

export type UpdateQuickCodeLinks = {
    /**
     * Unique identifier for a rate associated with the quick code.
     */
    readonly rate?: number;
};

export type PagedQuickCodesWritable = {
    QuickCodes?: Array<QuickCodeWritable>;
    meta?: PageMetaData;
};

export type QuickCodeWritable = {
    /**
     * The value for the quick code.
     */
    quickCode?: string;
    /**
     * A description for the quick code.
     */
    description?: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
};

export type CreateQuickCodeWritable = {
    /**
     * The value for the quick code.
     */
    quickCode: string;
    /**
     * A description for the quick code.
     */
    description: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
};

export type UpdateQuickCodeWritable = {
    /**
     * The value for the quick code.
     */
    quickCode?: string;
    /**
     * A description for the quick code.
     */
    description?: string;
    /**
     * Indicates if the quick code is available for retainer transfers.
     */
    useForRetainerTransfers?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for receipts.
     */
    useForReceipts?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for tasks.
     */
    useForTasks?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for time entry.
     */
    useForTimeEntry?: 'T' | 'F';
    /**
     * Indicates if the quick code is available for withdrawals.
     */
    useForWithdrawals?: 'T' | 'F';
};

export type CreateQuickCode2 = CreateQuickCodeWritable;

export type UpdateQuickCode2 = UpdateQuickCodeWritable;

export type GetQuickcodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quickcodes';
};

export type GetQuickcodesResponses = {
    /**
     * OK.
     */
    200: PagedQuickCodes;
};

export type GetQuickcodesResponse = GetQuickcodesResponses[keyof GetQuickcodesResponses];

export type PostQuickcodesData = {
    body?: CreateQuickCode2;
    path?: never;
    query?: never;
    url: '/quickcodes';
};

export type PostQuickcodesResponses = {
    /**
     * OK.
     */
    200: QuickCode;
};

export type PostQuickcodesResponse = PostQuickcodesResponses[keyof PostQuickcodesResponses];

export type GetQuickcodesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single Quick Code.
         */
        id: number;
    };
    query?: never;
    url: '/quickcodes/{id}';
};

export type GetQuickcodesByIdResponses = {
    /**
     * OK.
     */
    200: QuickCode;
};

export type GetQuickcodesByIdResponse = GetQuickcodesByIdResponses[keyof GetQuickcodesByIdResponses];

export type PutQuickcodesByIdData = {
    body?: UpdateQuickCode2;
    path: {
        /**
         * Unique identifier for a single Quick Code.
         */
        id: number;
    };
    query?: never;
    url: '/quickcodes/{id}';
};

export type PutQuickcodesByIdResponses = {
    /**
     * OK.
     */
    200: QuickCode;
};

export type PutQuickcodesByIdResponse = PutQuickcodesByIdResponses[keyof PutQuickcodesByIdResponses];
