// This file is auto-generated by @hey-api/openapi-ts

export const participantadditionalnotificationmethodsSchema = {
    type: 'object',
    properties: {
        participantadditionalnotificationmethods: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParticipantAdditionalNotificationMethod'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        participantadditionalnotificationmethods: {
            '$ref': '#/components/schemas/ParticipantAdditionalNotificationMethodPageData'
        }
    }
} as const;

export const ParticipantAdditionalNotificationMethodPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of Participant Additional Notification Methods returned by the underlying query.',
            type: 'integer',
            example: 4
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of Participant Additional Notification Methods.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of Participant Additional Notification Methods.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantadditionalnotificationmethods?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of Participant Additional Notification Methods.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantadditionalnotificationmethods?page=3'
        }
    }
} as const;

export const ParticipantAdditionalNotificationMethodSchema = {
    type: 'object',
    properties: {
        notificationMethod: {
            description: 'The method of notification.',
            enum: ['E-Mail', 'SMS', 'Phone', 'Fax', 'Mail', 'Skype', 'Facebook', 'IM', 'Twitter'],
            type: 'string',
            format: 'string',
            example: 'Facebook'
        },
        address: {
            description: 'The address applicable to the notification method.',
            type: 'string',
            format: 'string',
            example: 'john.smith@mycompany.com'
        },
        notes: {
            description: 'Optional notes for this notification method.',
            type: 'string',
            format: 'string',
            example: 'Phone number of secondary property.'
        },
        links: {
            '$ref': '#/components/schemas/ParticipantAdditionalNotificationMethodLinks'
        }
    }
} as const;

export const ParticipantAdditionalNotificationMethodLinksSchema = {
    type: 'object',
    properties: {
        participant: {
            description: 'Unique identifier of the participant to whom this additional notification method is to be associated.',
            example: 8945,
            type: 'integer'
        }
    }
} as const;

export const CreateParticipantAdditionalNotificationMethodSchema = {
    type: 'object',
    required: ['notificationMethod', 'address'],
    properties: {
        notificationMethod: {
            description: 'The method of notification.',
            enum: ['E-Mail', 'SMS', 'Phone', 'Fax', 'Mail', 'Skype', 'Facebook', 'IM', 'Twitter'],
            type: 'string',
            format: 'string',
            example: 'Facebook'
        },
        address: {
            description: 'The address applicable to the notification method.',
            type: 'string',
            format: 'string',
            example: 'john.smith@mycompany.com'
        },
        notes: {
            description: 'Optional notes for this notification method.',
            type: 'string',
            format: 'string',
            example: 'Phone number of secondary property.'
        },
        links: {
            '$ref': '#/components/schemas/CreateParticipantAdditionalNotificationMethodLinks'
        }
    }
} as const;

export const CreateParticipantAdditionalNotificationMethodLinksSchema = {
    type: 'object',
    required: ['participant'],
    properties: {
        participant: {
            description: 'Unique identifier of the participant to whom this additional notification method is to be associated.',
            example: 8945,
            type: 'integer'
        }
    }
} as const;

export const UpdateParticipantAdditionalNotificationMethodSchema = {
    type: 'object',
    required: ['notificationMethod', 'address'],
    properties: {
        notificationMethod: {
            description: 'The method of notification.',
            enum: ['E-Mail', 'SMS', 'Phone', 'Fax', 'Mail', 'Skype', 'Facebook', 'IM', 'Twitter'],
            type: 'string',
            format: 'string',
            example: 'Facebook'
        },
        address: {
            description: 'The address applicable to the notification method.',
            type: 'string',
            format: 'string',
            example: 'john.smith@mycompany.com'
        },
        notes: {
            description: 'Optional notes for this notification method.',
            type: 'string',
            format: 'string',
            example: 'Phone number of secondary property.'
        },
        links: {
            '$ref': '#/components/schemas/UpdateParticipantAdditionalNotificationMethodLinks'
        }
    }
} as const;

export const UpdateParticipantAdditionalNotificationMethodLinksSchema = {
    type: 'object',
    required: ['participant'],
    properties: {
        participant: {
            description: 'Unique identifier of the participant to whom this additional notification method is to be associated.',
            example: 8945,
            type: 'integer'
        }
    }
} as const;
