// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteParticipantadditionalnotificationmethodsByIdData, DeleteParticipantadditionalnotificationmethodsByIdResponses, GetParticipantadditionalnotificationmethodsByIdData, GetParticipantadditionalnotificationmethodsByIdResponses, GetParticipantadditionalnotificationmethodsData, GetParticipantadditionalnotificationmethodsResponses, PostParticipantadditionalnotificationmethodsData, PostParticipantadditionalnotificationmethodsResponses, PutParticipantadditionalnotificationmethodsByIdData, PutParticipantadditionalnotificationmethodsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a list of all Participant Additional Notification Methods.
 */
export const getParticipantadditionalnotificationmethods = <ThrowOnError extends boolean = false>(options?: Options<GetParticipantadditionalnotificationmethodsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetParticipantadditionalnotificationmethodsResponses, unknown, ThrowOnError>({
        url: '/participantadditionalnotificationmethods',
        ...options
    });
};

/**
 * Create a new Participant Additional Notification Method.
 */
export const postParticipantadditionalnotificationmethods = <ThrowOnError extends boolean = false>(options?: Options<PostParticipantadditionalnotificationmethodsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostParticipantadditionalnotificationmethodsResponses, unknown, ThrowOnError>({
        url: '/participantadditionalnotificationmethods',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a single Participant Additional Notification Method record.
 */
export const deleteParticipantadditionalnotificationmethodsById = <ThrowOnError extends boolean = false>(options: Options<DeleteParticipantadditionalnotificationmethodsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteParticipantadditionalnotificationmethodsByIdResponses, unknown, ThrowOnError>({
        url: '/participantadditionalnotificationmethods/{id}',
        ...options
    });
};

/**
 * Returns a single Participant Additional Notification Method.
 */
export const getParticipantadditionalnotificationmethodsById = <ThrowOnError extends boolean = false>(options: Options<GetParticipantadditionalnotificationmethodsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetParticipantadditionalnotificationmethodsByIdResponses, unknown, ThrowOnError>({
        url: '/participantadditionalnotificationmethods/{id}',
        ...options
    });
};

/**
 * Updates a single Participant Additional Notification Method record.
 */
export const putParticipantadditionalnotificationmethodsById = <ThrowOnError extends boolean = false>(options: Options<PutParticipantadditionalnotificationmethodsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutParticipantadditionalnotificationmethodsByIdResponses, unknown, ThrowOnError>({
        url: '/participantadditionalnotificationmethods/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
