// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type Participantadditionalnotificationmethods = {
    participantadditionalnotificationmethods?: Array<ParticipantAdditionalNotificationMethod>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    participantadditionalnotificationmethods?: ParticipantAdditionalNotificationMethodPageData;
};

export type ParticipantAdditionalNotificationMethodPageData = {
    /**
     * The total number of Participant Additional Notification Methods returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Participant Additional Notification Methods.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Participant Additional Notification Methods.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Participant Additional Notification Methods.
     */
    nextPage?: string;
};

export type ParticipantAdditionalNotificationMethod = {
    /**
     * The method of notification.
     */
    notificationMethod?: 'E-Mail' | 'SMS' | 'Phone' | 'Fax' | 'Mail' | 'Skype' | 'Facebook' | 'IM' | 'Twitter';
    /**
     * The address applicable to the notification method.
     */
    address?: string;
    /**
     * Optional notes for this notification method.
     */
    notes?: string;
    links?: ParticipantAdditionalNotificationMethodLinks;
};

export type ParticipantAdditionalNotificationMethodLinks = {
    /**
     * Unique identifier of the participant to whom this additional notification method is to be associated.
     */
    participant?: number;
};

export type CreateParticipantAdditionalNotificationMethod = {
    /**
     * The method of notification.
     */
    notificationMethod: 'E-Mail' | 'SMS' | 'Phone' | 'Fax' | 'Mail' | 'Skype' | 'Facebook' | 'IM' | 'Twitter';
    /**
     * The address applicable to the notification method.
     */
    address: string;
    /**
     * Optional notes for this notification method.
     */
    notes?: string;
    links?: CreateParticipantAdditionalNotificationMethodLinks;
};

export type CreateParticipantAdditionalNotificationMethodLinks = {
    /**
     * Unique identifier of the participant to whom this additional notification method is to be associated.
     */
    participant: number;
};

export type UpdateParticipantAdditionalNotificationMethod = {
    /**
     * The method of notification.
     */
    notificationMethod: 'E-Mail' | 'SMS' | 'Phone' | 'Fax' | 'Mail' | 'Skype' | 'Facebook' | 'IM' | 'Twitter';
    /**
     * The address applicable to the notification method.
     */
    address: string;
    /**
     * Optional notes for this notification method.
     */
    notes?: string;
    links?: UpdateParticipantAdditionalNotificationMethodLinks;
};

export type UpdateParticipantAdditionalNotificationMethodLinks = {
    /**
     * Unique identifier of the participant to whom this additional notification method is to be associated.
     */
    participant: number;
};

export type CreateParticipantAdditionalNotificationMethod2 = CreateParticipantAdditionalNotificationMethod;

export type UpdateParticipantAdditionalNotificationMethod2 = UpdateParticipantAdditionalNotificationMethod;

export type GetParticipantadditionalnotificationmethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/participantadditionalnotificationmethods';
};

export type GetParticipantadditionalnotificationmethodsResponses = {
    /**
     * OK.
     */
    200: Participantadditionalnotificationmethods;
};

export type GetParticipantadditionalnotificationmethodsResponse = GetParticipantadditionalnotificationmethodsResponses[keyof GetParticipantadditionalnotificationmethodsResponses];

export type PostParticipantadditionalnotificationmethodsData = {
    body?: CreateParticipantAdditionalNotificationMethod2;
    path?: never;
    query?: never;
    url: '/participantadditionalnotificationmethods';
};

export type PostParticipantadditionalnotificationmethodsResponses = {
    /**
     * OK.
     */
    200: ParticipantAdditionalNotificationMethod;
};

export type PostParticipantadditionalnotificationmethodsResponse = PostParticipantadditionalnotificationmethodsResponses[keyof PostParticipantadditionalnotificationmethodsResponses];

export type DeleteParticipantadditionalnotificationmethodsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the Participant Additional Notification Method record.
         */
        id: string;
    };
    query?: never;
    url: '/participantadditionalnotificationmethods/{id}';
};

export type DeleteParticipantadditionalnotificationmethodsByIdResponses = {
    /**
     * Success, No content.
     */
    204: void;
};

export type DeleteParticipantadditionalnotificationmethodsByIdResponse = DeleteParticipantadditionalnotificationmethodsByIdResponses[keyof DeleteParticipantadditionalnotificationmethodsByIdResponses];

export type GetParticipantadditionalnotificationmethodsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the Participant Additional Notification Method.
         */
        id: string;
    };
    query?: never;
    url: '/participantadditionalnotificationmethods/{id}';
};

export type GetParticipantadditionalnotificationmethodsByIdResponses = {
    /**
     * OK.
     */
    200: ParticipantAdditionalNotificationMethod;
};

export type GetParticipantadditionalnotificationmethodsByIdResponse = GetParticipantadditionalnotificationmethodsByIdResponses[keyof GetParticipantadditionalnotificationmethodsByIdResponses];

export type PutParticipantadditionalnotificationmethodsByIdData = {
    body?: UpdateParticipantAdditionalNotificationMethod2;
    path: {
        /**
         * Unique identifier for a single Participant Additional Notification Method record.
         */
        id: number;
    };
    query?: never;
    url: '/participantadditionalnotificationmethods/{id}';
};

export type PutParticipantadditionalnotificationmethodsByIdResponses = {
    /**
     * OK.
     */
    200: ParticipantAdditionalNotificationMethod;
};

export type PutParticipantadditionalnotificationmethodsByIdResponse = PutParticipantadditionalnotificationmethodsByIdResponses[keyof PutParticipantadditionalnotificationmethodsByIdResponses];
