// This file is auto-generated by @hey-api/openapi-ts

export const participantrelationshiptypesSchema = {
    type: 'object',
    properties: {
        participantrelationshiptypes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ParticipantRelationshipType'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        participantrelationshiptypes: {
            '$ref': '#/components/schemas/ParticipantRelationshipTypePageData'
        }
    }
} as const;

export const ParticipantRelationshipTypePageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of Participant Relationship Types returned by the underlying query.',
            type: 'integer',
            example: 4
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 8
        },
        page: {
            description: 'The page number for this page of Participant Relationship Types.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of Participant Relationship Types.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantrelationshiptypes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of Participant Relationship Types.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/participantrelationshiptypes?page=3'
        }
    }
} as const;

export const ParticipantRelationshipTypeSchema = {
    type: 'object',
    properties: {
        category: {
            description: 'The category for the relationship type.',
            enum: ['IndividualToIndividual', 'IndividualToCompany', 'CompanyToIndividual', 'CompanyToCompany'],
            type: 'string',
            format: 'string',
            example: 'IndividualToIndividual'
        },
        relationshipType: {
            description: 'The name for the relationship type.',
            type: 'string',
            format: 'string',
            example: 'Acquaintance'
        }
    }
} as const;

export const CreateParticipantRelationshipTypeSchema = {
    type: 'object',
    required: ['category', 'relationship'],
    properties: {
        category: {
            description: 'The category for the relationship type.',
            enum: ['IndividualToIndividual', 'IndividualToCompany', 'CompanyToIndividual', 'CompanyToCompany'],
            type: 'string',
            format: 'string',
            example: 'IndividualToIndividual'
        },
        relationshipType: {
            description: 'The name for the relationship type. A relationship type must be unique within a category.',
            type: 'string',
            format: 'string',
            example: 'Acquaintance'
        }
    }
} as const;
