// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteParticipantrelationshiptypesByIdData, DeleteParticipantrelationshiptypesByIdResponses, GetParticipantrelationshiptypesByIdData, GetParticipantrelationshiptypesByIdResponses, GetParticipantrelationshiptypesData, GetParticipantrelationshiptypesResponses, PostParticipantrelationshiptypesData, PostParticipantrelationshiptypesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a list of all Participant Relationship Types.
 */
export const getParticipantrelationshiptypes = <ThrowOnError extends boolean = false>(options?: Options<GetParticipantrelationshiptypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetParticipantrelationshiptypesResponses, unknown, ThrowOnError>({
        url: '/participantrelationshiptypes',
        ...options
    });
};

/**
 * Create a new participant relationship type.
 */
export const postParticipantrelationshiptypes = <ThrowOnError extends boolean = false>(options?: Options<PostParticipantrelationshiptypesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostParticipantrelationshiptypesResponses, unknown, ThrowOnError>({
        url: '/participantrelationshiptypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a single participant relationship type.
 */
export const deleteParticipantrelationshiptypesById = <ThrowOnError extends boolean = false>(options: Options<DeleteParticipantrelationshiptypesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteParticipantrelationshiptypesByIdResponses, unknown, ThrowOnError>({
        url: '/participantrelationshiptypes/{id}',
        ...options
    });
};

/**
 * Returns a single participant relationship type.
 */
export const getParticipantrelationshiptypesById = <ThrowOnError extends boolean = false>(options: Options<GetParticipantrelationshiptypesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetParticipantrelationshiptypesByIdResponses, unknown, ThrowOnError>({
        url: '/participantrelationshiptypes/{id}',
        ...options
    });
};
