// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type Participantrelationshiptypes = {
    participantrelationshiptypes?: Array<ParticipantRelationshipType>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    participantrelationshiptypes?: ParticipantRelationshipTypePageData;
};

export type ParticipantRelationshipTypePageData = {
    /**
     * The total number of Participant Relationship Types returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Participant Relationship Types.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Participant Relationship Types.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Participant Relationship Types.
     */
    nextPage?: string;
};

export type ParticipantRelationshipType = {
    /**
     * The category for the relationship type.
     */
    category?: 'IndividualToIndividual' | 'IndividualToCompany' | 'CompanyToIndividual' | 'CompanyToCompany';
    /**
     * The name for the relationship type.
     */
    relationshipType?: string;
};

export type CreateParticipantRelationshipType = {
    /**
     * The category for the relationship type.
     */
    category: 'IndividualToIndividual' | 'IndividualToCompany' | 'CompanyToIndividual' | 'CompanyToCompany';
    /**
     * The name for the relationship type. A relationship type must be unique within a category.
     */
    relationshipType?: string;
};

export type CreateParticipantRelationshipType2 = CreateParticipantRelationshipType;

export type GetParticipantrelationshiptypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/participantrelationshiptypes';
};

export type GetParticipantrelationshiptypesResponses = {
    /**
     * OK.
     */
    200: Participantrelationshiptypes;
};

export type GetParticipantrelationshiptypesResponse = GetParticipantrelationshiptypesResponses[keyof GetParticipantrelationshiptypesResponses];

export type PostParticipantrelationshiptypesData = {
    body?: CreateParticipantRelationshipType2;
    path?: never;
    query?: never;
    url: '/participantrelationshiptypes';
};

export type PostParticipantrelationshiptypesResponses = {
    /**
     * OK.
     */
    200: ParticipantRelationshipType;
};

export type PostParticipantrelationshiptypesResponse = PostParticipantrelationshiptypesResponses[keyof PostParticipantrelationshiptypesResponses];

export type DeleteParticipantrelationshiptypesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the participant relationship type. This is a composite key composed from the category and relationship properties, separated by '--'.
         */
        id: string;
    };
    query?: never;
    url: '/participantrelationshiptypes/{id}';
};

export type DeleteParticipantrelationshiptypesByIdResponses = {
    /**
     * Success, No content.
     */
    204: void;
};

export type DeleteParticipantrelationshiptypesByIdResponse = DeleteParticipantrelationshiptypesByIdResponses[keyof DeleteParticipantrelationshiptypesByIdResponses];

export type GetParticipantrelationshiptypesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for the participant relationship type. This is a composite key composed from the category and relationship properties, separated by '--'.
         */
        id: string;
    };
    query?: never;
    url: '/participantrelationshiptypes/{id}';
};

export type GetParticipantrelationshiptypesByIdResponses = {
    /**
     * OK.
     */
    200: ParticipantRelationshipType;
};

export type GetParticipantrelationshiptypesByIdResponse = GetParticipantrelationshiptypesByIdResponses[keyof GetParticipantrelationshiptypesByIdResponses];
