// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetBillsData, GetBillsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of bills (invoices). For information on how to construct requests filtering by various properties, please refer to the API Developer Portal.
 */
export const getBills = <ThrowOnError extends boolean = false>(options?: Options<GetBillsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetBillsResponses, unknown, ThrowOnError>({
        url: '/bills',
        ...options
    });
};
