// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedBills = {
    bills?: Array<Bill>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    participants?: BillsPageData;
};

export type BillsPageData = {
    /**
     * The total number of bills returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of bills.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of bills.
     */
    prevPage?: string;
    /**
     * A URL to the next page of bills.
     */
    nextPage?: string;
};

export type Bill = {
    /**
     * Unique identifier for the bill.
     */
    id?: number;
    /**
     * The status of the bill.
     */
    status?: 'Draft' | 'Open' | 'Closed' | 'Deleted';
    /**
     * Internal reference identifier.
     */
    ourReference?: string;
    /**
     * External reference identifier.
     */
    theirReference?: string;
    /**
     * The 3 character ISO currency code.
     */
    currency?: string;
    /**
     * Date of the bill.
     */
    invoiceDate?: string;
    /**
     * The date when the bill is due.
     */
    dueDate?: string;
    /**
     * The inclusive total amount of the bill.
     */
    totalInclusive?: number;
    /**
     * The exclusive total amount of the bill.
     */
    totalExclusive?: number;
    /**
     * Total sales tax for the bill.
     */
    totalSalesTax?: number;
    /**
     * Total amount paid for the bill.
     */
    totalPaid?: number;
    /**
     * Total amount due for the bill.
     */
    totalDue?: number;
    /**
     * Date and time of record creation.
     */
    createdTimestamp?: string;
    /**
     * Date and time of last record modification.
     */
    modifiedTimestamp?: string;
    /**
     * Date and time the record was deleted.
     */
    deletedTimestamp?: string;
    links?: BillLinks;
};

export type BillLinks = {
    /**
     * Unique identifier of the division to which the bill is associated.
     */
    division?: number;
    /**
     * List of matters to which this bill is associated.
     */
    action?: Array<number>;
    /**
     * Unique identifier of the person to whom the bill is associated.
     */
    theirParticipant?: string;
};

export type GetBillsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bills';
};

export type GetBillsResponses = {
    /**
     * OK.
     */
    200: PagedBills;
};

export type GetBillsResponse = GetBillsResponses[keyof GetBillsResponses];
