// This file is auto-generated by @hey-api/openapi-ts

export const PagedFileNotesSchema = {
    type: 'object',
    properties: {
        filenotes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FileNote'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        filenotes: {
            '$ref': '#/components/schemas/FileNotesPageData'
        }
    }
} as const;

export const FileNotesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of file notes returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of file notes.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of file notes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/filenotes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of file notes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/filenotes?page=3'
        }
    }
} as const;

export const FileNoteSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the file note.',
            example: 2347,
            type: 'integer',
            readOnly: true
        },
        enteredTimestamp: {
            description: 'The date and time the file note is entered.',
            example: '2022-05-03T00:09:00+12:00',
            format: 'timestamp',
            type: 'string',
            readOnly: true
        },
        text: {
            description: 'Content of the file note.',
            example: 'Client is requesting follow up meeting this week.',
            type: 'string'
        },
        enteredBy: {
            description: 'The Actionstep user who entered the file note.',
            example: 'Smith, John',
            type: 'string',
            readOnly: true
        },
        source: {
            description: 'Indicates the source of the file note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the file note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/FileNoteLinks'
        }
    }
} as const;

export const FileNoteLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the file note is associated.',
            example: 34,
            type: 'integer'
        },
        document: {
            description: 'Unique identifier of a document associated to the file note.',
            example: 8376,
            type: 'integer'
        },
        participant: {
            description: 'Unique identifier of the Actionstep user who created the file note.',
            example: 546,
            type: 'integer',
            readOnly: true
        },
        tags: {
            description: 'Zero or more tags associated with the file note. Each tag is the unique identifier for the tag.',
            example: [1283, 1934],
            type: 'array',
            items: {
                type: 'integer'
            }
        }
    }
} as const;

export const CreateFileNoteSchema = {
    type: 'object',
    required: ['text'],
    properties: {
        text: {
            description: 'Content of the file note.',
            example: 'Client is requesting follow up meeting this week.',
            type: 'string'
        },
        source: {
            description: 'Indicates the source of the file note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the file note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/CreateFileNoteLinks'
        }
    }
} as const;

export const CreateFileNoteLinksSchema = {
    type: 'object',
    required: ['action'],
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the file note is associated.',
            example: 34,
            type: 'integer'
        },
        document: {
            description: 'Unique identifier of a document associated to the file note.',
            example: 8376,
            type: 'integer'
        },
        tags: {
            description: 'Zero or more tags to be associated with the file note. Each tag is the unique identifier for the tag.',
            example: [1283, 1934],
            type: 'array',
            items: {
                type: 'integer'
            }
        }
    }
} as const;

export const UpdateFileNoteSchema = {
    type: 'object',
    required: ['text'],
    properties: {
        text: {
            description: 'Content of the file note.',
            example: 'Client is requesting follow up meeting this week.',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the file note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/UpdateFileNoteLinks'
        }
    }
} as const;

export const UpdateFileNoteLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the file note is associated.',
            example: 34,
            type: 'integer'
        },
        document: {
            description: 'Unique identifier of a document associated to the file note.',
            example: 8376,
            type: 'integer'
        },
        tags: {
            description: 'Zero or more tags to be associated with the file note. Each tag is the unique identifier for the tag. The supplied list of tags will replace in totality any existing tags. To remove all tags specify an empty array.',
            example: [1283, 1934],
            type: 'array',
            items: {
                type: 'integer'
            }
        }
    }
} as const;

export const PagedFileNotesWritableSchema = {
    type: 'object',
    properties: {
        filenotes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FileNoteWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const FileNoteWritableSchema = {
    type: 'object',
    properties: {
        text: {
            description: 'Content of the file note.',
            example: 'Client is requesting follow up meeting this week.',
            type: 'string'
        },
        source: {
            description: 'Indicates the source of the file note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the file note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/FileNoteLinksWritable'
        }
    }
} as const;

export const FileNoteLinksWritableSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the file note is associated.',
            example: 34,
            type: 'integer'
        },
        document: {
            description: 'Unique identifier of a document associated to the file note.',
            example: 8376,
            type: 'integer'
        },
        tags: {
            description: 'Zero or more tags associated with the file note. Each tag is the unique identifier for the tag.',
            example: [1283, 1934],
            type: 'array',
            items: {
                type: 'integer'
            }
        }
    }
} as const;
