// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteFilenotesByIdData, DeleteFilenotesByIdResponses, GetFilenotesByIdData, GetFilenotesByIdResponses, GetFilenotesData, GetFilenotesResponses, PostFilenotesData, PostFilenotesResponses, PutFilenotesByIdData, PutFilenotesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a collection of file notes.
 */
export const getFilenotes = <ThrowOnError extends boolean = false>(options?: Options<GetFilenotesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFilenotesResponses, unknown, ThrowOnError>({
        url: '/filenotes',
        ...options
    });
};

/**
 * Create a new file note.
 */
export const postFilenotes = <ThrowOnError extends boolean = false>(options?: Options<PostFilenotesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostFilenotesResponses, unknown, ThrowOnError>({
        url: '/filenotes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a file note.
 */
export const deleteFilenotesById = <ThrowOnError extends boolean = false>(options: Options<DeleteFilenotesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteFilenotesByIdResponses, unknown, ThrowOnError>({
        url: '/filenotes/{id}',
        ...options
    });
};

/**
 * Returns a single file note.
 */
export const getFilenotesById = <ThrowOnError extends boolean = false>(options: Options<GetFilenotesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetFilenotesByIdResponses, unknown, ThrowOnError>({
        url: '/filenotes/{id}',
        ...options
    });
};

/**
 * Update a file note.
 */
export const putFilenotesById = <ThrowOnError extends boolean = false>(options: Options<PutFilenotesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutFilenotesByIdResponses, unknown, ThrowOnError>({
        url: '/filenotes/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
