// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedFileNotes = {
    filenotes?: Array<FileNote>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    filenotes?: FileNotesPageData;
};

export type FileNotesPageData = {
    /**
     * The total number of file notes returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of file notes.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of file notes.
     */
    prevPage?: string;
    /**
     * A URL to the next page of file notes.
     */
    nextPage?: string;
};

export type FileNote = {
    /**
     * Unique identifier for the file note.
     */
    readonly id?: number;
    /**
     * The date and time the file note is entered.
     */
    readonly enteredTimestamp?: string;
    /**
     * Content of the file note.
     */
    text?: string;
    /**
     * The Actionstep user who entered the file note.
     */
    readonly enteredBy?: string;
    /**
     * Indicates the source of the file note.
     */
    source?: 'System' | 'User';
    /**
     * The date and time for the file note.
     */
    noteTimestamp?: string;
    links?: FileNoteLinks;
};

export type FileNoteLinks = {
    /**
     * Unique identifier of the matter to which the file note is associated.
     */
    action?: number;
    /**
     * Unique identifier of a document associated to the file note.
     */
    document?: number;
    /**
     * Unique identifier of the Actionstep user who created the file note.
     */
    readonly participant?: number;
    /**
     * Zero or more tags associated with the file note. Each tag is the unique identifier for the tag.
     */
    tags?: Array<number>;
};

export type CreateFileNote = {
    /**
     * Content of the file note.
     */
    text: string;
    /**
     * Indicates the source of the file note.
     */
    source?: 'System' | 'User';
    /**
     * The date and time for the file note.
     */
    noteTimestamp?: string;
    links?: CreateFileNoteLinks;
};

export type CreateFileNoteLinks = {
    /**
     * Unique identifier of the matter to which the file note is associated.
     */
    action: number;
    /**
     * Unique identifier of a document associated to the file note.
     */
    document?: number;
    /**
     * Zero or more tags to be associated with the file note. Each tag is the unique identifier for the tag.
     */
    tags?: Array<number>;
};

export type UpdateFileNote = {
    /**
     * Content of the file note.
     */
    text: string;
    /**
     * The date and time for the file note.
     */
    noteTimestamp?: string;
    links?: UpdateFileNoteLinks;
};

export type UpdateFileNoteLinks = {
    /**
     * Unique identifier of the matter to which the file note is associated.
     */
    action?: number;
    /**
     * Unique identifier of a document associated to the file note.
     */
    document?: number;
    /**
     * Zero or more tags to be associated with the file note. Each tag is the unique identifier for the tag. The supplied list of tags will replace in totality any existing tags. To remove all tags specify an empty array.
     */
    tags?: Array<number>;
};

export type PagedFileNotesWritable = {
    filenotes?: Array<FileNoteWritable>;
    meta?: PageMetaData;
};

export type FileNoteWritable = {
    /**
     * Content of the file note.
     */
    text?: string;
    /**
     * Indicates the source of the file note.
     */
    source?: 'System' | 'User';
    /**
     * The date and time for the file note.
     */
    noteTimestamp?: string;
    links?: FileNoteLinksWritable;
};

export type FileNoteLinksWritable = {
    /**
     * Unique identifier of the matter to which the file note is associated.
     */
    action?: number;
    /**
     * Unique identifier of a document associated to the file note.
     */
    document?: number;
    /**
     * Zero or more tags associated with the file note. Each tag is the unique identifier for the tag.
     */
    tags?: Array<number>;
};

export type CreateFileNote2 = CreateFileNote;

export type UpdateFileNote2 = UpdateFileNote;

export type GetFilenotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/filenotes';
};

export type GetFilenotesResponses = {
    /**
     * OK.
     */
    200: PagedFileNotes;
};

export type GetFilenotesResponse = GetFilenotesResponses[keyof GetFilenotesResponses];

export type PostFilenotesData = {
    body?: CreateFileNote2;
    path?: never;
    query?: never;
    url: '/filenotes';
};

export type PostFilenotesResponses = {
    /**
     * OK.
     */
    200: FileNote;
};

export type PostFilenotesResponse = PostFilenotesResponses[keyof PostFilenotesResponses];

export type DeleteFilenotesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a file note.
         */
        id: number;
    };
    query?: never;
    url: '/filenotes/{id}';
};

export type DeleteFilenotesByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteFilenotesByIdResponse = DeleteFilenotesByIdResponses[keyof DeleteFilenotesByIdResponses];

export type GetFilenotesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a file note.
         */
        id: number;
    };
    query?: never;
    url: '/filenotes/{id}';
};

export type GetFilenotesByIdResponses = {
    /**
     * OK.
     */
    200: FileNote;
};

export type GetFilenotesByIdResponse = GetFilenotesByIdResponses[keyof GetFilenotesByIdResponses];

export type PutFilenotesByIdData = {
    body?: UpdateFileNote2;
    path: {
        /**
         * Unique identifier for a file note.
         */
        id: number;
    };
    query?: never;
    url: '/filenotes/{id}';
};

export type PutFilenotesByIdResponses = {
    /**
     * OK.
     */
    200: FileNote;
};

export type PutFilenotesByIdResponse = PutFilenotesByIdResponses[keyof PutFilenotesByIdResponses];
