// This file is auto-generated by @hey-api/openapi-ts

export const PagedContactNotesSchema = {
    type: 'object',
    properties: {
        contactnotes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ContactNote'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        contactnotes: {
            '$ref': '#/components/schemas/ContactNotesPageData'
        }
    }
} as const;

export const ContactNotesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of contact notes returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of contact notes.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of contact notes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/contactnotes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of contact notes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/contactnotes?page=3'
        }
    }
} as const;

export const ContactNoteSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for the contact note.',
            example: 2347,
            type: 'integer',
            readOnly: true
        },
        enteredTimestamp: {
            description: 'The date and time the contact note is entered.',
            example: '2022-05-03T00:09:00+12:00',
            format: 'timestamp',
            type: 'string',
            readOnly: true
        },
        text: {
            description: 'Content of the contact note.',
            example: 'Please review AML status.',
            type: 'string'
        },
        enteredBy: {
            description: 'The Actionstep user who entered the contact note.',
            example: 'Smith, John',
            type: 'string',
            readOnly: true
        },
        enteredByParticipant: {
            description: 'Unique identifier of the Actionstep user who created the contact note.',
            example: 842,
            type: 'integer',
            readOnly: true
        },
        source: {
            description: 'Indicates the source of the contact note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the contact note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/ContactNoteLinks'
        }
    }
} as const;

export const ContactNoteLinksSchema = {
    type: 'object',
    properties: {
        participant: {
            description: 'Unique identifier of the contact to whom this note is associated.',
            example: 546,
            type: 'integer',
            readOnly: true
        }
    }
} as const;

export const CreateContactNoteSchema = {
    type: 'object',
    required: ['text'],
    properties: {
        text: {
            description: 'Content of the contact note.',
            example: 'Updated AML status notes.',
            type: 'string'
        },
        source: {
            description: 'Indicates the source of the contact note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the contact note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/CreateContactNoteLinks'
        }
    }
} as const;

export const CreateContactNoteLinksSchema = {
    type: 'object',
    required: ['participant'],
    properties: {
        participant: {
            description: 'Unique identifier of the contact to whom the note is associated.',
            example: 546,
            type: 'integer'
        }
    }
} as const;

export const UpdateContactNoteSchema = {
    type: 'object',
    required: ['text'],
    properties: {
        text: {
            description: 'Content of the contact note.',
            example: 'Updated address details.',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the contact note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        links: {
            '$ref': '#/components/schemas/UpdateContactNoteLinks'
        }
    }
} as const;

export const UpdateContactNoteLinksSchema = {
    type: 'object',
    properties: {
        participant: {
            description: 'Unique identifier of the contact to whom the note is associated.',
            example: 546,
            type: 'integer'
        }
    }
} as const;

export const PagedContactNotesWritableSchema = {
    type: 'object',
    properties: {
        contactnotes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ContactNoteWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ContactNoteWritableSchema = {
    type: 'object',
    properties: {
        text: {
            description: 'Content of the contact note.',
            example: 'Please review AML status.',
            type: 'string'
        },
        source: {
            description: 'Indicates the source of the contact note.',
            enum: ['System', 'User'],
            example: 'User',
            type: 'string'
        },
        noteTimestamp: {
            description: 'The date and time for the contact note.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        }
    }
} as const;
