// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteGendertypesByGenderTypeNameData, DeleteGendertypesByGenderTypeNameResponses, GetGendertypesByGenderTypeNameData, GetGendertypesByGenderTypeNameResponses, GetGendertypesData, GetGendertypesResponses, PostGendertypesData, PostGendertypesResponses, PutGendertypesByGenderTypeNameData, PutGendertypesByGenderTypeNameResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns a list of custom gender types.
 */
export const getGendertypes = <ThrowOnError extends boolean = false>(options?: Options<GetGendertypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGendertypesResponses, unknown, ThrowOnError>({
        url: '/gendertypes',
        ...options
    });
};

/**
 * Create a new custom gender type.
 */
export const postGendertypes = <ThrowOnError extends boolean = false>(options?: Options<PostGendertypesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostGendertypesResponses, unknown, ThrowOnError>({
        url: '/gendertypes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a custom gender type. Please note - you cannot delete a custom gender type if it is already assigned to an existing participant record.
 */
export const deleteGendertypesByGenderTypeName = <ThrowOnError extends boolean = false>(options: Options<DeleteGendertypesByGenderTypeNameData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteGendertypesByGenderTypeNameResponses, unknown, ThrowOnError>({
        url: '/gendertypes/{genderTypeName}',
        ...options
    });
};

/**
 * Returns a single custom gender type.
 */
export const getGendertypesByGenderTypeName = <ThrowOnError extends boolean = false>(options: Options<GetGendertypesByGenderTypeNameData, ThrowOnError>) => {
    return (options.client ?? client).get<GetGendertypesByGenderTypeNameResponses, unknown, ThrowOnError>({
        url: '/gendertypes/{genderTypeName}',
        ...options
    });
};

/**
 * Update a single custom gender type.
 */
export const putGendertypesByGenderTypeName = <ThrowOnError extends boolean = false>(options: Options<PutGendertypesByGenderTypeNameData, ThrowOnError>) => {
    return (options.client ?? client).put<PutGendertypesByGenderTypeNameResponses, unknown, ThrowOnError>({
        url: '/gendertypes/{genderTypeName}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
