// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedGenderTypes = {
    gendertypes?: Array<GenderType>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    gendertypes?: GenderTypesPageData;
};

export type GenderTypesPageData = {
    /**
     * The total number of custom gender types returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of custom gender types.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of custom gender types.
     */
    prevPage?: string;
    /**
     * A URL to the next page of custom gender types.
     */
    nextPage?: string;
};

export type GenderType = {
    /**
     * Name of the custom gender type.
     */
    genderTypeName?: string;
    /**
     * One of 'Male', 'Female', 'Neutral', or 'Company'.
     */
    pronounType?: 'Male' | 'Female' | 'Neutral' | 'Company';
};

export type CreateGenderType = {
    /**
     * Name of the custom gender type.
     */
    genderTypeName: string;
    /**
     * One of 'Male', 'Female', 'Neutral', or 'Company'.
     */
    pronounType: 'Male' | 'Female' | 'Neutral' | 'Company';
};

export type UpdateGenderType = {
    /**
     * One of 'Male', 'Female', 'Neutral', or 'Company'.
     */
    pronounType: 'Male' | 'Female' | 'Neutral' | 'Company';
};

export type CreateGenderType2 = CreateGenderType;

export type UpdateGenderType2 = UpdateGenderType;

export type GetGendertypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/gendertypes';
};

export type GetGendertypesResponses = {
    /**
     * OK.
     */
    200: PagedGenderTypes;
};

export type GetGendertypesResponse = GetGendertypesResponses[keyof GetGendertypesResponses];

export type PostGendertypesData = {
    body?: CreateGenderType2;
    path?: never;
    query?: never;
    url: '/gendertypes';
};

export type PostGendertypesResponses = {
    /**
     * OK.
     */
    200: GenderType;
};

export type PostGendertypesResponse = PostGendertypesResponses[keyof PostGendertypesResponses];

export type DeleteGendertypesByGenderTypeNameData = {
    body?: never;
    path: {
        /**
         * Name of the custom gender type.
         */
        genderTypeName: string;
    };
    query?: never;
    url: '/gendertypes/{genderTypeName}';
};

export type DeleteGendertypesByGenderTypeNameResponses = {
    /**
     * Success, No content.
     */
    204: void;
};

export type DeleteGendertypesByGenderTypeNameResponse = DeleteGendertypesByGenderTypeNameResponses[keyof DeleteGendertypesByGenderTypeNameResponses];

export type GetGendertypesByGenderTypeNameData = {
    body?: never;
    path: {
        /**
         * Name of the custom gender type.
         */
        genderTypeName: string;
    };
    query?: never;
    url: '/gendertypes/{genderTypeName}';
};

export type GetGendertypesByGenderTypeNameResponses = {
    /**
     * OK.
     */
    200: GenderType;
};

export type GetGendertypesByGenderTypeNameResponse = GetGendertypesByGenderTypeNameResponses[keyof GetGendertypesByGenderTypeNameResponses];

export type PutGendertypesByGenderTypeNameData = {
    body?: UpdateGenderType2;
    path: {
        /**
         * Name of the custom gender type.
         */
        genderTypeName: string;
    };
    query?: never;
    url: '/gendertypes/{genderTypeName}';
};

export type PutGendertypesByGenderTypeNameResponses = {
    /**
     * OK.
     */
    200: GenderType;
};

export type PutGendertypesByGenderTypeNameResponse = PutGendertypesByGenderTypeNameResponses[keyof PutGendertypesByGenderTypeNameResponses];
