// This file is auto-generated by @hey-api/openapi-ts

export const PagedUTBMSCodesSchema = {
    type: 'object',
    properties: {
        UTBMSCodes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UTBMSCode'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        UTBMSCodes: {
            '$ref': '#/components/schemas/UTBMSCodesPageData'
        }
    }
} as const;

export const UTBMSCodesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of UTBMS code records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of UTBMS codes.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of UTBMS codes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/utbmscodes?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of UTBMS codes.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/utbmscodes?page=3'
        }
    }
} as const;

export const UTBMSCodeSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier (code) for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'A100',
            readOnly: true
        },
        categoryCode: {
            description: 'The category code to which the UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'Activity codes'
        },
        parentUtbmsCode: {
            description: 'The parent UTBMS code to which this UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'AA10'
        },
        description: {
            description: 'A description for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'Research'
        },
        overrideDescription: {
            description: 'A custom description for the time entry description field. Only relevant for Activity codes.',
            type: 'string',
            format: 'string',
            example: 'Case history research.'
        },
        enabled: {
            description: 'Indicates if the UTBMS code is enabled for use.',
            type: 'string',
            enum: ['T', 'F'],
            default: 'T',
            format: 'string',
            example: 'T'
        }
    }
} as const;

export const CreateUTBMSCodeSchema = {
    type: 'object',
    required: ['utbmsCode', 'categoryCode', 'description', 'enabled'],
    properties: {
        utbmsCode: {
            description: 'Unique identifier (code) for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'A100'
        },
        categoryCode: {
            description: 'The category code to which the UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'Activity codes'
        },
        parentUtbmsCode: {
            description: 'The parent UTBMS code to which this UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'AA10'
        },
        description: {
            description: 'A description for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'Research'
        },
        overrideDescription: {
            description: 'A custom description for the time entry description field. Only relevant for Activity codes.',
            type: 'string',
            format: 'string',
            example: 'Case history research.'
        },
        enabled: {
            description: 'Indicates if the UTBMS code is enabled for use.',
            type: 'string',
            enum: ['T', 'F'],
            default: 'T',
            format: 'string',
            example: 'T'
        }
    }
} as const;

export const UpdateUTBMSCodeSchema = {
    type: 'object',
    properties: {
        categoryCode: {
            description: 'The category code to which the UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'Activity codes'
        },
        parentUtbmsCode: {
            description: 'The parent UTBMS code to which this UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'AA10'
        },
        description: {
            description: 'A description for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'Research'
        },
        overrideDescription: {
            description: 'A custom description for the time entry description field. Only relevant for Activity codes.',
            type: 'string',
            format: 'string',
            example: 'Case history research.'
        },
        enabled: {
            description: 'Indicates if the UTBMS code is enabled for use.',
            type: 'string',
            enum: ['T', 'F'],
            default: 'T',
            format: 'string',
            example: 'T'
        }
    }
} as const;

export const PagedUTBMSCodesWritableSchema = {
    type: 'object',
    properties: {
        UTBMSCodes: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UTBMSCodeWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const UTBMSCodeWritableSchema = {
    type: 'object',
    properties: {
        categoryCode: {
            description: 'The category code to which the UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'Activity codes'
        },
        parentUtbmsCode: {
            description: 'The parent UTBMS code to which this UTBMS code is associated.',
            type: 'string',
            format: 'string',
            example: 'AA10'
        },
        description: {
            description: 'A description for the UTBMS code.',
            type: 'string',
            format: 'string',
            example: 'Research'
        },
        overrideDescription: {
            description: 'A custom description for the time entry description field. Only relevant for Activity codes.',
            type: 'string',
            format: 'string',
            example: 'Case history research.'
        },
        enabled: {
            description: 'Indicates if the UTBMS code is enabled for use.',
            type: 'string',
            enum: ['T', 'F'],
            default: 'T',
            format: 'string',
            example: 'T'
        }
    }
} as const;
