// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteUtbmscodesByIdData, DeleteUtbmscodesByIdResponses, GetUtbmscodesByIdData, GetUtbmscodesByIdResponses, GetUtbmscodesData, GetUtbmscodesResponses, PostUtbmscodesData, PostUtbmscodesResponses, PutUtbmscodesByIdData, PutUtbmscodesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all UTBMS codes.
 */
export const getUtbmscodes = <ThrowOnError extends boolean = false>(options?: Options<GetUtbmscodesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUtbmscodesResponses, unknown, ThrowOnError>({
        url: '/utbmscodes',
        ...options
    });
};

/**
 * Create a new UTBMS code.
 */
export const postUtbmscodes = <ThrowOnError extends boolean = false>(options?: Options<PostUtbmscodesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostUtbmscodesResponses, unknown, ThrowOnError>({
        url: '/utbmscodes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single UTBMS code.
 */
export const deleteUtbmscodesById = <ThrowOnError extends boolean = false>(options: Options<DeleteUtbmscodesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteUtbmscodesByIdResponses, unknown, ThrowOnError>({
        url: '/utbmscodes/{id}',
        ...options
    });
};

/**
 * Returns a single UTBMS code.
 */
export const getUtbmscodesById = <ThrowOnError extends boolean = false>(options: Options<GetUtbmscodesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUtbmscodesByIdResponses, unknown, ThrowOnError>({
        url: '/utbmscodes/{id}',
        ...options
    });
};

/**
 * Updates a single UTBMS code.
 */
export const putUtbmscodesById = <ThrowOnError extends boolean = false>(options: Options<PutUtbmscodesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutUtbmscodesByIdResponses, unknown, ThrowOnError>({
        url: '/utbmscodes/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
