// This file is auto-generated by @hey-api/openapi-ts

export const ParticipantTypeAttributesSchema = {
    type: 'object',
    additionalProperties: true,
    properties: {
        name: {
            type: 'string'
        },
        displayName: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        isBaseParticipantType: {
            type: 'boolean'
        },
        companyFlag: {
            type: 'boolean'
        },
        taxNumberAlias: {
            type: 'string'
        }
    }
} as const;

export const ParticipantTypeListResponseSchema = {
    type: 'object',
    additionalProperties: true,
    properties: {
        data: {
            type: 'array',
            items: {
                type: 'object',
                additionalProperties: true,
                properties: {
                    attributes: {
                        '$ref': '#/components/schemas/ParticipantTypeAttributes'
                    }
                }
            }
        }
    }
} as const;
