// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ParticipantTypeAttributes = {
    name?: string;
    displayName?: string;
    description?: string;
    isBaseParticipantType?: boolean;
    companyFlag?: boolean;
    taxNumberAlias?: string;
    [key: string]: unknown | string | boolean | undefined;
};

export type ParticipantTypeListResponse = {
    data?: Array<{
        attributes?: ParticipantTypeAttributes;
        [key: string]: unknown | ParticipantTypeAttributes | undefined;
    }>;
    [key: string]: unknown | Array<{
        attributes?: ParticipantTypeAttributes;
        [key: string]: unknown | ParticipantTypeAttributes | undefined;
    }> | undefined;
};

export type GetParticipanttypesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/participanttypes';
};

export type GetParticipanttypesResponses = {
    /**
     * OK
     */
    200: ParticipantTypeListResponse;
};

export type GetParticipanttypesResponse = GetParticipanttypesResponses[keyof GetParticipanttypesResponses];
