// This file is auto-generated by @hey-api/openapi-ts

export const PagedDataCollectionRecordValuesSchema = {
    type: 'object',
    properties: {
        datacollectionrecordvalues: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionRecordValue'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        datacollectionrecordvalues: {
            '$ref': '#/components/schemas/DataCollectionRecordValuesPageData'
        }
    }
} as const;

export const DataCollectionRecordValuesPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of data collection record values returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of data collection record values.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of data collection record values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionrecordvalues?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of data collection record values.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionrecordvalues?page=3'
        }
    }
} as const;

export const DataCollectionRecordValueSchema = {
    type: 'object',
    properties: {
        id: {
            description: "Unique identifier for the data collection record value. This is a composite identifier constructed from the data collection unique identifier, the data field name, and the data collection record unique identifier, all separated by a '--' delimiter.",
            example: '148--victim_age--6234',
            type: 'string',
            format: 'string',
            readOnly: true
        },
        stringValue: {
            description: 'Data field value as a string.',
            example: '2023-12-25',
            format: 'string',
            type: 'string'
        },
        last_modified_time_stamp: {
            description: 'Date and time the data field value was last modified.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        last_modified_by_user_id: {
            description: 'Unique identifier for the Actionstep user who last modified the data field value.',
            example: 7837,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionRecordValueLinks'
        }
    }
} as const;

export const DataCollectionRecordValueLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the data collection field value is associated.',
            example: 500,
            type: 'integer'
        },
        dataCollectionField: {
            description: "Unique identifier for the data collection field. This is a composite unique identifier composed from the data collection unique identifier and the data field name, separated by a '--' delimiter.",
            example: '148--victim_age',
            format: 'string',
            type: 'string'
        },
        dataCollectionRecord: {
            description: 'Unique identifier for the data record.',
            example: 6234,
            type: 'integer'
        },
        dataCollection: {
            description: 'Unique identifier of the data collection to which the data collection record is associated.',
            example: 148,
            type: 'integer'
        }
    }
} as const;

export const CreateDataCollectionRecordValueSchema = {
    type: 'object',
    required: ['stringValue'],
    properties: {
        stringValue: {
            description: 'Data field value as a string.',
            example: '2023-12-25',
            format: 'string',
            type: 'string'
        },
        last_modified_time_stamp: {
            description: 'Date and time the data field value is created.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        last_modified_by_user_id: {
            description: 'Unique identifier for the Actionstep user who is creating the data field value.',
            example: 7837,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/CreateDataCollectionRecordValueLinks'
        }
    }
} as const;

export const CreateDataCollectionRecordValueLinksSchema = {
    type: 'object',
    required: ['action', 'dataCollectionField', 'dataCollectionRecord', 'dataCollection'],
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the data collection field value is associated.',
            example: 500,
            type: 'integer'
        },
        dataCollectionField: {
            description: "Unique identifier for the data collection field. This is a composite unique identifier composed from the data collection unique identifier and the data field name, separated by a '--' delimiter.",
            example: '148--victim_age',
            format: 'string',
            type: 'string'
        },
        dataCollectionRecord: {
            description: 'Unique identifier for the data collection record.',
            example: 6234,
            type: 'integer'
        },
        dataCollection: {
            description: 'Unique identifier of the data collection to which the data collection record is associated.',
            example: 148,
            type: 'integer'
        }
    }
} as const;

export const UpdateDataCollectionRecordValueSchema = {
    type: 'object',
    required: ['stringValue'],
    properties: {
        stringValue: {
            description: 'Data field value as a string.',
            example: '2023-12-25',
            format: 'string',
            type: 'string'
        },
        last_modified_time_stamp: {
            description: 'Date and time the data field value is modified.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        last_modified_by_user_id: {
            description: 'Unique identifier for the Actionstep user who is modifying the data field value.',
            example: 7837,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/UpdateDataCollectionRecordValueLinks'
        }
    }
} as const;

export const UpdateDataCollectionRecordValueLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the data collection field value is associated.',
            example: 500,
            type: 'integer'
        },
        dataCollectionField: {
            description: "Unique identifier for the data collection field. This is a composite unique identifier composed from the data collection unique identifier and the data field name, separated by a '--' delimiter.",
            example: '148--victim_age',
            format: 'string',
            type: 'string'
        },
        dataCollectionRecord: {
            description: 'Unique identifier for the data record.',
            example: 6234,
            type: 'integer'
        },
        dataCollection: {
            description: 'Unique identifier of the data collection to which the data collection record is associated.',
            example: 148,
            type: 'integer'
        }
    }
} as const;

export const PagedDataCollectionRecordValuesWritableSchema = {
    type: 'object',
    properties: {
        datacollectionrecordvalues: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionRecordValueWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const DataCollectionRecordValueWritableSchema = {
    type: 'object',
    properties: {
        stringValue: {
            description: 'Data field value as a string.',
            example: '2023-12-25',
            format: 'string',
            type: 'string'
        },
        last_modified_time_stamp: {
            description: 'Date and time the data field value was last modified.',
            example: '2023-06-03T00:09:30+12:00',
            format: 'timestamp',
            type: 'string'
        },
        last_modified_by_user_id: {
            description: 'Unique identifier for the Actionstep user who last modified the data field value.',
            example: 7837,
            type: 'integer'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionRecordValueLinks'
        }
    }
} as const;
