// This file is auto-generated by @hey-api/openapi-ts

export const PagedDataCollectionFieldDropdownChoicesSchema = {
    type: 'object',
    properties: {
        datacollectionfielddropdownchoices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionFieldDropdownChoiceRecord'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        datacollectionfielddropdownchoices: {
            '$ref': '#/components/schemas/DataCollectionFieldDropdownChoiceRecordPageData'
        }
    }
} as const;

export const DataCollectionFieldDropdownChoiceRecordPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of data collection field dropdown choice records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of data collection field dropdown choices.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of data collection field dropdown choice records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionfielddropdownchoices?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of data collection field dropdown choice records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/datacollectionfielddropdownchoices?page=3'
        }
    }
} as const;

export const DataCollectionFieldDropdownChoiceRecordSchema = {
    type: 'object',
    properties: {
        id: {
            description: "Unique identifier for a single data collection field dropdown choice record. Note the unique identifier is a composite primary key comprising of the data collection identifier, the data field name, and the name associated with the dropdown choice, delimited by '--'.",
            type: 'string',
            format: 'string',
            example: '230--CarColor--Red',
            readOnly: true
        },
        name: {
            description: 'The name associated with the choice. The name property is displayed in the dropdown list.',
            type: 'string',
            format: 'string',
            example: 'Metallic Red'
        },
        value: {
            description: 'The value for the choice.',
            type: 'string',
            format: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.',
            type: 'integer',
            format: 'integer',
            default: 0,
            example: 3
        },
        isDefault: {
            description: 'Indicates a default choice. Only one item in a dropdown choice list can be marked as default.',
            enum: ['T', 'F'],
            type: 'string',
            format: 'string',
            example: 'T'
        },
        parentValue: {
            description: 'Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.',
            type: 'string',
            format: 'string',
            example: 'Country'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionFieldDropdownChoiceRecordLinks'
        }
    }
} as const;

export const DataCollectionFieldDropdownChoiceRecordLinksSchema = {
    type: 'object',
    properties: {
        dataField: {
            description: "Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.",
            type: 'string',
            format: 'string',
            example: '230--CarColor'
        },
        dataCollection: {
            description: 'Unique identifier for the parent data collection.',
            type: 'integer',
            format: 'string',
            example: 230
        }
    }
} as const;

export const CreateDataCollectionFieldDropdownChoiceRecordSchema = {
    type: 'object',
    required: ['name', 'value', 'listOrder', 'isDefault'],
    properties: {
        name: {
            description: 'The name associated with the choice. The name property is displayed in the dropdown list.',
            type: 'string',
            format: 'string',
            example: 'Metallic Red'
        },
        value: {
            description: 'The value for the choice.',
            type: 'string',
            format: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.',
            type: 'integer',
            format: 'integer',
            default: 0,
            example: 3
        },
        isDefault: {
            description: 'Indicates a default choice. Only one item in a dropdown choice list can be marked as default.',
            enum: ['T', 'F'],
            type: 'string',
            format: 'string',
            example: 'T'
        },
        parentValue: {
            description: 'Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.',
            type: 'string',
            format: 'string',
            example: 'Country'
        },
        links: {
            '$ref': '#/components/schemas/CreateDataCollectionFieldDropdownChoiceRecordLinks'
        }
    }
} as const;

export const CreateDataCollectionFieldDropdownChoiceRecordLinksSchema = {
    type: 'object',
    required: ['dataField'],
    properties: {
        dataField: {
            description: "Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.",
            type: 'string',
            format: 'string',
            example: '230--CarColor'
        },
        dataCollection: {
            description: 'Unique identifier for the parent data collection.',
            type: 'integer',
            format: 'string',
            example: 230
        }
    }
} as const;

export const UpdateDataCollectionFieldDropdownChoiceRecordSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'The name associated with the choice. The name property is displayed in the dropdown list.',
            type: 'string',
            format: 'string',
            example: 'Metallic Red'
        },
        value: {
            description: 'The value for the choice.',
            type: 'string',
            format: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.',
            type: 'integer',
            format: 'integer',
            default: 0,
            example: 3
        },
        isDefault: {
            description: 'Indicates a default choice. Only one item in a dropdown choice list can be marked as default.',
            enum: ['T', 'F'],
            type: 'string',
            format: 'string',
            example: 'T'
        },
        parentValue: {
            description: 'Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.',
            type: 'string',
            format: 'string',
            example: 'Country'
        },
        links: {
            '$ref': '#/components/schemas/UpdateDataCollectionFieldDropdownChoiceRecordLinks'
        }
    }
} as const;

export const UpdateDataCollectionFieldDropdownChoiceRecordLinksSchema = {
    type: 'object',
    properties: {
        dataField: {
            description: "Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.",
            type: 'string',
            format: 'string',
            example: '230--CarColor'
        },
        dataCollection: {
            description: 'Unique identifier for the parent data collection.',
            type: 'integer',
            format: 'string',
            example: 230
        }
    }
} as const;

export const PagedDataCollectionFieldDropdownChoicesWritableSchema = {
    type: 'object',
    properties: {
        datacollectionfielddropdownchoices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DataCollectionFieldDropdownChoiceRecordWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const DataCollectionFieldDropdownChoiceRecordWritableSchema = {
    type: 'object',
    properties: {
        name: {
            description: 'The name associated with the choice. The name property is displayed in the dropdown list.',
            type: 'string',
            format: 'string',
            example: 'Metallic Red'
        },
        value: {
            description: 'The value for the choice.',
            type: 'string',
            format: 'string',
            example: 'red'
        },
        listOrder: {
            description: 'The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.',
            type: 'integer',
            format: 'integer',
            default: 0,
            example: 3
        },
        isDefault: {
            description: 'Indicates a default choice. Only one item in a dropdown choice list can be marked as default.',
            enum: ['T', 'F'],
            type: 'string',
            format: 'string',
            example: 'T'
        },
        parentValue: {
            description: 'Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.',
            type: 'string',
            format: 'string',
            example: 'Country'
        },
        links: {
            '$ref': '#/components/schemas/DataCollectionFieldDropdownChoiceRecordLinks'
        }
    }
} as const;
