// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteDatacollectionfielddropdownchoicesByIdData, DeleteDatacollectionfielddropdownchoicesByIdResponses, GetDatacollectionfielddropdownchoicesByIdData, GetDatacollectionfielddropdownchoicesByIdResponses, GetDatacollectionfielddropdownchoicesData, GetDatacollectionfielddropdownchoicesResponses, PostDatacollectionfielddropdownchoicesData, PostDatacollectionfielddropdownchoicesResponses, PutDatacollectionfielddropdownchoicesByIdData, PutDatacollectionfielddropdownchoicesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all data collection field dropdown choice records.
 */
export const getDatacollectionfielddropdownchoices = <ThrowOnError extends boolean = false>(options?: Options<GetDatacollectionfielddropdownchoicesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDatacollectionfielddropdownchoicesResponses, unknown, ThrowOnError>({
        url: '/datacollectionfielddropdownchoices',
        ...options
    });
};

/**
 * Create a new data collection field dropdown choice record.
 */
export const postDatacollectionfielddropdownchoices = <ThrowOnError extends boolean = false>(options?: Options<PostDatacollectionfielddropdownchoicesData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDatacollectionfielddropdownchoicesResponses, unknown, ThrowOnError>({
        url: '/datacollectionfielddropdownchoices',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a single data collection field dropdown choice record.
 */
export const deleteDatacollectionfielddropdownchoicesById = <ThrowOnError extends boolean = false>(options: Options<DeleteDatacollectionfielddropdownchoicesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteDatacollectionfielddropdownchoicesByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfielddropdownchoices/{id}',
        ...options
    });
};

/**
 * Returns a single data collection field dropdown choice record.
 */
export const getDatacollectionfielddropdownchoicesById = <ThrowOnError extends boolean = false>(options: Options<GetDatacollectionfielddropdownchoicesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetDatacollectionfielddropdownchoicesByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfielddropdownchoices/{id}',
        ...options
    });
};

/**
 * Updates a single data collection field dropdown choice record.
 */
export const putDatacollectionfielddropdownchoicesById = <ThrowOnError extends boolean = false>(options: Options<PutDatacollectionfielddropdownchoicesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutDatacollectionfielddropdownchoicesByIdResponses, unknown, ThrowOnError>({
        url: '/datacollectionfielddropdownchoices/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
