// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedDataCollectionFieldDropdownChoices = {
    datacollectionfielddropdownchoices?: Array<DataCollectionFieldDropdownChoiceRecord>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    datacollectionfielddropdownchoices?: DataCollectionFieldDropdownChoiceRecordPageData;
};

export type DataCollectionFieldDropdownChoiceRecordPageData = {
    /**
     * The total number of data collection field dropdown choice records returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of data collection field dropdown choices.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of data collection field dropdown choice records.
     */
    prevPage?: string;
    /**
     * A URL to the next page of data collection field dropdown choice records.
     */
    nextPage?: string;
};

export type DataCollectionFieldDropdownChoiceRecord = {
    /**
     * Unique identifier for a single data collection field dropdown choice record. Note the unique identifier is a composite primary key comprising of the data collection identifier, the data field name, and the name associated with the dropdown choice, delimited by '--'.
     */
    readonly id?: string;
    /**
     * The name associated with the choice. The name property is displayed in the dropdown list.
     */
    name?: string;
    /**
     * The value for the choice.
     */
    value?: string;
    /**
     * The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.
     */
    listOrder?: number;
    /**
     * Indicates a default choice. Only one item in a dropdown choice list can be marked as default.
     */
    isDefault?: 'T' | 'F';
    /**
     * Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.
     */
    parentValue?: string;
    links?: DataCollectionFieldDropdownChoiceRecordLinks;
};

export type DataCollectionFieldDropdownChoiceRecordLinks = {
    /**
     * Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.
     */
    dataField?: string;
    /**
     * Unique identifier for the parent data collection.
     */
    dataCollection?: number;
};

export type CreateDataCollectionFieldDropdownChoiceRecord = {
    /**
     * The name associated with the choice. The name property is displayed in the dropdown list.
     */
    name: string;
    /**
     * The value for the choice.
     */
    value: string;
    /**
     * The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.
     */
    listOrder: number;
    /**
     * Indicates a default choice. Only one item in a dropdown choice list can be marked as default.
     */
    isDefault: 'T' | 'F';
    /**
     * Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.
     */
    parentValue?: string;
    links?: CreateDataCollectionFieldDropdownChoiceRecordLinks;
};

export type CreateDataCollectionFieldDropdownChoiceRecordLinks = {
    /**
     * Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.
     */
    dataField: string;
    /**
     * Unique identifier for the parent data collection.
     */
    dataCollection?: number;
};

export type UpdateDataCollectionFieldDropdownChoiceRecord = {
    /**
     * The name associated with the choice. The name property is displayed in the dropdown list.
     */
    name?: string;
    /**
     * The value for the choice.
     */
    value?: string;
    /**
     * The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.
     */
    listOrder?: number;
    /**
     * Indicates a default choice. Only one item in a dropdown choice list can be marked as default.
     */
    isDefault?: 'T' | 'F';
    /**
     * Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.
     */
    parentValue?: string;
    links?: UpdateDataCollectionFieldDropdownChoiceRecordLinks;
};

export type UpdateDataCollectionFieldDropdownChoiceRecordLinks = {
    /**
     * Unique identifier for a single data collection field. Note the unique identifier is a composite primary key comprising of the data collection identifier and the data field name, delimited by '--'.
     */
    dataField?: string;
    /**
     * Unique identifier for the parent data collection.
     */
    dataCollection?: number;
};

export type PagedDataCollectionFieldDropdownChoicesWritable = {
    datacollectionfielddropdownchoices?: Array<DataCollectionFieldDropdownChoiceRecordWritable>;
    meta?: PageMetaData;
};

export type DataCollectionFieldDropdownChoiceRecordWritable = {
    /**
     * The name associated with the choice. The name property is displayed in the dropdown list.
     */
    name?: string;
    /**
     * The value for the choice.
     */
    value?: string;
    /**
     * The order in which choices are displayed in the dropdown list. Choices with the same listOrder value are displayed in alphabetical order based on the name property.
     */
    listOrder?: number;
    /**
     * Indicates a default choice. Only one item in a dropdown choice list can be marked as default.
     */
    isDefault?: 'T' | 'F';
    /**
     * Used when creating hierarchical custom data fields to limit the displayed choices based on the value selected in a parent dropdown list. See [Creating Hierarchical Custom Data Fields](https://support.actionstep.com/support/solutions/articles/150000188403-creating-hierarchical-custom-data-fields-admin-) for further information.
     */
    parentValue?: string;
    links?: DataCollectionFieldDropdownChoiceRecordLinks;
};

export type CreateDataCollectionFieldDropdownChoiceRecord2 = CreateDataCollectionFieldDropdownChoiceRecord;

export type UpdateDataCollectionFieldDropdownChoiceRecord2 = UpdateDataCollectionFieldDropdownChoiceRecord;

export type GetDatacollectionfielddropdownchoicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/datacollectionfielddropdownchoices';
};

export type GetDatacollectionfielddropdownchoicesResponses = {
    /**
     * OK.
     */
    200: PagedDataCollectionFieldDropdownChoices;
};

export type GetDatacollectionfielddropdownchoicesResponse = GetDatacollectionfielddropdownchoicesResponses[keyof GetDatacollectionfielddropdownchoicesResponses];

export type PostDatacollectionfielddropdownchoicesData = {
    body?: CreateDataCollectionFieldDropdownChoiceRecord2;
    path?: never;
    query?: never;
    url: '/datacollectionfielddropdownchoices';
};

export type PostDatacollectionfielddropdownchoicesResponses = {
    /**
     * OK.
     */
    200: DataCollectionFieldDropdownChoiceRecord;
};

export type PostDatacollectionfielddropdownchoicesResponse = PostDatacollectionfielddropdownchoicesResponses[keyof PostDatacollectionfielddropdownchoicesResponses];

export type DeleteDatacollectionfielddropdownchoicesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single data collection field dropdown choice record. Note the unique identifier is a composite primary key comprising of the data collection identifier, the data field name, and the name associated with the dropdown choice, delimited by '--'.
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfielddropdownchoices/{id}';
};

export type DeleteDatacollectionfielddropdownchoicesByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteDatacollectionfielddropdownchoicesByIdResponse = DeleteDatacollectionfielddropdownchoicesByIdResponses[keyof DeleteDatacollectionfielddropdownchoicesByIdResponses];

export type GetDatacollectionfielddropdownchoicesByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single data collection field dropdown choice record. Note the unique identifier is a composite primary key comprising of the data collection identifier, the data field name, and the name associated with the dropdown choice, delimited by '--'.
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfielddropdownchoices/{id}';
};

export type GetDatacollectionfielddropdownchoicesByIdResponses = {
    /**
     * OK.
     */
    200: DataCollectionFieldDropdownChoiceRecord;
};

export type GetDatacollectionfielddropdownchoicesByIdResponse = GetDatacollectionfielddropdownchoicesByIdResponses[keyof GetDatacollectionfielddropdownchoicesByIdResponses];

export type PutDatacollectionfielddropdownchoicesByIdData = {
    body?: UpdateDataCollectionFieldDropdownChoiceRecord2;
    path: {
        /**
         * Unique identifier for a single data collection field dropdown choice record. Note the unique identifier is a composite primary key comprising of the data collection identifier, the data field name, and the name associated with the dropdown choice, delimited by '--'.
         */
        id: string;
    };
    query?: never;
    url: '/datacollectionfielddropdownchoices/{id}';
};

export type PutDatacollectionfielddropdownchoicesByIdResponses = {
    /**
     * OK.
     */
    200: DataCollectionFieldDropdownChoiceRecord;
};

export type PutDatacollectionfielddropdownchoicesByIdResponse = PutDatacollectionfielddropdownchoicesByIdResponses[keyof PutDatacollectionfielddropdownchoicesByIdResponses];
