// This file is auto-generated by @hey-api/openapi-ts

export const PagedContactRelationshipsSchema = {
    type: 'object',
    properties: {
        contactrelationships: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ContactRelationship'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        contactrelationships: {
            '$ref': '#/components/schemas/ContactRelationshipsPageData'
        }
    }
} as const;

export const ContactRelationshipsPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of contact relationship records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of contact relationship records.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of contact relationship records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/contactrelationships?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of contact relationship records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/contactrelationships?page=3'
        }
    }
} as const;

export const ContactRelationshipSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for a single contact relationship record. The identifier is composed from the relationship, fromContact, and toContact properties separated by "--".',
            type: 'string',
            format: 'string',
            example: 'Father-41854-845258',
            readOnly: true
        },
        relationship: {
            description: 'The relationship name between the two contacts.',
            type: 'string',
            format: 'string',
            example: 'Father'
        },
        links: {
            '$ref': '#/components/schemas/ContactRelationshipLinks'
        }
    }
} as const;

export const ContactRelationshipLinksSchema = {
    type: 'object',
    properties: {
        fromContact: {
            description: 'Unique identifier for the contact from which a relationship is established.',
            example: 41854,
            type: 'integer',
            readOnly: true
        },
        toContact: {
            description: 'Unique identifier for the contact to which a relationship is established.',
            example: 321845,
            type: 'integer',
            readOnly: true
        }
    }
} as const;

export const CreateContactRelationshipSchema = {
    type: 'object',
    required: ['relationship'],
    properties: {
        relationship: {
            description: 'The relationship name between the two contacts.',
            type: 'string',
            format: 'string',
            example: 'Father'
        },
        links: {
            '$ref': '#/components/schemas/CreateContactRelationshipLinks'
        }
    }
} as const;

export const CreateContactRelationshipLinksSchema = {
    type: 'object',
    required: ['fromContact', 'toContact'],
    properties: {
        fromContact: {
            description: 'Unique identifier for the contact from which a relationship is to be established.',
            example: 41854,
            type: 'integer'
        },
        toContact: {
            description: 'Unique identifier for the contact to which a relationship is to be established.',
            example: 321845,
            type: 'integer'
        }
    }
} as const;

export const PagedContactRelationshipsWritableSchema = {
    type: 'object',
    properties: {
        contactrelationships: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ContactRelationshipWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const ContactRelationshipWritableSchema = {
    type: 'object',
    properties: {
        relationship: {
            description: 'The relationship name between the two contacts.',
            type: 'string',
            format: 'string',
            example: 'Father'
        }
    }
} as const;
