// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteContactrelationshipsByIdData, DeleteContactrelationshipsByIdResponses, GetContactrelationshipsByIdData, GetContactrelationshipsByIdResponses, GetContactrelationshipsData, GetContactrelationshipsResponses, PostContactrelationshipsData, PostContactrelationshipsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all contact relationships.
 */
export const getContactrelationships = <ThrowOnError extends boolean = false>(options?: Options<GetContactrelationshipsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetContactrelationshipsResponses, unknown, ThrowOnError>({
        url: '/contactrelationships',
        ...options
    });
};

/**
 * Create a new contact relationship.
 */
export const postContactrelationships = <ThrowOnError extends boolean = false>(options?: Options<PostContactrelationshipsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostContactrelationshipsResponses, unknown, ThrowOnError>({
        url: '/contactrelationships',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single contact relationship record.
 */
export const deleteContactrelationshipsById = <ThrowOnError extends boolean = false>(options: Options<DeleteContactrelationshipsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteContactrelationshipsByIdResponses, unknown, ThrowOnError>({
        url: '/contactrelationships/{id}',
        ...options
    });
};

/**
 * Returns a single contact relationship record.
 */
export const getContactrelationshipsById = <ThrowOnError extends boolean = false>(options: Options<GetContactrelationshipsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetContactrelationshipsByIdResponses, unknown, ThrowOnError>({
        url: '/contactrelationships/{id}',
        ...options
    });
};
