// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedContactDocuments = {
    contactdocuments?: Array<ContactDocument>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    contactdocuments?: ContactDocumentPageData;
};

export type ContactDocumentPageData = {
    /**
     * The total number of contact documents returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of contact documents.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of contact documents.
     */
    prevPage?: string;
    /**
     * A URL to the next page of contact documents.
     */
    nextPage?: string;
};

export type ContactDocument = {
    /**
     * Unique identifier for a contact document.
     */
    readonly id?: number;
    /**
     * The name given to the document.
     */
    name?: string;
    /**
     * Timestamp for when the contact document was created. This is not the created date for the underlying document.
     */
    readonly createdTimestamp?: string;
    /**
     * Timestamp for when the contact document was last modified. This is not the last modified date for the underlying document.
     */
    readonly modifiedTimestamp?: string;
    /**
     * Status for the contact document.
     */
    status?: 'pending' | 'generated' | 'uploaded';
    /**
     * List of one of more keywords associated with the contact document.
     */
    readonly keywords?: string;
    /**
     * A textual summary of the document.
     */
    summary?: string;
    /**
     * The file type for the contact document.
     */
    readonly fileType?: string;
    /**
     * The size (in bytes) of the underlying file.
     */
    readonly fileSize?: number;
    /**
     * Extension of the underlying file.
     */
    readonly extension?: string;
    /**
     * An internal file name assigned to the contact document.
     */
    readonly fileName?: string;
    /**
     * A URL to the contact document.
     */
    readonly sharepointUrl?: string;
    /**
     * An internal reference for the contact document used for downloading the underlying file.
     */
    readonly file?: string;
    links?: ContactDocumentLinks;
};

export type ContactDocumentLinks = {
    /**
     * Unique identifier for a contact to which this contact document is associated.
     */
    participant?: number;
    /**
     * Unique identifier for the containing folder hosting the contact document.
     */
    folder?: string;
    /**
     * Unique identifier for the Actionstep user who created the contact document.
     */
    readonly createdBy?: number;
};

export type CreateContactDocument = {
    /**
     * A name to be given to the document.
     */
    name?: string;
    /**
     * A textual summary of the document.
     */
    summary?: string;
    /**
     * The indentifier for the uploaded file used to create the contact document. The format of the file parameter is important. It must include both the unique file id and the file name (including the file extension) in the format {file_id};{file_name_with_extension}
     */
    file: string;
    links?: CreateContactDocumentLinks;
};

export type CreateContactDocumentLinks = {
    /**
     * Unique identifier for a contact to which the contact document is associated.
     */
    participant: number;
    /**
     * Unique identifier for a document folder for the contact document.
     */
    folder?: string;
};

export type UpdateContactDocument = {
    /**
     * A name to be given to the document.
     */
    name?: string;
    /**
     * A textual summary of the document.
     */
    summary?: string;
    links?: UpdateContactDocumentLinks;
};

export type UpdateContactDocumentLinks = {
    /**
     * Unique identifier for a document folder for the contact document.
     */
    folder?: string;
};

export type PagedContactDocumentsWritable = {
    contactdocuments?: Array<ContactDocumentWritable>;
    meta?: PageMetaData;
};

export type ContactDocumentWritable = {
    /**
     * The name given to the document.
     */
    name?: string;
    /**
     * A textual summary of the document.
     */
    summary?: string;
    links?: ContactDocumentLinksWritable;
};

export type ContactDocumentLinksWritable = {
    /**
     * Unique identifier for a contact to which this contact document is associated.
     */
    participant?: number;
    /**
     * Unique identifier for the containing folder hosting the contact document.
     */
    folder?: string;
};

export type CreateContactDocument2 = CreateContactDocument;

export type UpdateContactDocument2 = UpdateContactDocument;

export type GetContactdocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/contactdocuments';
};

export type GetContactdocumentsResponses = {
    /**
     * OK.
     */
    200: PagedContactDocuments;
};

export type GetContactdocumentsResponse = GetContactdocumentsResponses[keyof GetContactdocumentsResponses];

export type PostContactdocumentsData = {
    body?: CreateContactDocument2;
    path?: never;
    query?: never;
    url: '/contactdocuments';
};

export type PostContactdocumentsResponses = {
    /**
     * OK.
     */
    200: ContactDocument;
};

export type PostContactdocumentsResponse = PostContactdocumentsResponses[keyof PostContactdocumentsResponses];

export type DeleteContactdocumentsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single contact document.
         */
        id: number;
    };
    query?: never;
    url: '/contactdocuments/{id}';
};

export type DeleteContactdocumentsByIdResponses = {
    /**
     * Success, No Content.
     */
    204: void;
};

export type DeleteContactdocumentsByIdResponse = DeleteContactdocumentsByIdResponses[keyof DeleteContactdocumentsByIdResponses];

export type GetContactdocumentsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a single contact document.
         */
        id: number;
    };
    query?: never;
    url: '/contactdocuments/{id}';
};

export type GetContactdocumentsByIdResponses = {
    /**
     * OK.
     */
    200: ContactDocument;
};

export type GetContactdocumentsByIdResponse = GetContactdocumentsByIdResponses[keyof GetContactdocumentsByIdResponses];

export type PutContactdocumentsByIdData = {
    body?: UpdateContactDocument2;
    path: {
        /**
         * Unique identifier for a single contact document.
         */
        id: number;
    };
    query?: never;
    url: '/contactdocuments/{id}';
};

export type PutContactdocumentsByIdResponses = {
    /**
     * OK.
     */
    200: ContactDocument;
};

export type PutContactdocumentsByIdResponse = PutContactdocumentsByIdResponses[keyof PutContactdocumentsByIdResponses];
