import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { actionstepSpecManifest } from '../openapi/manifest';

const GENERATED_NOTICE = '// Auto-generated by scripts/sync-exports.ts. Do not edit manually.';

const FUNCTION_EXPORT_PATTERN =
  /^export\s+(?:async\s+)?(?:const|function)\s+([A-Za-z_$][\w$]*)/gm;

function toExportLine(endpoint: string): string {
  return `export * as ${endpoint} from './clients/${endpoint}';`;
}

function toClientExportLine(endpoint: string): string {
  return `export * as ${endpoint}Client from './clients/${endpoint}/client';`;
}

async function writeFileSafe(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, 'utf8');
}

async function extractSdkExports(endpoint: string): Promise<string[]> {
  const sdkPath = resolve(`src/clients/${endpoint}/sdk.gen.ts`);
  const source = await readFile(sdkPath, 'utf8');
  const names = new Set<string>();
  for (const match of source.matchAll(FUNCTION_EXPORT_PATTERN)) {
    names.add(match[1]);
  }
  return [...names];
}

type AggregateBuild = {
  body: string;
  collisions: Map<string, string[]>;
};

async function buildAggregate(): Promise<AggregateBuild> {
  const endpointExports = await Promise.all(
    actionstepSpecManifest.map(async ({ endpoint }) => ({
      endpoint,
      exports: await extractSdkExports(endpoint),
    })),
  );

  const exportSources = new Map<string, string[]>();
  for (const { endpoint, exports } of endpointExports) {
    for (const name of exports) {
      const sources = exportSources.get(name);
      if (sources) {
        sources.push(endpoint);
      } else {
        exportSources.set(name, [endpoint]);
      }
    }
  }

  const collisions = new Map<string, string[]>();
  const flatExportsByEndpoint = new Map<string, string[]>();

  for (const [name, sources] of exportSources) {
    if (sources.length > 1) {
      collisions.set(name, sources);
      continue;
    }
    const endpoint = sources[0];
    const list = flatExportsByEndpoint.get(endpoint) ?? [];
    list.push(name);
    flatExportsByEndpoint.set(endpoint, list);
  }

  const importLines = actionstepSpecManifest.map(
    ({ endpoint }) => `import { client as ${endpoint}Client } from './clients/${endpoint}/client.gen';`,
  );

  const aggregateArrayLines = [
    'const aggregateClients = [',
    ...actionstepSpecManifest.map(({ endpoint }) => `  ${endpoint}Client,`),
    '] as const;',
  ];

  const collisionLines = collisions.size > 0
    ? [
        '// Flat re-exports skipped for the following names because multiple sub-clients export them.',
        '// Import the conflicting symbol via its namespaced sub-client instead, e.g. `actions.foo`.',
        ...[...collisions.entries()]
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([name, sources]) => `//   ${name} -> ${sources.join(', ')}`),
        '',
      ]
    : [];

  const reExportLines: string[] = [];
  for (const { endpoint } of actionstepSpecManifest) {
    const names = flatExportsByEndpoint.get(endpoint);
    if (!names || names.length === 0) continue;
    names.sort();
    reExportLines.push(
      `export { ${names.join(', ')} } from './clients/${endpoint}';`,
    );
  }

  const body = [
    GENERATED_NOTICE,
    '',
    ...importLines,
    '',
    ...aggregateArrayLines,
    '',
    "export type ActionstepClientConfig = Parameters<(typeof aggregateClients)[number]['setConfig']>[0];",
    '',
    '/**',
    ' * Applies a shared client configuration to every generated Actionstep sub-client',
    ' * in a single call. Use this when you want one base URL, header set, or auth',
    " * strategy for the whole package rather than configuring each domain's client",
    ' * individually.',
    ' */',
    'export function configure(config: ActionstepClientConfig): void {',
    '  for (const client of aggregateClients) {',
    '    (client.setConfig as (cfg: ActionstepClientConfig) => unknown)(config);',
    '  }',
    '}',
    '',
    ...collisionLines,
    ...reExportLines,
    '',
  ].join('\n');

  return { body, collisions };
}

async function main() {
  const namespaceExports = actionstepSpecManifest.flatMap(({ endpoint }) => [
    toExportLine(endpoint),
    toClientExportLine(endpoint),
  ]);

  const { body: aggregateTs, collisions } = await buildAggregate();

  const indexTs = [
    GENERATED_NOTICE,
    '',
    ...namespaceExports,
    '',
    "export * from './aggregate.gen';",
    '',
  ].join('\n');

  const clientsIndexTs = [
    GENERATED_NOTICE,
    '',
    ...namespaceExports.map((line) => line.replace("'./clients/", "'./")),
    '',
  ].join('\n');

  await writeFileSafe(resolve('src/index.ts'), indexTs);
  await writeFileSafe(resolve('src/clients/index.ts'), clientsIndexTs);
  await writeFileSafe(resolve('src/aggregate.gen.ts'), aggregateTs);

  if (collisions.size > 0) {
    console.warn(
      `sync-exports: skipped ${collisions.size} flat export(s) due to collisions across sub-clients (see comments in src/aggregate.gen.ts).`,
    );
  }
}

void main();
