import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { actionstepSpecManifest } from '../openapi/manifest';

const GENERATED_NOTICE = '// Auto-generated by scripts/sync-exports.ts. Do not edit manually.';

function toExportLine(endpoint: string): string {
  return `export * as ${endpoint} from './clients/${endpoint}';`;
}

function toClientExportLine(endpoint: string): string {
  return `export * as ${endpoint}Client from './clients/${endpoint}/client';`;
}

async function writeFileSafe(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, 'utf8');
}

async function main() {
  const exports = actionstepSpecManifest.flatMap(({ endpoint }) => [
    toExportLine(endpoint),
    toClientExportLine(endpoint),
  ]);

  const indexTs = [GENERATED_NOTICE, '', ...exports, ''].join('\n');
  const clientsIndexTs = [GENERATED_NOTICE, '', ...exports.map((line) => line.replace("'./clients/", "'./")), ''].join('\n');

  await writeFileSafe(resolve('src/index.ts'), indexTs);
  await writeFileSafe(resolve('src/clients/index.ts'), clientsIndexTs);
}

void main();
