// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteParticipanttypedatafieldsByIdData, DeleteParticipanttypedatafieldsByIdResponses, GetParticipanttypedatafieldsByIdData, GetParticipanttypedatafieldsByIdResponses, GetParticipanttypedatafieldsData, GetParticipanttypedatafieldsResponses, PostParticipanttypedatafieldsData, PostParticipanttypedatafieldsResponses, PutParticipanttypedatafieldsByIdData, PutParticipanttypedatafieldsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all participant type data fields.
 */
export const getParticipanttypedatafields = <ThrowOnError extends boolean = false>(options?: Options<GetParticipanttypedatafieldsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetParticipanttypedatafieldsResponses, unknown, ThrowOnError>({
        url: '/participanttypedatafields',
        ...options
    });
};

/**
 * Create a new participant type data field.
 */
export const postParticipanttypedatafields = <ThrowOnError extends boolean = false>(options?: Options<PostParticipanttypedatafieldsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostParticipanttypedatafieldsResponses, unknown, ThrowOnError>({
        url: '/participanttypedatafields',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Deletes a single participant type data field record.
 */
export const deleteParticipanttypedatafieldsById = <ThrowOnError extends boolean = false>(options: Options<DeleteParticipanttypedatafieldsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteParticipanttypedatafieldsByIdResponses, unknown, ThrowOnError>({
        url: '/participanttypedatafields/{id}',
        ...options
    });
};

/**
 * Returns a single participant type data field record.
 */
export const getParticipanttypedatafieldsById = <ThrowOnError extends boolean = false>(options: Options<GetParticipanttypedatafieldsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetParticipanttypedatafieldsByIdResponses, unknown, ThrowOnError>({
        url: '/participanttypedatafields/{id}',
        ...options
    });
};

/**
 * Updates a single participant type data field record.
 */
export const putParticipanttypedatafieldsById = <ThrowOnError extends boolean = false>(options: Options<PutParticipanttypedatafieldsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutParticipanttypedatafieldsByIdResponses, unknown, ThrowOnError>({
        url: '/participanttypedatafields/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
