// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://docs.actionstep.com' | (string & {});
};

export type PagedActionParticipants = {
    actionparticipants?: Array<ActionParticipants>;
    meta?: PageMetaData;
};

export type PageMetaData = {
    paging?: PagingData;
};

export type PagingData = {
    actionparticipants?: ActionParticipantsPageData;
};

export type ActionParticipantsPageData = {
    /**
     * The total number of Matter participants returned by the underlying query.
     */
    recordCount?: number;
    /**
     * The total number of pages generated by the underlying query.
     */
    pageCount?: number;
    /**
     * The page number for this page of Matter participants.
     */
    page?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * A URL to the previous page of Matter participants.
     */
    prevPage?: string;
    /**
     * A URL to the next page of Matter participants.
     */
    nextPage?: string;
};

export type ActionParticipants = {
    /**
     * Unique identifier for the Matter participant. The identifier is a composite value composed from the Matter identifier, the participant type identifier, and the participant identifier, separated by "--".
     */
    id?: string;
    /**
     * The order the Matter participants were added to an action.
     */
    participantNumber?: number;
    links?: ActionParticipantsLinks;
};

export type ActionParticipantsLinks = {
    /**
     * Unique identifier of the associated action.
     */
    action?: number;
    /**
     * Unique identifier of the participant type.
     */
    participantType?: number;
    /**
     * Unique identifier of the participant.
     */
    participant?: number;
};

export type CreateActionParticipants = {
    actionparticipants?: CreateActionParticipantsLinks;
};

export type CreateActionParticipantsLinks = {
    links?: CreateActionParticipantsLinksLink;
};

export type CreateActionParticipantsLinksLink = {
    /**
     * Unique identifier of the associated action.
     */
    action?: number;
    /**
     * Unique identifier of the participant type.
     */
    participantType?: number;
    /**
     * Unique identifier of the participant.
     */
    participant?: number;
};

export type CreateActionParticipants2 = CreateActionParticipants;

export type GetActionparticipantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actionparticipants';
};

export type GetActionparticipantsResponses = {
    /**
     * OK.
     */
    200: PagedActionParticipants;
};

export type GetActionparticipantsResponse = GetActionparticipantsResponses[keyof GetActionparticipantsResponses];

export type PostActionparticipantsData = {
    body?: CreateActionParticipants2;
    path?: never;
    query?: never;
    url: '/actionparticipants';
};

export type PostActionparticipantsResponses = {
    /**
     * OK.
     */
    200: ActionParticipants;
};

export type PostActionparticipantsResponse = PostActionparticipantsResponses[keyof PostActionparticipantsResponses];

export type DeleteActionparticipantsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for an Matter participant. The identifier is a composite value composed from the Matter identifier, the participant type identifier, and the participant identifier, separated by "--".
         */
        id: string;
    };
    query?: never;
    url: '/actionparticipants/{id}';
};

export type DeleteActionparticipantsByIdResponses = {
    /**
     * Success, No content.
     */
    204: void;
};

export type DeleteActionparticipantsByIdResponse = DeleteActionparticipantsByIdResponses[keyof DeleteActionparticipantsByIdResponses];

export type GetActionparticipantsByIdData = {
    body?: never;
    path: {
        /**
         * Unique identifier for a Matter Participant. The identifier is a composite value composed from the Matter identifier, the participant type identifier, and the participant identifier, separated by "--".
         */
        id: string;
    };
    query?: never;
    url: '/actionparticipants/{id}';
};

export type GetActionparticipantsByIdResponses = {
    /**
     * OK.
     */
    200: ActionParticipants;
};

export type GetActionparticipantsByIdResponse = GetActionparticipantsByIdResponses[keyof GetActionparticipantsByIdResponses];
