// This file is auto-generated by @hey-api/openapi-ts

export const PagedPhoneRecordsSchema = {
    type: 'object',
    properties: {
        phonerecords: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PhoneRecord'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PageMetaDataSchema = {
    type: 'object',
    properties: {
        paging: {
            '$ref': '#/components/schemas/PagingData'
        }
    }
} as const;

export const PagingDataSchema = {
    type: 'object',
    properties: {
        phonerecords: {
            '$ref': '#/components/schemas/PhoneRecordPageData'
        }
    }
} as const;

export const PhoneRecordPageDataSchema = {
    type: 'object',
    properties: {
        recordCount: {
            description: 'The total number of phone records returned by the underlying query.',
            type: 'integer',
            example: 2487
        },
        pageCount: {
            description: 'The total number of pages generated by the underlying query.',
            type: 'integer',
            example: 50
        },
        page: {
            description: 'The page number for this page of phone records.',
            type: 'integer',
            example: 2
        },
        pageSize: {
            description: 'Page size.',
            type: 'integer',
            example: 50
        },
        prevPage: {
            description: 'A URL to the previous page of phone records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/phonerecords?page=1'
        },
        nextPage: {
            description: 'A URL to the next page of phone records.',
            type: 'string',
            example: 'https://ap-southeast-2.actionstep.com/api/rest/phonerecords?page=3'
        }
    }
} as const;

export const PhoneRecordSchema = {
    type: 'object',
    properties: {
        id: {
            description: 'Unique identifier for a phone record.',
            type: 'integer',
            format: 'integer',
            example: 1176,
            readOnly: true
        },
        fromParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an incoming call.',
            type: 'string',
            format: 'string',
            example: 'John Smith'
        },
        toParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an outgoing call.',
            type: 'string',
            format: 'string',
            example: 'AJ Accountants LLC'
        },
        direction: {
            description: 'Direction of the call.',
            enum: ['in', 'out'],
            type: 'string',
            format: 'string',
            example: 'out'
        },
        phoneNumber: {
            description: 'Phone number.',
            type: 'string',
            format: 'string',
            example: '+44 493 993938'
        },
        phoneNumberType: {
            description: 'A type associated to the phone number.',
            type: 'string',
            format: 'string',
            example: 'Business'
        },
        actualHours: {
            description: 'The duration of the call measured in hours.',
            type: 'number',
            format: 'string',
            example: 0.25
        },
        notes: {
            description: 'Notes taken from the call.',
            type: 'string',
            format: 'string',
            example: 'Discussed progress for this week.'
        },
        callTimestamp: {
            description: 'Date and time of the phone call.',
            type: 'string',
            format: 'timestamp',
            example: '2025-09-17T09:12:32+12:00'
        },
        outcome: {
            description: 'Indicates the outcome for the call.',
            type: 'string',
            format: 'string',
            example: 'Call completed'
        },
        links: {
            '$ref': '#/components/schemas/PhoneRecordLinks'
        }
    }
} as const;

export const PhoneRecordLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the phone record is associated.',
            example: 321845,
            type: 'integer'
        },
        fromParticipant: {
            description: 'Unique identifier for a participant from whom the call was received.',
            example: 8945,
            type: 'integer'
        },
        toParticipant: {
            description: 'Unique identifier for a participant to whom the call was made.',
            example: 4912,
            type: 'integer'
        }
    }
} as const;

export const CreatePhoneRecordSchema = {
    type: 'object',
    required: ['direction', 'callTimestamp', 'outcome'],
    properties: {
        fromParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an incoming call.',
            type: 'string',
            format: 'string',
            example: 'John Smith'
        },
        toParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an outgoing call.',
            type: 'string',
            format: 'string',
            example: 'AJ Accountants LLC'
        },
        direction: {
            description: 'Direction of the call.',
            enum: ['in', 'out'],
            type: 'string',
            format: 'string',
            example: 'out'
        },
        phoneNumber: {
            description: 'Phone number.',
            type: 'string',
            format: 'string',
            example: '+44 493 993938'
        },
        phoneNumberType: {
            description: 'A type associated to the phone number.',
            type: 'string',
            format: 'string',
            example: 'Business'
        },
        actualHours: {
            description: 'The duration of the call measured in hours.',
            type: 'number',
            format: 'string',
            example: 0.25
        },
        notes: {
            description: 'Notes taken from the call.',
            type: 'string',
            format: 'string',
            example: 'Discussed progress for this week.'
        },
        callTimestamp: {
            description: 'Date and time of the phone call.',
            type: 'string',
            format: 'timestamp',
            example: '2025-09-17T09:12:32+12:00'
        },
        outcome: {
            description: 'Indicates the outcome for the call.',
            type: 'string',
            format: 'string',
            example: 'Call completed'
        },
        links: {
            '$ref': '#/components/schemas/CreatePhoneRecordLinks'
        }
    }
} as const;

export const CreatePhoneRecordLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the phone record is associated.',
            example: 321845,
            type: 'integer'
        },
        fromParticipant: {
            description: 'Unique identifier for a participant from whom the call was received.',
            example: 8945,
            type: 'integer'
        },
        toParticipant: {
            description: 'Unique identifier for a participant to whom the call was made.',
            example: 4912,
            type: 'integer'
        }
    }
} as const;

export const UpdatePhoneRecordSchema = {
    type: 'object',
    properties: {
        fromParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an incoming call.',
            type: 'string',
            format: 'string',
            example: 'John Smith'
        },
        toParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an outgoing call.',
            type: 'string',
            format: 'string',
            example: 'AJ Accountants LLC'
        },
        direction: {
            description: 'Direction of the call.',
            enum: ['in', 'out'],
            type: 'string',
            format: 'string',
            example: 'out'
        },
        phoneNumber: {
            description: 'Phone number.',
            type: 'string',
            format: 'string',
            example: '+44 493 993938'
        },
        phoneNumberType: {
            description: 'A type associated to the phone number.',
            type: 'string',
            format: 'string',
            example: 'Business'
        },
        actualHours: {
            description: 'The duration of the call measured in hours.',
            type: 'number',
            format: 'string',
            example: 0.25
        },
        notes: {
            description: 'Notes taken from the call.',
            type: 'string',
            format: 'string',
            example: 'Discussed progress for this week.'
        },
        callTimestamp: {
            description: 'Date and time of the phone call.',
            type: 'string',
            format: 'timestamp',
            example: '2025-09-17T09:12:32+12:00'
        },
        outcome: {
            description: 'Indicates the outcome for the call.',
            type: 'string',
            format: 'string',
            example: 'Call completed'
        },
        links: {
            '$ref': '#/components/schemas/UpdatePhoneRecordLinks'
        }
    }
} as const;

export const UpdatePhoneRecordLinksSchema = {
    type: 'object',
    properties: {
        action: {
            description: 'Unique identifier of the matter to which the phone record is associated.',
            example: 321845,
            type: 'integer'
        },
        fromParticipant: {
            description: 'Unique identifier for a participant from whom the call was received.',
            example: 8945,
            type: 'integer'
        },
        toParticipant: {
            description: 'Unique identifier for a participant to whom the call was made.',
            example: 4912,
            type: 'integer'
        }
    }
} as const;

export const PagedPhoneRecordsWritableSchema = {
    type: 'object',
    properties: {
        phonerecords: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PhoneRecordWritable'
            }
        },
        meta: {
            '$ref': '#/components/schemas/PageMetaData'
        }
    }
} as const;

export const PhoneRecordWritableSchema = {
    type: 'object',
    properties: {
        fromParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an incoming call.',
            type: 'string',
            format: 'string',
            example: 'John Smith'
        },
        toParticipantOther: {
            description: 'Used to record the name of an individual or company not held in Actionstep for an outgoing call.',
            type: 'string',
            format: 'string',
            example: 'AJ Accountants LLC'
        },
        direction: {
            description: 'Direction of the call.',
            enum: ['in', 'out'],
            type: 'string',
            format: 'string',
            example: 'out'
        },
        phoneNumber: {
            description: 'Phone number.',
            type: 'string',
            format: 'string',
            example: '+44 493 993938'
        },
        phoneNumberType: {
            description: 'A type associated to the phone number.',
            type: 'string',
            format: 'string',
            example: 'Business'
        },
        actualHours: {
            description: 'The duration of the call measured in hours.',
            type: 'number',
            format: 'string',
            example: 0.25
        },
        notes: {
            description: 'Notes taken from the call.',
            type: 'string',
            format: 'string',
            example: 'Discussed progress for this week.'
        },
        callTimestamp: {
            description: 'Date and time of the phone call.',
            type: 'string',
            format: 'timestamp',
            example: '2025-09-17T09:12:32+12:00'
        },
        outcome: {
            description: 'Indicates the outcome for the call.',
            type: 'string',
            format: 'string',
            example: 'Call completed'
        },
        links: {
            '$ref': '#/components/schemas/PhoneRecordLinks'
        }
    }
} as const;
