// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeletePhonerecordsByIdData, DeletePhonerecordsByIdResponses, GetPhonerecordsByIdData, GetPhonerecordsByIdResponses, GetPhonerecordsData, GetPhonerecordsResponses, PostPhonerecordsData, PostPhonerecordsResponses, PutPhonerecordsByIdData, PutPhonerecordsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all phone records.
 */
export const getPhonerecords = <ThrowOnError extends boolean = false>(options?: Options<GetPhonerecordsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPhonerecordsResponses, unknown, ThrowOnError>({
        url: '/phonerecords',
        ...options
    });
};

/**
 * Create a new phone record.
 */
export const postPhonerecords = <ThrowOnError extends boolean = false>(options?: Options<PostPhonerecordsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostPhonerecordsResponses, unknown, ThrowOnError>({
        url: '/phonerecords',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete a single phone record.
 */
export const deletePhonerecordsById = <ThrowOnError extends boolean = false>(options: Options<DeletePhonerecordsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeletePhonerecordsByIdResponses, unknown, ThrowOnError>({
        url: '/phonerecords/{id}',
        ...options
    });
};

/**
 * Returns a single phone record.
 */
export const getPhonerecordsById = <ThrowOnError extends boolean = false>(options: Options<GetPhonerecordsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPhonerecordsByIdResponses, unknown, ThrowOnError>({
        url: '/phonerecords/{id}',
        ...options
    });
};

/**
 * Updates a single phone record.
 */
export const putPhonerecordsById = <ThrowOnError extends boolean = false>(options: Options<PutPhonerecordsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutPhonerecordsByIdResponses, unknown, ThrowOnError>({
        url: '/phonerecords/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
