// Auto-generated by scripts/sync-exports.ts. Do not edit manually.

import { client as actionsClient } from './clients/actions/client.gen';
import { client as actionbillsettingsClient } from './clients/actionbillsettings/client.gen';
import { client as actionfoldersClient } from './clients/actionfolders/client.gen';
import { client as actionnetdocssettingsClient } from './clients/actionnetdocssettings/client.gen';
import { client as actionparticipantsClient } from './clients/actionparticipants/client.gen';
import { client as actiontypesClient } from './clients/actiontypes/client.gen';
import { client as actiontypeparticipanttypesClient } from './clients/actiontypeparticipanttypes/client.gen';
import { client as billsClient } from './clients/bills/client.gen';
import { client as contactdocumentsClient } from './clients/contactdocuments/client.gen';
import { client as contactfoldersClient } from './clients/contactfolders/client.gen';
import { client as contactnotesClient } from './clients/contactnotes/client.gen';
import { client as contactrelationshipsClient } from './clients/contactrelationships/client.gen';
import { client as culturalidentityClient } from './clients/culturalidentity/client.gen';
import { client as datacollectionsClient } from './clients/datacollections/client.gen';
import { client as datacollectionfieldsClient } from './clients/datacollectionfields/client.gen';
import { client as datacollectionfielddropdownchoicesClient } from './clients/datacollectionfielddropdownchoices/client.gen';
import { client as datacollectionrecordsClient } from './clients/datacollectionrecords/client.gen';
import { client as datacollectionrecordvaluesClient } from './clients/datacollectionrecordvalues/client.gen';
import { client as disabilitystatusClient } from './clients/disabilitystatus/client.gen';
import { client as disbursementsClient } from './clients/disbursements/client.gen';
import { client as filenotesClient } from './clients/filenotes/client.gen';
import { client as gendertypesClient } from './clients/gendertypes/client.gen';
import { client as participantsClient } from './clients/participants/client.gen';
import { client as participantadditionalnotificationmethodsClient } from './clients/participantadditionalnotificationmethods/client.gen';
import { client as participantdatafielddropdownchoicesClient } from './clients/participantdatafielddropdownchoices/client.gen';
import { client as participantrelationshiptypesClient } from './clients/participantrelationshiptypes/client.gen';
import { client as participantdefaulttypesClient } from './clients/participantdefaulttypes/client.gen';
import { client as participanttypedatafieldsClient } from './clients/participanttypedatafields/client.gen';
import { client as phonerecordsClient } from './clients/phonerecords/client.gen';
import { client as primarylanguageClient } from './clients/primarylanguage/client.gen';
import { client as quickcodesClient } from './clients/quickcodes/client.gen';
import { client as resthooksClient } from './clients/resthooks/client.gen';
import { client as timeentriesClient } from './clients/timeentries/client.gen';
import { client as tasksClient } from './clients/tasks/client.gen';
import { client as utbmscodesClient } from './clients/utbmscodes/client.gen';

const aggregateClients = [
  actionsClient,
  actionbillsettingsClient,
  actionfoldersClient,
  actionnetdocssettingsClient,
  actionparticipantsClient,
  actiontypesClient,
  actiontypeparticipanttypesClient,
  billsClient,
  contactdocumentsClient,
  contactfoldersClient,
  contactnotesClient,
  contactrelationshipsClient,
  culturalidentityClient,
  datacollectionsClient,
  datacollectionfieldsClient,
  datacollectionfielddropdownchoicesClient,
  datacollectionrecordsClient,
  datacollectionrecordvaluesClient,
  disabilitystatusClient,
  disbursementsClient,
  filenotesClient,
  gendertypesClient,
  participantsClient,
  participantadditionalnotificationmethodsClient,
  participantdatafielddropdownchoicesClient,
  participantrelationshiptypesClient,
  participantdefaulttypesClient,
  participanttypedatafieldsClient,
  phonerecordsClient,
  primarylanguageClient,
  quickcodesClient,
  resthooksClient,
  timeentriesClient,
  tasksClient,
  utbmscodesClient,
] as const;

export type ActionstepClientConfig = Parameters<(typeof aggregateClients)[number]['setConfig']>[0];

/**
 * Applies a shared client configuration to every generated Actionstep sub-client
 * in a single call. Use this when you want one base URL, header set, or auth
 * strategy for the whole package rather than configuring each domain's client
 * individually.
 */
export function configure(config: ActionstepClientConfig): void {
  for (const client of aggregateClients) {
    (client.setConfig as (cfg: ActionstepClientConfig) => unknown)(config);
  }
}

export { getActions, getActionsById, patchActionsById } from './clients/actions';
export { getActionbillsettings, getActionbillsettingsById, putActionbillsettingsById } from './clients/actionbillsettings';
export { getActionfolders, getActionfoldersById } from './clients/actionfolders';
export { deleteActionnetdocssettingsById, getActionnetdocssettings, getActionnetdocssettingsById, postActionnetdocssettings, putActionnetdocssettingsById } from './clients/actionnetdocssettings';
export { deleteActionparticipantsById, getActionparticipants, getActionparticipantsById, postActionparticipants } from './clients/actionparticipants';
export { getActiontypes } from './clients/actiontypes';
export { deleteActiontypeparticipanttypesById, getActiontypeparticipanttypes, getActiontypeparticipanttypesById, postActiontypeparticipanttypes, putActiontypeparticipanttypesById } from './clients/actiontypeparticipanttypes';
export { getBills } from './clients/bills';
export { deleteContactdocumentsById, getContactdocuments, getContactdocumentsById, postContactdocuments, putContactdocumentsById } from './clients/contactdocuments';
export { deleteContactfoldersById, getContactfolders, getContactfoldersById, postContactfolders, putContactfoldersById } from './clients/contactfolders';
export { deleteContactnotesById, getContactnotes, getContactnotesById, postContactnotes, putContactnotesById } from './clients/contactnotes';
export { deleteContactrelationshipsById, getContactrelationships, getContactrelationshipsById, postContactrelationships } from './clients/contactrelationships';
export { getCulturalidentity } from './clients/culturalidentity';
export { deleteDatacollectionById, getDatacollectionById, getDatacollections, postDatacollections, putDatacollectionById } from './clients/datacollections';
export { deleteDatacollectionfieldById, getDatacollectionfieldById, getDatacollectionfields, postDatacollectionfields, putDatacollectionfieldById } from './clients/datacollectionfields';
export { deleteDatacollectionfielddropdownchoicesById, getDatacollectionfielddropdownchoices, getDatacollectionfielddropdownchoicesById, postDatacollectionfielddropdownchoices, putDatacollectionfielddropdownchoicesById } from './clients/datacollectionfielddropdownchoices';
export { deleteDatacollectionrecordsById, getDatacollectionrecords, getDatacollectionrecordsById, postDatacollectionrecords } from './clients/datacollectionrecords';
export { getDatacollectionrecordvalues, getDatacollectionrecordvaluesById, postDatacollectionrecordvalues, putDatacollectionrecordvaluesById } from './clients/datacollectionrecordvalues';
export { getDisabilitystatus } from './clients/disabilitystatus';
export { deleteDisbursementsById, getDisbursements, getDisbursementsById, postDisbursements, putDisbursementsById } from './clients/disbursements';
export { deleteFilenotesById, getFilenotes, getFilenotesById, postFilenotes, putFilenotesById } from './clients/filenotes';
export { deleteGendertypesByGenderTypeName, getGendertypes, getGendertypesByGenderTypeName, postGendertypes, putGendertypesByGenderTypeName } from './clients/gendertypes';
export { getParticipants, getParticipantsById, postParticipants, putParticipantsById } from './clients/participants';
export { deleteParticipantadditionalnotificationmethodsById, getParticipantadditionalnotificationmethods, getParticipantadditionalnotificationmethodsById, postParticipantadditionalnotificationmethods, putParticipantadditionalnotificationmethodsById } from './clients/participantadditionalnotificationmethods';
export { deleteParticipantdatafielddropdownchoicesById, getParticipantdatafielddropdownchoices, getParticipantdatafielddropdownchoicesById, postParticipantdatafielddropdownchoices, putParticipantdatafielddropdownchoicesById } from './clients/participantdatafielddropdownchoices';
export { deleteParticipantrelationshiptypesById, getParticipantrelationshiptypes, getParticipantrelationshiptypesById, postParticipantrelationshiptypes } from './clients/participantrelationshiptypes';
export { deleteParticipantdefaulttypesById, getParticipantdefaulttypes, postParticipantdefaulttypes } from './clients/participantdefaulttypes';
export { deleteParticipanttypedatafieldsById, getParticipanttypedatafields, getParticipanttypedatafieldsById, postParticipanttypedatafields, putParticipanttypedatafieldsById } from './clients/participanttypedatafields';
export { deletePhonerecordsById, getPhonerecords, getPhonerecordsById, postPhonerecords, putPhonerecordsById } from './clients/phonerecords';
export { getPrimarylanguage } from './clients/primarylanguage';
export { getQuickcodes, getQuickcodesById, postQuickcodes, putQuickcodesById } from './clients/quickcodes';
export { deleteResthooksById, getResthooks, getResthooksById, postResthooks, putResthooksById } from './clients/resthooks';
export { deleteTimeentriesById, getTimeentries, getTimeentriesById, postTimeentries, putTimeentriesById } from './clients/timeentries';
export { deleteTasksById, getTasks, getTasksById, postTasks, putTasksById } from './clients/tasks';
export { deleteUtbmscodesById, getUtbmscodes, getUtbmscodesById, postUtbmscodes, putUtbmscodesById } from './clients/utbmscodes';
