// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetActionfoldersByIdData, GetActionfoldersByIdResponses, GetActionfoldersData, GetActionfoldersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Returns the collection of all folders for all Matters. For information on how to construct requests filtering by various properties, please refer to the API Developer Portal.
 */
export const getActionfolders = <ThrowOnError extends boolean = false>(options?: Options<GetActionfoldersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetActionfoldersResponses, unknown, ThrowOnError>({
        url: '/actionfolders',
        ...options
    });
};

/**
 * Returns a single Matter folder.
 */
export const getActionfoldersById = <ThrowOnError extends boolean = false>(options: Options<GetActionfoldersByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetActionfoldersByIdResponses, unknown, ThrowOnError>({
        url: '/actionfolders/{id}',
        ...options
    });
};
