// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type FileCreatePayload = {
    data?: {
        [key: string]: unknown;
    };
    [key: string]: unknown | {
        [key: string]: unknown;
    } | undefined;
};

export type ActionstepDocumentResponse = {
    data?: {
        [key: string]: unknown;
    };
    [key: string]: unknown | {
        [key: string]: unknown;
    } | undefined;
};

export type ActionstepListResponse = {
    data?: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown | Array<{
        [key: string]: unknown;
    }> | undefined;
};

export type GetFilesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/files';
};

export type GetFilesResponses = {
    /**
     * OK
     */
    200: ActionstepListResponse;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type PostFilesData = {
    body: FileCreatePayload;
    path?: never;
    query?: never;
    url: '/files';
};

export type PostFilesResponses = {
    /**
     * Created
     */
    201: ActionstepDocumentResponse;
};

export type PostFilesResponse = PostFilesResponses[keyof PostFilesResponses];

export type GetFilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        part_number?: number;
    };
    url: '/files/{id}';
};

export type GetFilesByIdResponses = {
    /**
     * OK
     */
    200: ActionstepDocumentResponse;
};

export type GetFilesByIdResponse = GetFilesByIdResponses[keyof GetFilesByIdResponses];
